### ISSUE TITLE
Update the documentation for Talawa-Admin

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-docs#108]
As the whole codebase of Talawa-Admin has been changed from vue js to react js there is a need to update the Talawa-Admin part of docs so that contributors can get a clear idea about the technologies used in the project @palisadoes sir

**Comment by palisadoes** [comment]
I searched the documentation and there is no reference to Vue. Please show me the examples you are referring to.

**Comment by XshubhamX** [comment]
@palisadoes sir I mean currently there is no documentation for talawa admin I was thinking that as soon as i make a pr for login page and home page for talawa admin ,I can start work on creating the documentation for it

**Comment by palisadoes** [comment]
OK. Please add the documentation to talawa-docs.
