### ISSUE TITLE
documentation needs editing

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-docs#111]
While exploring about talawa, I went through the documentation and came across few errors that needs to be resolved for better documentation.

@palisadoes 
Can I work on this issue ?

**Comment by palisadoes** [comment]
What are the specific errors? The request is too vague.

**Comment by ssaumyaa7** [comment]
@palisadoes sir, there are spell errors and that as doesn't looks good eg. In the organisation part in documents there are misspelled words like intigrel rather it should be integral 

These are minors mistakes but do need editing.

**Comment by ssaumyaa7** [comment]
@palisadoes Sir, corrected and improved documentation

Generated pull request #118
