### ISSUE TITLE
Improvement in the documentation

### ISSUE THREAD

**Issue by Mobasherah12** [PalisadoesFoundation/talawa-docs#157]
Hi, I would like to recommend an additional point in the following documentation link:
https://github.com/PalisadoesFoundation/talawa-docs/blob/master/docs/internships/gsoc/introduction.md

Under the title **Students Read This**, a necessary change should be added according to GSoC 2022:
14. Read more about the [changes in the eligibilty criteria for GSoC 2022](https://opensource.googleblog.com/2021/11/expanding-google-summer-of-code-in-2022.html#:~:text=Expanding%20Google%20Summer%20of%20Code%20in%202022%20Wednesday%2C,source%20contributors%20into%20OSS%20communities%20big%20and%20small.).

**Comment by palisadoes** [comment]
Thanks @Mobasherah12 I merged your PR, however you need to follow procedure. Create the issue, get the issue assigned to you, then submit the PR.

- https://github.com/PalisadoesFoundation/talawa/issues/359

I appreciate the enthusiasm, but we really need to ensure consistent code and process. We have many competing issues, and we want to make sure everyone gets a chance to participate.

**Comment by Mobasherah12** [comment]
> Thanks @Mobasherah12 I merged your PR, however you need to follow procedure. Create the issue, get the issue assigned to you, then submit the PR.
> 
> * [Student Internship Programs talawa#359](https://github.com/PalisadoesFoundation/talawa/issues/359)
> 
> I appreciate the enthusiasm, but we really need to ensure consistent code and process. We have many competing issues, and we want to make sure everyone gets a chance to participate.

Thank you for letting me know. I will keep that in mind from now onwards.
