### ISSUE TITLE
Improve Theming 

### ISSUE THREAD

**Issue by jordanliu** [PalisadoesFoundation/talawa-docs#17]
The styling for the docs need to be improved from the default theme, this could just be a colour change and to modify the default placeholders on the homepage.

**Comment by yasharth291** [comment]
can you please assign me this

**Comment by yasharth291** [comment]
i can help you in it

**Comment by jordanliu** [comment]
@yasharth291 assigned.

Basically, we need to change the colours from the default green maybe a light blue.

Additionally,
we need to swap out these tiles 
![image](https://user-images.githubusercontent.com/9423525/111543017-76757d00-8740-11eb-95e3-9fa1618b7374.png)

1. What Talawa is 
2. Open Source information
3. Information about Palisadoes

**Comment by yasharth291** [comment]
okay sir you want to change the theme to some blue one and can i add one more addition of dark mode in it?

**Comment by jordanliu** [comment]
Sounds good

**Comment by yasharth291** [comment]
okay sir working on the same

**Comment by vedant-ingole** [comment]
@jordanliu  Sir! I would love to work on changing the theme to blue and some basic animation to the webpage. @jordanliu
