### ISSUE TITLE
[API Docs] Automate the generation of docs for Talawa API

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa-docs#188]
**Overview**

- We need a semi/fully automated method of updating our documentation as the codebase changes overtime. The main orchestrator of things will be our CI/CD pipeline through use of a couple actions for ease of management and accountability. 
- Additionally, we will need to update the contributions.md/code of conduct to require users to make updates to the documentation where necessary. 

### Please refer to the Parent issue for comprehensive coverage of what needs to be done for ALL repos, not just Talawa-API.

Parent issue:
- https://github.com/PalisadoesFoundation/talawa-docs/issues/191

Child issues: 
- https://github.com/PalisadoesFoundation/talawa-api/issues/474 
- https://github.com/PalisadoesFoundation/talawa-api/issues/480

**Comment by palisadoes** [comment]
Ideally, we should also include these features as part of the solution:
- Automatically create documentation, not just for GraphQL, but also the node.js code base in general. (Should this be a separate issue?)
- Create a dashboard to track the percentage documentation creation for each code base file, class, method and function. This dashboard can be via a third-party cloud service, preferably free for open-source projects.
- Check the percentage coverage of documentation of each class, function, and method in the code submitted in PRs and reject the PR if the documentation is at an insufficient level.

**Comment by palisadoes** [comment]
Completed
