### ISSUE TITLE
[API Docs] Automate the generation of docs for the Flutter App

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa-docs#189]
The technical documentation across all Talawa projects needs to be greatly improved. One way of achieving this goal is to find ways of adding documentation into the files of each code base in such a way that an external website such as that created by the Talawa-Docs repo is automatically updated. We foresee that this will require PR CI/CD integration Talawa-Docs between Talawa, Talawa-API and Talawa-Admin.

**Problem Statement**

We need to find a way to:

- Consistently update the Talawa Flutter code base to facilitate the creation of automated documentation.
- Integrate the documentation creation process into Talawa-Docs
- Create a dashboard to track the percentage documentation creation for each code base file, class, method and function. This dashboard can be via a third-party cloud service, preferably free for open-source projects.
- Check the percentage coverage of documentation of each class, function, and method in the code submitted in PRs and reject the PR if the documentation is at an insufficient level. 

Parent Issue:
- https://github.com/PalisadoesFoundation/talawa-docs/issues/191

Child Issues:
- https://github.com/PalisadoesFoundation/talawa/issues/1215
- https://github.com/PalisadoesFoundation/talawa/issues/1216

**Comment by adepeju4** [comment]
Hi, i read the description of this issue and its parent issue, and i think i might be able to figure it out overtime. Can i be assigned to this issue?

**Comment by palisadoes** [comment]
This is actually completed. The documentation is automatically updated from talawa with every successful merge of a pull request. 

Closing. Thanks for asking. We'll be creating more issues soon.
