### ISSUE TITLE
[API Docs] Automate the generation of docs for Talawa Admin

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa-docs#190]
The technical documentation across all Talawa projects needs to be greatly improved. One way of achieving this goal is to find ways of adding documentation into the files of each code base in such a way that an external website such as that created by the Talawa-Docs repo is automatically updated. We foresee that this will require PR CI/CD integration Talawa-Docs between Talawa, Talawa-API and Talawa-Admin.

**Problem Statement**

We need to find a way to:

- Consistently update the Talawa-Admin code base to facilitate the creation of automated documentation.
- Integrate the documentation creation process into Talawa-Docs
- Create a dashboard to track the percentage documentation creation for each code base file, class, method and function. This dashboard can be via a third-party cloud service, preferably free for open-source projects.
- Check the percentage coverage of documentation of each class, function, and method in the code submitted in PRs and reject the PR if the documentation is at an insufficient level. 

Parent Issue:
- https://github.com/PalisadoesFoundation/talawa-docs/issues/191

**Comment by Himanshiii-14** [comment]
Hello, I want to work on this. Please assign this to me

**Comment by Himanshiii-14** [comment]
@DMills27 
Hello, is this issue still to be resolved?
I want to work on this

**Comment by palisadoes** [comment]
Yes we still need to do it. If you are interested in working on it please talk to:

- @tasneemkoushar 
- @evasharma12 
- @anwersayeed 

Here or on slack.

**Comment by elizabeth-agada** [comment]
Hello, has this issue been assigned?
i would love to work and learn a lot from doing it.

**Comment by evasharma12** [comment]
> Hello, has this issue been assigned? i would love to work and learn a lot from doing it.

@elizabeth-agada Can you share your ideas on this issue? How are you planning to proceed with it.

**Comment by elizabeth-agada** [comment]
Okay @evasharma12 i intend to choose a documentation generation tool, I'm more comfortable with postman,
define the routes for the API, including the HTTP method, URL, and any parameters required.
Document each endpoint by describing the purpose of the endpoint and the data that it accepts and returns, include an example of the doc so users get to understand how to use the API and then using a (CI/CD) pipeline to automatically generate and publish the documentation whenever changes are made to the API code.

**Comment by KinetiCore-Labs** [comment]
> Okay @evasharma12 i intend to choose a documentation generation tool, I'm more comfortable with postman, define the routes for the API, including the HTTP method, URL, and any parameters required. Document each endpoint by describing the purpose of the endpoint and the data that it accepts and returns, include an example of the doc so users get to understand how to use the API and then using a (CI/CD) pipeline to automatically generate and publish the documentation whenever changes are made to the API code.

Hi @elizabeth-agada. 
Currently we are using Docusaurus to generate our documentation website [Link](https://docs.talawa.io/). It uses Markdowns (preferred) as well as HTML to build our website. 

You can reach out to me on Slack, so that we can discuss more about your approach. Please prepare a demo about your automation plan.

**Comment by elizabeth-agada** [comment]
Okay, I will be sure to reach out.
Thank you so much.

**Comment by elizabeth-agada** [comment]
Hello @evasharma12 
i dropped a message on slack.

**Comment by suhana832** [comment]
can you assign this issue to me ?

**Comment by elizabeth-agada** [comment]
I'm working on it

**Comment by Cioppolo14** [comment]
@elizabeth-agada Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.
