### ISSUE TITLE
Creating Icon for Talawa Docs

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa-docs#2]
I can create a good logo/icon for the Talawa Docs and my idea was to use the existing Talawa Icon and add some letter or document symbol to it to make it look even better and thus would relate to the Main Talawa App itself

Will give the Vector files also :)

**Comment by jordanliu** [comment]
Sure, let's see what you have in mind :)

**Comment by adithyaakrishna** [comment]
Thanks @jordanliu , I've shared you some ideas over Slack and do let me know your thoughts on them :)

**Comment by gauravdas014** [comment]
@jordanliu Can you give me the link for joining the slack channel?

**Comment by palisadoes** [comment]
We have finalized logos for the project
