### ISSUE TITLE
Format static HTML files approved in pull requests to be consistent with the rest of the site

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa-docs#200]
After the completion of https://github.com/PalisadoesFoundation/talawa-docs/issues/199, create a CI/CD pipeline (with Github actions) that adds formatting to the file sent in the pull request. The task is to guarantee that the contents of the file being added from the pull request is essentially copied over and injected into a template from https://github.com/PalisadoesFoundation/talawa-docs/issues/199, such that the styling is consistent with the rest of the site and nothing breaks in the page. Additionally, add a check that the file being formatted is an .html file beforehand.

**Parent Issue**
- https://github.com/PalisadoesFoundation/talawa-docs/issues/191

**Comment by vedant-z** [comment]
Hey @DMills27 May I work on this?

**Comment by DMills27** [comment]
@vedant-z I've assigned it to you.

**Comment by itsgurmannatsohal** [comment]
@DMills27 I see that there hasn't been any activity for a while now. Can this issue be assigned to me?

**Comment by palisadoes** [comment]
@itsgurmannatsohal You may want to coordinate your efforts with 

- @garvit3835
- @tasneemkoushar 

Who are working on this issue:

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199

The two are closely related

**Comment by itsgurmannatsohal** [comment]
Okay. So, I should create a CI/CD pipeline for all pull requests, right? The title says approved pull requests, so how are the approved ones marked?

**Comment by Ukaoha** [comment]
How do i get this issue assigned to me please

**Comment by Merveille-Louange** [comment]
@itsgurmannatsohal I would like to work on this issue with u, can I have it assigned to me as well?

**Comment by itsgurmannatsohal** [comment]
@Merveille-Louange Yeah, you go ahead and work on it. @DMills27, I'm sorry but it seems I'll be unable to work on this issue. Could it be unassigned please? Thank you

**Comment by Merveille-Louange** [comment]
> @Merveille-Louange Yeah, you go ahead and work on it. @DMills27, I'm sorry but it seems I'll be unable to work on this issue. Could it be unassigned please? Thank you

Can I please have this issue assigned to me?

**Comment by itstasneem** [comment]
@Merveille-Louange is there any update on how will you approach the issue??
