### ISSUE TITLE
fix: typo error in gsod idea.md

### ISSUE THREAD

**Issue by vedant-jain03** [PalisadoesFoundation/talawa-docs#222]
There is a typo error in Idea List > Project 2 > Additional information follows > 3rd point

Screenshot Preview:

![Screenshot from 2022-04-12 20-44-04](https://user-images.githubusercontent.com/76901313/162995356-cc122744-a5df-487f-949b-1399a4c858bc.png)

**Comment by vedant-jain03** [comment]
@DMills27 I would love to work on this issue, if you allow?

**Comment by palisadoes** [comment]
Thanks for letting us know. This has been fixed.
