### ISSUE TITLE
Second Doc link is broken

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-docs#225]
The Second Doc Link in the Footer section of the Documentation website isn't working.
On clicking it, we are directed to `Page Not Found`.
* if you click on `Second Doc`
![Screenshot from 2022-04-17 10-48-49](https://user-images.githubusercontent.com/57287988/163701680-7abb0afe-d1b9-4001-9cc5-7babf8b782cb.png)
* You will be directed to `Page Not Found`
![Screenshot from 2022-04-17 10-49-07](https://user-images.githubusercontent.com/57287988/163701684-bb286e56-ef0e-401e-bec6-c56ba20fcfc0.png)

**Comment by palisadoes** [comment]
Do you want to work on this? Ideally we should have no static links to docs in the footer. The auto-generated pages in `/docs` are sufficient at this time.

**Comment by anwersayeed** [comment]
@palisadoes Should I remove this `Second Doc` from the footer??

**Comment by palisadoes** [comment]
Yes.

**Comment by anwersayeed** [comment]
https://github.com/PalisadoesFoundation/talawa-docs/pull/229 @palisadoes , I have removed the "Second Doc" link

**Comment by palisadoes** [comment]
1. You deleted the template in #229 which prevented the issue from automatically being closed.
2. The templates are there to help with automation and other key workflow activities. 
3. Please follow the procedure in CONTRIBUTING.md
