### ISSUE TITLE
Installation using npm is missing

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-docs#226]
In the `README.md` 
* installation using `npm` is missing.
*  Running the Developement server using `npm` is missing
![Screenshot from 2022-04-17 12-23-04](https://user-images.githubusercontent.com/57287988/163704225-e99b38db-0d29-4621-ab14-7d6688c127b1.png)

**Comment by anwersayeed** [comment]
@DMills27 @palisadoes I have successfully run the code locally using `npm` and jotted down all the command, should I update that in the `Readme.md`

**Comment by palisadoes** [comment]
We only use yarn. There is no need for another installation method.
