### ISSUE TITLE
Collapsible sidebar feature

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-docs#227]
The sidebar of the talawa-docs documentation website is currently not collapsible, if we have a collapsible sidebar, then it will allow users to better focus on the content.

**Comment by anwersayeed** [comment]
Can you assign this issue to me?

**Comment by anwersayeed** [comment]
https://github.com/PalisadoesFoundation/talawa-docs/pull/228
I have made the pull request, Could you please review the changes? @palisadoes

**Comment by palisadoes** [comment]
Please Read the CONTRIBUTING.md file on methods that can be used to auto-close issues when their PRs are merged.
