### ISSUE TITLE
Create a style guide for Talawa Documentation

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#23]
We need better consistency in the quality of our documentation. [The current style guide](https://github.com/PalisadoesFoundation/talawa-docs/blob/master/docs/style-guide.md) only focuses on the technical details of how to create documents, and not on the general formatting of documentation. This needs to be greatly improved. 

There are many open source projects that have style guides that we could use as a starting point. Here is an example:

- https://flink.apache.org/contributing/docs-style.html

The resulting document needs to be added to the repo and a link for it included in the Talawa documentation introduction

**Comment by MayankVir** [comment]
Hey @palisadoes Can I start working on this issue?
