### ISSUE TITLE
ui: the email looks absurd with other text nearby

### ISSUE THREAD

**Issue by jaiakash** [PalisadoesFoundation/talawa-docs#235]
Image was used for email id. It looked absurd with other text nearby.
So I updated the email as text format.
![image](https://user-images.githubusercontent.com/33419526/174492423-557e1e61-62c9-40c7-9976-3fc870da8594.png)

https://palisadoesfoundation.github.io/talawa-docs/docs/internships/github/github-introduction

**Comment by SiddheshKukade** [comment]
@jaiakash actually this is done to avoid spam from bots. 
bots can only scrape the text on website not images

**Comment by jaiakash** [comment]
Cool, I will make a PR for the same.
