### ISSUE TITLE
Improve the README.md file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#24]
We need better documentation on how to create good documentation for the project.

The README.md file has many issues that need to be rectified:

1. There is no description of the Palisadoes Foundation
2. There is no description of the various Talawa projects
3. There are no detailed explanations of how to configure your system to work with the Docusaurus model
4. There isn't a reference to Contributing.md nor the style guide document
5. There isn't a reference on how to add new pages and integrate your changes into our Docusaurus system

**Comment by Ayaan2907** [comment]
hello, I am a beginner in opensource and would like to take this issue. Please assign it to me and help a little bit to start working.

**Comment by Jd-rathod** [comment]
I want to contribute, can you assign it to me. I will improve the documentation as you have mentioned above.

**Comment by palisadoes** [comment]
> hello, I am a beginner in opensource and would like to take this issue. Please assign it to me and help a little bit to start working.

Assigning to @Ayaan2907

**Comment by Ayaan2907** [comment]
Hello, I just need some clue for the Fourth point, else everything I am trying to polish.

**Comment by palisadoes** [comment]
1. This is related to this issue: https://github.com/PalisadoesFoundation/talawa-docs/issues/25
2. There is no reference to this document: https://github.com/PalisadoesFoundation/talawa-docs/blob/master/docs/style-guide.md
