### ISSUE TITLE
Remove dependency on "docusaurus": "^1.14.7"

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#283]
**Describe the bug**

- We are consistently getting security reports about Talawa docs related to dependencies for Docusaurus `1.14.7`
- This may be a result of us upgrading from `1.14.7` to `2.X` last year

When the `yarn add docusaurus` command is run a reference to Docusaurus `1.14.7`  is created in `package-lock.json`. This reference is not in the Docusaurus GitHub repository's `package-lock.json` file.

**To Reproduce**
- Delete the reference to Docusaurus `1.14.7` in `package-lock.json`
- Delete the `node_modules` directory
- Run `yarn add docusaurus` 

The entry appears.

**Expected behavior**

No entry to `v1.X` should exist

**Actual behavior**

See above

**Screenshots**
N/A

**Additional details**
N/A

**Comment by gkprasanth** [comment]
Hello, @palisadoes  I want to work on this problem, but before I do, could you provide me a detailed explanation of what needs to be done?

**Comment by mmudbe** [comment]
hi @palisadoes , can i solve this issue, please assign to me!

**Comment by palisadoes** [comment]
I am uncertain. That will be up to you to figure out. Do you still want to proceed? This will probably take some time to resolve, and it may not be resolvable. The person working on this issue may have to do a completely new installation of 2.3.0 Docusaurus to recreate the Talawa website and see what differences there are with what we have now. Do you still want to proceed?

**Comment by gkprasanth** [comment]
What are the skills required?what do I need to know I mean

**Comment by palisadoes** [comment]
Knowledge of how to upgrade  javascript dependencies.

**Comment by gkprasanth** [comment]
> Knowledge of how to upgrade  javascript dependencies.

Yup I will try to solve this issue Coz I might get yo learn something. Although I don't have knowledge about Javascript but I will still try.

**Comment by gkprasanth** [comment]
Thank you @palisadoes for giving me the assignment; I'm going to get started on it and seek assistance when required.

**Comment by palisadoes** [comment]
- You should try to do a fresh instatllation of Docusaurus in a separate directory. 
- Add the markdown files from Talawa-Docs
- See how package-lock.json is different from your local installation and Talawa-Docs to see what could be wrong.

There are probably features that will need to be updated.

**Comment by gkprasanth** [comment]
What are markdown files?

**Comment by palisadoes** [comment]
You are going to have to research it.

**Comment by gkprasanth** [comment]
I will.

**Comment by Biki-das** [comment]
@palisadoes i would like to dig into this , since the assignee has no feeback or progress for almost a month, would it be okay if i work on this?

**Comment by gkprasanth** [comment]
> @palisadoes i would like to dig into this , since the assignee has no feeback or progress for almost a month, would it be okay if i work on this?

Dude I am working on it. If you want you do it from your side and submit pr if you complete it. And I will do the same from my side and when I complete it I will submit a PR.

**Comment by palisadoes** [comment]
@gkprasanth It's been over 6 weeks since you were assigned. When will you submit a PR?

**Comment by gkprasanth** [comment]
> @gkprasanth It's been over 6 weeks since you were assigned. When will you submit a PR?

I have submitted a PR just now please review it and let me if there is something that I need to verify again. And sorry for the delay.

**Comment by Cioppolo14** [comment]
I am going to close this PR as we have impending website changes that will address this.
