### ISSUE TITLE
`Admin: Checkins` & `Admin: Volunteer Event Management` idea update

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#285]
Evaluate these GSoC ideas

1. Add potential mentors 
1. Update the expected activities such that they are 350 hour projects. 

Also consider merging the projects with themselves or other 175 hour projects if the 350 hour goal is unattainable.

**Comment by palisadoes** [comment]
@noman2002 this is a tracking issue for you

**Comment by palisadoes** [comment]
The file to edit is `docs/internships/ideas.md`

**Comment by palisadoes** [comment]
@noman2002 Please do the same for [Admin: Multi-Tennancy (Cloud)](https://docs.talawa.io/docs/internships/internship-ideas#admin-multi-tennancy-cloud) 
1. It has `TBD` for a mentor. 
2. I'm also uncertain whether it's 350 hours of work. It may or may not need to be merged with another idea

**Comment by noman2002** [comment]
I'll update it.
