### ISSUE TITLE
Create a dedicated GSoD Ideas page

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#286]
@evasharma12  This is a tracking issue for you. Please comment so that I can assign it to you

**Comment by evasharma12** [comment]
I would like to work on this issue.
Thankyou

**Comment by palisadoes** [comment]
@evasharma12 

1. I just realized that we already had a GSoD ideas page at `docs/internships/gsod/ideas.md`
1. Move any GSoD specific ideas from the GSoC ideas page `docs/internships/ideas.md` to the new GSoD ideas page
1. Make any suitable changes to the GSoD page and let @DMills27 review your PR so that you are both aware of the final status.

**Comment by evasharma12** [comment]
Hey @palisadoes , @DMills27,
I have made the [Pull Request](https://github.com/PalisadoesFoundation/talawa-docs/pull/288) for this issue.
Kindly review it and let me know if any changes are required.
