### ISSUE TITLE
Update GSoC Ideas list - Posts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#291]
The database now supports posts with titles. 
1. This is appropriate for blogging
1. This is not appropriate for a newsfeed.

We need to update the ideas page to include this modification as part of one of the Talawa ideas

**Comment by noman2002** [comment]
Should I remove the post revamp from current idea ? or I just have to add a new idea for blogging ?

**Comment by palisadoes** [comment]
1. Newsfeed posts should not have titles - https://docs.talawa.io/docs/internships/internship-ideas#mobile-app-improved-member-management-and-news-feed
2. Admin should be able to make posts to the newsfeed - https://docs.talawa.io/docs/internships/internship-ideas#mobile-app-ability-to-share-posts--deep-linking

I don't think there is any area where we have blogging functionality in the app that requires a title.

Also, please check the #talawa-admin slack channel. I want to start some walkthroughs with people to get a better Admin design idea.
