### ISSUE TITLE
Creating New Illustrations

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa-docs#3]
I can work on to create new illustrations for different aspects of the Talawa Docs Page to make it more visually appealing :)

**Comment by jordanliu** [comment]
Sounds great, let's see what you have in mind.

**Comment by adithyaakrishna** [comment]
> Sounds great, let's see what you have in mind.

As there are 3 illustrations and in issue #17 , the basic title/info about the 3 tiles are given right, so would the illustrations be designed upon them?

![image](https://user-images.githubusercontent.com/23498248/111696499-60f47600-885a-11eb-8542-916ba5086454.png)
