### ISSUE TITLE
Documenting the new remove member mutation in the scema

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-docs#308]
**Describe the bug**

**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
pls assign this to me

**Comment by palisadoes** [comment]
@kb-0311 Any updates on this?

**Comment by kb-0311** [comment]
@palisadoes yeah, sorry for no update here, got my hands a little full with the encoded content upload thingy. I will submit a PR for the documentation for both this one and new content upload system tomorrow morning( IST).
