### ISSUE TITLE
Bug Report: Typos in the Documentation

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#327]
Going through the current talawa docs i have found quite a number of typos in the documentation and I would like to fix them

**Comment by palisadoes** [comment]
@Biki-das Please define what the issues are. We won't assign an issue if there aren't more specifics. In the absence of a help desk, our documentation is crucial to the success of our projects.

**Comment by aanya963** [comment]
Hey! @palisadoes, while going through talawa docs I came across multiple typos. I would like to work on this issue. Can you assign this issue to me? 
Thank you!

**Comment by Biki-das** [comment]
> Hey! @palisadoes, while going through talawa docs I came across multiple typos. I would like to work on this issue. Can you assign this issue to me? Thank you!

I am working on it, so try to work on other issues

**Comment by palisadoes** [comment]
@Biki-das Please state what the typos are. The wording of the issue excludes anyone else from reviewing the documentation. State what sections you are working on, and then we can have others work on some of the others. This is not in keeping with the spirit of our community.

**Comment by aanya963** [comment]
> @Biki-das Please define what the issues are. We won't assign an issue if there aren't more specifics. In the absence of a help desk, our documentation is crucial to the success of our projects.

Sure @Biki-das, I thought your pull request has been closed. I'm sorry.

**Comment by Biki-das** [comment]
> @Biki-das Please state what the typos are. The wording of the issue excludes anyone else from reviewing the documentation. State what sections you are working on, and then we can have others work on some of the others. This is not in keeping with the spirit of our community.

sure working on it!

**Comment by aanya963** [comment]
@Biki-das you surely be working on the home and about section if you don't mind can I work on the overview section?
Thank you!

**Comment by Biki-das** [comment]
> @Biki-das you surely be working on the home and about section if you don't mind can I work on the overview section? Thank you!

😅 i ran a third party plugin to check for the typos and tried to fix them from all section, already made a PR, but you can look through my PR and i may have missed the other typos and you can fix the same
