### ISSUE TITLE
Adding Algolia search to the docs

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#328]
Since the Talawa doc is using docusaurus for the Documentation, Search is something we should implement to it, as docusaurus supports support for algolia https://docusaurus.io/docs/search, 
This can be very helpful to the project!

**Comment by ayushi-8102** [comment]
kindly assign this issue to me, I would like to work on it.
Thankyou. @palisadoes

**Comment by Biki-das** [comment]
its still not accepted as an issue and i would like to take this , as i am already working on this!

**Comment by ayushi-8102** [comment]
@Biki-das ok no issues !

**Comment by Biki-das** [comment]
> @Biki-das ok no issues !

Meanwhile you can research and find out potential areas of improvement and raise a issue first on the same!

**Comment by Biki-das** [comment]
@palisadoes this would be a very important feature to add to the current documentation and i need your help as you need to give some consent to use the search method available in docusarus, could you fill the below ?

https://docsearch.algolia.com/apply/

**Comment by palisadoes** [comment]
@Biki-das I'm going to close this. Google searches are the way most people will find content. The additional overhead of managing a third party account is not required at this early stage.

**Comment by Biki-das** [comment]
> @Biki-das I'm going to close this. Google searches are the way most people will find content. The additional overhead of managing a third party account is not required at this early stage.

@palisadoes , I would like to discuss a little bit more about adding this Feature, i quite did not understood what you meant by google search and finding the content, The search option method that i am talking about here is it will enable documentation readers to search for a particular bit of information spread over the documentation. For instance let say someone is looking to read for the architecture rather than diving around the sidebar they can just type in search bar and get the relevant information. and as you said about managing the third party account, i don't think it would be a management problem as all we will get is search api key and config which i can write the config and that's it, there is no updates or sort of thing we need to do.
Looking forward to your thoughts!

**Comment by palisadoes** [comment]
Please type this into your browser search bar:

       search:docs.talawa.io API

This is not required. Your solution makes sense for documents stored on a network inaccessible to Google. This is absolutely not required.

**Comment by Biki-das** [comment]
> Please type this into your browser search bar:
> 
> ```
>    search:docs.talawa.io API
> ```
> 
> This is not required. Your solution makes sense for documents stored on a network inaccessible to Google. This is absolutely not required.

Got your point!

**Comment by mariomakter** [comment]
@Biki-das  do you PR

**Comment by Biki-das** [comment]
> @Biki-das do you PR

as suggested by the maintainers this is not something , we are looking forward to add , so i have not made a PR!

**Comment by mariomakter** [comment]
> > @Biki-das do you PR
> 
> as suggested by the maintainers this is not something , we are looking forward to add , so i have not made a PR!

ok
