### ISSUE TITLE
Adding configuration for author and time updated 

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#329]
Docusarus supports a feature to show who updated the docs last time and when , this is a very handy thing to know about as it would help us to maintain the documentation site

![About Us _ Talawa Project Documentation — Mozilla Firefox 3_7_2023 1_28_56 PM](https://user-images.githubusercontent.com/72331432/223361611-4c23baba-691a-4c6b-b940-6f8c0db33a32.png)

this would help us to achieve the above

**Comment by palisadoes** [comment]
Please submit a PR for this. Fill in the template as best you can.

**Comment by aanya963** [comment]
hey, @Biki-das are you still working on this? If no, can I contribute to this issue? please let me know.

**Comment by Biki-das** [comment]
> hey, @Biki-das are you still working on this? If no, can I contribute to this issue? please let me know.

yes @Aanya9693 , i am still working on it, there is some CI CD integration to be done to make this work and i am working on it .

**Comment by palisadoes** [comment]
In hindsight we have to close this PR and the issue. The plan is to have all pages on docs.talawa.io to have the same look and feel. For many pages the author information won't be relevant as they will be autogenerated. Sorry, but we have to close this one.
