### ISSUE TITLE
Adding Brand Assets Pages

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa-docs#33]
**Description:** As we have the new set of logos, we need to have some clear rules defining the usage of them in different situations.
**Solution:** Update documentation regarding the Assets, things need to be accomplished,

- [x] -  Logos - PR #34 
- [x] -  Color Palette
- [ ] - Typography
- [ ] - Patterns & Illustrations

**Are You Willing to Work on This:** Yes :)

**Comment by palisadoes** [comment]
These have been addressed.
