### ISSUE TITLE
Documentation for Running the development server using NPM.

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#330]
Can I add the documentation for the same in `Readme.md`? Could you assign it to me?

**Comment by palisadoes** [comment]
Please proceed

**Comment by Yogita-T** [comment]
Is there any particular schema for naming the branch?

**Comment by palisadoes** [comment]
No, but for each issue you are working on you could use the issue number as your local branch name

**Comment by palisadoes** [comment]
You may want to refer to this pull request.

- https://github.com/PalisadoesFoundation/talawa-docs/pull/334

**Comment by Yogita-T** [comment]
How could I write a sensible commit message?

**Comment by palisadoes** [comment]
Write something that describes what you did.

**Comment by Yogita-T** [comment]
I created a PR, could you please review.
