### ISSUE TITLE
Invalid path for editing pages

### ISSUE THREAD

**Issue by akankshat05** [PalisadoesFoundation/talawa-docs#332]
**Describe the bug**
When we click on "Edit the page", the URL is broken and does not redirect to the correct file.

**To Reproduce**

1. Visit any page on the "About" tab of the documentation
2. Click on "Edit this page"

**Expected behavior**
Every page should have the corresponding correct URL for it's editing.

**Comment by akankshat05** [comment]
I would like to work on this issue :)

**Comment by palisadoes** [comment]
- Please remove the link. We do not have the ability to manage giving people authorization to do this live. 
- For the moment we need to do this through the formal pull request review process

**Comment by iamyelex** [comment]
@akankshat05 do you need with this?

**Comment by iamyelex** [comment]
Do you need help on this? Can we collaborate?

**Comment by Biki-das** [comment]
@akankshat05 are you working on this?

**Comment by akankshat05** [comment]
> @akankshat05 are you working on this?

yes, I have made a PR for it - #360

**Comment by Biki-das** [comment]
> > @akankshat05 are you working on this?
> 
> yes, I have made a PR for it - #360



> > @akankshat05 are you working on this?
> 
> yes, I have made a PR for it - #360

see [comment](https://github.com/PalisadoesFoundation/talawa-docs/pull/360#issuecomment-1460457360)
