### ISSUE TITLE
Feature Request: Adding Cards to the Talawa Project Documentation Homepage

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#339]
**Is your feature request related to a problem? Please describe.**
1. The UI of the Talawa Project Documentation Homepage needs to be improved to increase user engagement.
2. Features heading is missing.

**Describe the solution you'd like**
1. Enclose Group Chats, Event Calendars, and the Powered by React feature in cards.
2. Add a hovering effect to the cards.
3. Add Features heading before the cards.

**Screenshot**
![add cards](https://user-images.githubusercontent.com/78542333/223403951-e52a39e4-c628-4738-883f-ae7dd724f0f4.PNG)

**Comment by ishitakapoor26** [comment]
Please assign this task to me.

**Comment by palisadoes** [comment]
This would be a nice feature, however it would be better to have a much more modern, professional looking home page. 
Can you think of any ways to do that? It would be greatly appreciated.

**Comment by ishitakapoor26** [comment]
> This would be a nice feature, however it would be better to have a much more modern, professional looking home page. Can you think of any ways to do that? It would be greatly appreciated.

Yeah that would be great!
So, I wanted to know if I can create two issues and work on both: 
1. UI/UX design of homepage on figma.
2. Coding that entire homepage.

**Comment by palisadoes** [comment]
- Just make it one issue. 
- I'll close this one
