### ISSUE TITLE
FAQ section missing from docs website

### ISSUE THREAD

**Issue by nangahamandine** [PalisadoesFoundation/talawa-docs#340]
The Frequently asked questions, or FAQs, are a great way to improve the user's experience of the website. It allows to answer the questions that are most commonly asked. This section is missing from the website

**Comment by Sheetal-05** [comment]
Specify the bug:
The website does not contain a FAQs section.

Approach: 
Including a section in the navbar for FAQs, which will include some frequently asked questions and their answers about the website as well as a button to ask a new question about the website.

**Comment by Sheetal-05** [comment]
kindly assign this issue to me, I would like to work on it.
Thankyou.

**Comment by palisadoes** [comment]
@nangahamandine What do you have in mind?

**Comment by nangahamandine** [comment]
> @nangahamandine What do you have in mind?

I'd like to create a section For Frequently Asked Questions, where some questions about the Talawa project will be answered
Possibly a title "FAQ" in the docusaurus.json file under 'Community' which redirects to an FAQ page

**Comment by nangahamandine** [comment]
If approved, please assign me so I can proceed with working on this Feature

**Comment by palisadoes** [comment]
Thanks

- What details would you provide? Where would you get that information from?
- Having a menu without decent content will not be a good experience for the user.

**Comment by nangahamandine** [comment]
I was hoping to start by getting some answers through the documentation, then asking questions from Mentors and other admins like:
- What is the Talawa Project?
- Why should I use Talawa?
- Is Talawa safe?
- Is Talawa free?
- How do I get started with using Talawa?
...

**Comment by nangahamandine** [comment]
> Thanks
> 
>     * What details would you provide? Where would you get that information from?
> 
>     * Having a menu without decent content will not be a good experience for the user.

These are just some of the few questions that I think could be asked. There's much more
Do you think this is a good approach?
I'm open to corrections

**Comment by Sheetal-05** [comment]
Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.

**Comment by nangahamandine** [comment]
> Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.

I agree
I wonder what you meant by "I believe it will be better if I can find them all in one place". Please throw more light
Because if I understand what you're saying. You seemed to have understood that the FAQs will be displayed in different pages which is not the case of what we are trying to visualize. FAQs are often displayed in the same section and that was what I suggested, probably didn't communicate it correctly

**Comment by nangahamandine** [comment]
> Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.

Plus, we could add a feature that suggests similar questions and answers to what the user originally asked

**Comment by Sheetal-05** [comment]
> > Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.
> 
> I agree I wonder what you meant by "I believe it will be better if I can find them all in one place". Please throw more light Because if I understand what you're saying. You seemed to have understood that the FAQs will be displayed in different pages which is not the case of what we are trying to visualize. FAQs are often displayed in the same section and that was what I suggested, probably didn't communicate it correctly

what I meant to say is  that  the website has other sections, such as about, documents, and Api etc. If we create a FAQs section on the home page with general inquiries about practically anything, we won't have to go to the specific page or section to obtain the answers. It'll be beneficial.
if approved, I would like to join you on this.

**Comment by Sheetal-05** [comment]
> > Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.
> 
> Plus, we could add a feature that suggests similar questions and answers to what the user originally asked

Yes, I agree

**Comment by palisadoes** [comment]
Please ask @Cioppolo14 to review your PR when the work is done. There is no need to request approval to do so.

**Comment by nangahamandine** [comment]
> > > Although we can read the answers to the frequently asked questions on the website, as a user, I believe it will be better if I can find them all in one place. Additionally, the collection of questions will be basic and general for the time being by including an option as new question which will allow the user to ask their doubts. We will also add that question to the list of frequently asked questions. This will help improve this section.
> > 
> > 
> > I agree I wonder what you meant by "I believe it will be better if I can find them all in one place". Please throw more light Because if I understand what you're saying. You seemed to have understood that the FAQs will be displayed in different pages which is not the case of what we are trying to visualize. FAQs are often displayed in the same section and that was what I suggested, probably didn't communicate it correctly
> 
> what I meant to say is that the website has other sections, such as about, documents, and Api etc. If we create a FAQs section on the home page with general inquiries about practically anything, we won't have to go to the specific page or section to obtain the answers. It'll be beneficial. if approved, I would like to join you on this.

Oh! Now I get it

**Comment by nangahamandine** [comment]
> Please ask @Cioppolo14 to review your PR when the work is done. There is no need to request approval to do so.

Thank you

**Comment by palisadoes** [comment]
@nangahamandine please work with @ishitakapoor26 on this. She is working on a redesign of the home page and your content would be usefully included there.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/344

**Comment by nangahamandine** [comment]
> @nangahamandine please work with @ishitakapoor26 on this. She is working on a redesign of the home page and your content would be usefully included there.
> 
>     * [Feature Request: Redesign the Talawa Documentation Homepage #344](https://github.com/PalisadoesFoundation/talawa-docs/issues/344)

Okay, will do that

**Comment by salman-farooqi** [comment]
I would like to work on this issue, and continue the work of @nangahamandine as she just mentioned on Slack 'she won't be able to continue from now on'!
I would learn alot from this issue, kindly if you can assign it to me, I would love doing it. Thanks!

**Comment by faveee** [comment]
@salman-farooqi  You beat me to this! Well done!

**Comment by yeahChibyke** [comment]
Can I work on this as well? I have done some personal on already existing products (Breeze, churchtrac, fellowshipone) to understand better what this task entails. I would love to work on this.

**Comment by Biki-das** [comment]
> I would like to work on this issue, and continue the work of @nangahamandine as she just mentioned on Slack 'she won't be able to continue from now on'! I would learn alot from this issue, kindly if you can assign it to me, I would love doing it. Thanks!

Read more about the Talawa app, install it and use it, The faq section should have something that seems like someone could really ask for >

**Comment by yeahChibyke** [comment]
> > I would like to work on this issue, and continue the work of @nangahamandine as she just mentioned on Slack 'she won't be able to continue from now on'! I would learn alot from this issue, kindly if you can assign it to me, I would love doing it. Thanks!
> 
> Read more about the Talawa app, install it and use it, The faq section should have something that seems like someone could really ask for >

OK. I am already on this

**Comment by Biki-das** [comment]
> > > I would like to work on this issue, and continue the work of @nangahamandine as she just mentioned on Slack 'she won't be able to continue from now on'! I would learn alot from this issue, kindly if you can assign it to me, I would love doing it. Thanks!
> > 
> > 
> > Read more about the Talawa app, install it and use it, The faq section should have something that seems like someone could really ask for >
> 
> OK. I am already on this

@gODcodes97 have you been assigned with this task?

**Comment by yeahChibyke** [comment]
Not yet. I am hoping to be assigned this task

**Comment by Cioppolo14** [comment]
@salman-farooqi Please take note of all the discussion about the content above. Thank you for taking this up!

**Comment by salman-farooqi** [comment]
> @salman-farooqi Please take note of all the discussion about the content above. Thank you for taking this up!

I will do my best, and I'll also further propose my ideas, if required.
And if I got stuck and had any questions, I'll ask here. Thanks!

**Comment by Cioppolo14** [comment]
I'm going to close this issue for now, as we're in a transition period with the new website. I apologize for the change.
