### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#341]
**Is your feature request related to a problem? Please describe.**
Docusaurus supports a config for hiding the sidebar while reading the actual content, I would like to add this config , this would help the readers to read the documentation without getting too much of the distraction 

Uploading Core Concepts _ Talawa Project Documentation — Mozilla Firefox 2023-03-07 19-45-28.mp4…

**Comment by palisadoes** [comment]
There is no video of what you are describing

**Comment by Biki-das** [comment]
oops! 😅 closing this one
