### ISSUE TITLE
Adding hideable sidebar config to the website

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#343]
Docusarus has a theme config to hide the sidebar, which would allow it to be hidden, this would make the experience of the readers easy and less distraction 

This is a simple config to be added to the docusaurus config but can add up to a really good documentation experience

https://user-images.githubusercontent.com/72331432/223449285-1bfb6d8a-e260-49be-a8ff-631253d4e9f7.mp4

**Comment by Biki-das** [comment]
@palisadoes this is the one

**Comment by palisadoes** [comment]
What happens when you first click on the about link?

**Comment by Biki-das** [comment]
> What happens when you first click on the about link?


https://user-images.githubusercontent.com/72331432/223452664-d4a5729a-e34d-4c82-ac53-2c538374406a.mp4

currently there is no way to close the sidebar .

**Comment by palisadoes** [comment]
- So as you scroll does the side menu disappear automatically?
- We should have this be an option for the user. They should have control of this part of the experience.

**Comment by Biki-das** [comment]
> * So as you scroll does the side menu disappear automatically?
> 
>     * We should have this be an option for the user. They should have control of this part of the experience.
![Core Concepts _ Talawa Project Documentation — Mozilla Firefox 3_7_2023 8_12_32 PM](https://user-images.githubusercontent.com/72331432/223455818-f41a00bf-56fe-4a80-a4cb-305ca8583f50.png)

yes the user will have the control of the sidebar hide and show, the sidebutton appears on the sidebar itself!
