### ISSUE TITLE
Feature Request: Redesign the Talawa Documentation Homepage

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#344]
**Is your feature request related to a problem? Please describe.**
Enhance the user interface of the Talawa Documentation Homepage to increase user engagement on the website.

**Describe the solution you'd like**
1. Propose a static design on Figma.
2. Code the proposed design.

Please assign this issue to me.

**Comment by palisadoes** [comment]
Please add screenshots for your design options here.

**Comment by iamyelex** [comment]
@ishitakapoor26 can I join you in redesigning the homepage?

**Comment by nangahamandine** [comment]
Hello @ishitakapoor26, I am working on an FAQ section for the talawa-docs website. It's a new feature which will be added to the website
Considering that you will be working on a redesign of the UI to improve the UX of the website, I'd like to suggest that we find a way to add the FAQ section in the Figma design before implementing the final design in the code

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 can I join you in redesigning the homepage?

Thanks for reaching out but I think I won't be requiring any assistance for now. But I'll reach you out for collaboration, in case I need help.

**Comment by ishitakapoor26** [comment]
> Please add screenshots for your design options here.

Sure, I'm on it!

**Comment by Sheetal-05** [comment]
@ishitakapoor26 @nangahamandine @palisadoes 
If that's acceptable, I'd like to collaborate with you on this as well. I have some suggestions for the homepage makeover and the FAQs area.

**Comment by palisadoes** [comment]
@ishitakapoor26 take note of @nangahamandine 's  comment. @nangahamandine will have content that will need to be added. Her input will be required. Please take a look here:

- https://github.com/PalisadoesFoundation/talawa-docs/issues/340

This is important.

**Comment by palisadoes** [comment]
- Collaboration is going to be required.
- @nangahamandine Is there a way for you to add your content now so that it can be integrated into the final homepage design when required?

**Comment by palisadoes** [comment]
The strength of our community rests in collaboration. Please take heed.

**Comment by nangahamandine** [comment]
> * Collaboration is going to be required.
> 
>     * @nangahamandine Is there a way for you to add your content now so that it can be integrated into the final homepage design when required?

Sure, I'm working on it

**Comment by ishitakapoor26** [comment]
@nangahamandine please create a PR. I'll merge the changes with my design code and design as well. Besides this, could you please share your slack ID so that we can get things to work at the design end as well.

**Comment by iamyelex** [comment]
> > @ishitakapoor26 can I join you in redesigning the homepage?
> 
> Thanks for reaching out but I think I won't be requiring any assistance for now. But I'll reach you out for collaboration, in case I need help.

Okay. Thanks

**Comment by nangahamandine** [comment]
> @nangahamandine please create a PR. I'll merge the changes with my design code and design as well. Besides this, could you please share your slack ID so that we can get things to work at the design end as well.

Nangah Amandine

**Comment by nangahamandine** [comment]
Quick question 
Do you think the FAQ section should be added up or down?
![Screenshot (82)_LI](https://user-images.githubusercontent.com/78376414/223486419-81378771-b30b-484d-9a39-13df6dd6465e.jpg)

**Comment by palisadoes** [comment]
Isn't it going to be on the home page? We won't need the links.

**Comment by ishitakapoor26** [comment]
I am thinking to add it in various ways, on the nav bar, footer, as well as a faq section. It will be easy to navigate through. Let me know your views.

**Comment by nangahamandine** [comment]
> I am thinking to add it in various ways, on the nav bar, footer, as well as a faq section. It will be easy to navigate through. Let me know your views.

My thoughts as well
The FAQ section should be displayed when the "FAQ" title is clicked right?

**Comment by nangahamandine** [comment]
Unless @palisadoes  has other thoughts
Would be nice for us all to be on the same page

**Comment by ishitakapoor26** [comment]
@nangahamandine don't add faq links because I'm altering the nav bar, only add a faq section and raise a PR.

**Comment by nangahamandine** [comment]
Hello, I've opened a pull request for the FAQ section in the link below
https://github.com/PalisadoesFoundation/talawa-docs/pull/364
Will be updating the documentation in another branch
@palisadoes please review

**Comment by ishitakapoor26** [comment]
Please review the design.
https://www.figma.com/file/HsIZFQWzMhHZRmsXTctG35/Talawa-Documentation-Homepage?node-id=0%3A1&t=2zAG1BcFry8ydrqD-0

**Comment by ishitakapoor26** [comment]
Below are the screenshots of the website design:

![design1](https://user-images.githubusercontent.com/78542333/223628720-8ce9f63b-6069-47cc-b9a0-5002ec373f55.PNG)

![design2](https://user-images.githubusercontent.com/78542333/223628728-4802bdef-2a00-4123-a9dd-f1a1b392ea9e.PNG)

![design3](https://user-images.githubusercontent.com/78542333/223628729-f044611f-cd43-45aa-85d0-d448dd630c27.PNG)

![design4](https://user-images.githubusercontent.com/78542333/223628733-54756123-ebea-4e32-91ff-01130743949b.PNG)

![design5](https://user-images.githubusercontent.com/78542333/223628755-d79da510-8265-49d9-8ca0-d0262104d6c5.PNG)

![design6](https://user-images.githubusercontent.com/78542333/223628760-d356426e-b84f-4443-8f7e-34d4b3a889de.PNG)

![design7](https://user-images.githubusercontent.com/78542333/223628762-88f5d970-c422-48ec-b1fe-f2a1253a9359.PNG)

**Comment by ishitakapoor26** [comment]
@palisadoes please suggest changes, if any. So that I can proceed with the coding of the page.

**Comment by nangahamandine** [comment]
Awesome work @ishitakapoor26 
Wasn't expecting the FAQ section to look so different

**Comment by ishitakapoor26** [comment]
Check this one as well:

![d1](https://user-images.githubusercontent.com/78542333/223703465-de538425-b9aa-4447-ab0e-59dc3f45d4a1.PNG)

![d2](https://user-images.githubusercontent.com/78542333/223703468-c7a9edbb-0d00-4a34-a6c5-737237310155.PNG)

![d3](https://user-images.githubusercontent.com/78542333/223703471-3f3ce9a4-5c59-487e-99bf-ce78474fca9a.PNG)

![d4](https://user-images.githubusercontent.com/78542333/223703475-02a5734a-a87a-405c-bed1-368012fcd73f.PNG)

![d5](https://user-images.githubusercontent.com/78542333/223703532-62f82133-82d5-4382-b4fb-8952d0a12869.PNG)

![d6](https://user-images.githubusercontent.com/78542333/223703537-9e1423ad-0091-4d59-b156-3851672beaab.PNG)

![d7](https://user-images.githubusercontent.com/78542333/223703540-3ce31228-90c0-45df-b8fc-5d787e7df0e1.PNG)

**Comment by nangahamandine** [comment]
I think the first design gives the look and feel of the Talawa original Homepage better than the second
Also check this documentation for style guides
https://docs.talawa.io/docs/design/ux/ux-talawa

**Comment by nangahamandine** [comment]
Also, in my opinion the FAQ section shouldn't have drop downs but rather displayed in text form

**Comment by iamyelex** [comment]
the design is nice. But the FAQ section should be a drop bar. the answer should only show when a users clicks on it

**Comment by ishitakapoor26** [comment]
> the design is nice. But the FAQ section should be a drop bar. the answer should only show when a users clicks on it

Yes it is the same.

**Comment by ishitakapoor26** [comment]
> Also, in my opinion the FAQ section shouldn't have drop downs but rather displayed in text form

No, it would mess up the page and lead to bad user experience.

**Comment by ishitakapoor26** [comment]
> I think the first design gives the look and feel of the Talawa original Homepage better than the second Also check this documentation for style guides https://docs.talawa.io/docs/design/ux/ux-talawa

The second design is according to the suggested color palette and design guidelines, in the above figma file.

**Comment by ishitakapoor26** [comment]
@palisadoes @Cioppolo14, shall I proceed with the coding part if you agree with the designs?

**Comment by palisadoes** [comment]
The delay is because we’ve both been very busy with this and other repositories.

I want to challenge you some more.

The home page will be catering to administrators who want to manage their teams. So the layouts need to have people not clipart. The focus needs to be on the various features, advantages of using each of these features and how that will benefit the organization, not the IT team.

We need a more modern template, possibly one with screen width images and/or graphics. We are a small group of volunteers, and we need to project ourselves globally with confidence. Therefore we need the look of a Fortune 500 company on the home page. What’s behind the home page can be updated later. 

Take a look at these global and industry specific sites for inspiration. 

1. [ChurchCRM](http://churchcrm.io/)
2. [Infosys](https://www.infosys.com/)
3. [Nokia](https://www.nokia.com/)
4. [Tata](https://www.tata.com/)
5. [SalesForce](https://www.salesforce.com/)
6. [Cisco](https://www.cisco.com/)
7. [Microsoft](https://www.microsoft.com/)
8. [Nestle](https://www.nestle.com/)
9. [Bua Foods](https://www.buafoodsplc.com/)

Take a look at the [Talawa Branding Requirements](https://docs.talawa.io/docs/design/branding) We need to make sure the design incorporates subtle elements of the Talawa color scheme.

It needs to be world class. Surprise us!

**Comment by ishitakapoor26** [comment]
> The delay is because we’ve both been very busy with this and other repositories.
> 
> I want to challenge you some more.
> 
> The home page will be catering to administrators who want to manage their teams. So the layouts need to have people not clipart. The focus needs to be on the various features, advantages of using each of these features and how that will benefit the organization, not the IT team.
> 
> We need a more modern template, possibly one with screen width images and/or graphics. We are a small group of volunteers, and we need to project ourselves globally with confidence. Therefore we need the look of a Fortune 500 company on the home page. What’s behind the home page can be updated later.
> 
> Take a look at these global and industry specific sites for inspiration.
> 
> 1. [ChurchCRM](http://churchcrm.io/)
> 2. [Infosys](https://www.infosys.com/)
> 3. [Nokia](https://www.nokia.com/)
> 4. [Tata](https://www.tata.com/)
> 5. [SalesForce](https://www.salesforce.com/)
> 6. [Cisco](https://www.cisco.com/)
> 7. [Microsoft](https://www.microsoft.com/)
> 8. [Nestle](https://www.nestle.com/)
> 9. [Bua Foods](https://www.buafoodsplc.com/)
> 
> Take a look at the [Talawa Branding Requirements](https://docs.talawa.io/docs/design/branding) We need to make sure the design incorporates subtle elements of the Talawa color scheme.
> 
> It needs to be world class. Surprise us!

Sure, on it. Thanks for the feedback!

**Comment by palisadoes** [comment]
@ishitakapoor26 How's progress on this? Do you have any shortlist designs?

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 How's progress on this? Do you have any shortlist designs?

Yeah, it's almost done...will be sharing some by eod. 
Apologies for the delay. I am not well, but yes trying my best to finish off the task.

**Comment by ishitakapoor26** [comment]
Please review these designs, @palisadoes, @Cioppolo14 :

![d1](https://user-images.githubusercontent.com/78542333/224486923-a1ffab5d-99ef-4bbd-8db6-a8082db80140.PNG)

----------------------

![d2](https://user-images.githubusercontent.com/78542333/224486925-92026a89-e9cf-4dc0-8c84-34f77ae06485.PNG)

------------------------

![d3](https://user-images.githubusercontent.com/78542333/224486926-145740b6-8fe4-4e5a-9339-41619b6643fc.PNG)

-------------------------

![d4](https://user-images.githubusercontent.com/78542333/224486945-b22a049b-d9c3-4db7-93c8-52023e7b26e7.PNG)

-------------------------

![d5](https://user-images.githubusercontent.com/78542333/224486948-dda47e12-b909-4fc4-bdf3-cb06fa8a5d76.PNG)

-------------------------

![d6](https://user-images.githubusercontent.com/78542333/224486949-9fd95e98-33c9-4ad9-9542-b16af08dc454.PNG)

-------------------------

![d7](https://user-images.githubusercontent.com/78542333/224486950-2ee5c6bd-0cc8-4b2b-8bf5-0782ed261152.PNG)

-------------------------

![d8](https://user-images.githubusercontent.com/78542333/224486952-fafd3faf-9507-4a9a-9248-35ec6f84bcc8.PNG)

-------------------------

![d9](https://user-images.githubusercontent.com/78542333/224486962-71ef8069-4e30-4576-bc15-1f64d65fc9bd.PNG)

Figma File Link:
https://www.figma.com/file/TbkeLl1QSopOvayHeQcWbM/Talawa-Palisadoes?node-id=0%3A1&t=6HYPGHPOR0XUtmRl-0

**Comment by palisadoes** [comment]
Thanks. This is a good start. Let's do one or two iterations of this and try to get the page updated in a week or two. We can reopen this to get even better improvements right afterwards. 

1. Can the menu bar stay static at the top?
1. We won't need the contact us section
1. We'd need a link to Palisadoes in the menu (Or in the footer depending on space)
1. How do you propose to handle the links to the links below? I think links to them should be on a `docs/` docusaurus page 
    1.  https://docs.talawa.io/talawa/index.html
    1. https://docs.talawa.io/talawa-api/schema/index.html 
1. The section with the slider cards could have pictures of people in a community setting. Detailing features of Mobile, Admin and the API
1. We don't need the FAQ section on the home page, we'll have a dedicated page.
1. Yellow lettering and icons on green is hard to see. We should use Talawa's green.
1. Where would the blog posts come from? Can they be retrieved automatically from another site like palisadoes.org?
1. The contact link should go to the contact page for palisadoes.org
1.  I think the features section with the hand should be just below the slider. Features are the most important thing
1.  The cards currently below the slider can be where the hand is now.
    1. One could have the GitHub logo and link to the Palisadoes Foundation organization page on GitHub
    1. The other should probably have a combination of logos for GSoC and Outreachy with blurb about the internship programs.
1. The call to action should link to the Palisadoes donation page
1. What is the best way to source images? Should we have a contest on slack with the winners getting their photos posted on slack? The photos can come later, but comments are welcome.

@Cioppolo14 Does this work for you?

**Comment by ishitakapoor26** [comment]
Sure, we can go with one or more iterations. During the process, I will continue brainstorming the improvements I can certainly suggest to make it look even better.

1. Since it's a design, some features weren't that lively and need to be explained:
a.) Nav Bar will be fixed.
b.) Each section will have hover and transition effects. 

2. As suggested, the Contact Us section will be removed and the navbar contact menu will be navigated to the contact page of palisadoes.org.

3. In the About Us card, I will add Learn More button which will navigate to the Palisadoes website.

4. The links to the mentioned URLs will be added in the following manner:
a.) The Docs option in the navbar is a drop-down menu. When you hover over it, a drop-down menu appears, providing options to navigate to the talawa package and talawa API.
b.) Also, after the header slider, we have two cards namely, Talawa docs and Talawa API to link the URLs.

5. Yes, nice thought. I can even prepare a few suitable mockups for the mobile app to fit the theme and requirements well (as you suggest). Just to clarify, which slider cards are you referring to here? (The header ones or the about us)

6. Okay, will not include.

7. Sure, I will send the changed theme design.

8. For now, I am thinking to retrieve the blogs from palisadoes.org. About automated retrieval will have to look into it. I will try my best to make it automatic.

9. Please refer to the second point.

10. Agree on that, and will do the change.

11. i. Yes, when we place the cursor on the cards, a transparency layer appears on the card with the GitHub logo (linked to the repository) on it.
ii. A good point, must agree. I will add a horizontal row of internship programs with the same hover effect as described in the above point, including a small description of the programs.

12. Yes, it does the same job.

13. Yeah, a contest is a great thought, indeed! Would empower creativity and community engagement.

Add On:

i. I would like to further describe the functionality of the Get Started Here button under Want to Learn More banner.
When you click on the button, a new section appears just after Want to learn more banner, describing every feature through slider cards.
Open to suggestions on this one.

ii. To generate different mockups for different features, I will be needing live application screenshots to design the mockups. So, please provide the reference to the screenshots or app.

**Comment by palisadoes** [comment]
Thanks again.

1. The "learn more" pages related to Talawa should link to a page in the docs site.
1. Point ( 5 ) is for the about us
1.  You may be able to get the blog posts using the palisadoes.org's RSS feed..

**Comment by ishitakapoor26** [comment]
> Thanks again.
> 
> 1. The "learn more" pages related to Talawa should link to a page in the docs site.
> 2. Point ( 5 ) is for the about us
> 3. You may be able to get the blog posts using the palisadoes.org's RSS feed..

Thanks for the clarification :)

**Comment by Cioppolo14** [comment]
The comments make sense to me. I'm going to get started on finding some images for this.

**Comment by palisadoes** [comment]
@ishitakapoor26 Are you ready to submit a initial PR for this? The requirements have been set. Don't wait for contributor supplied photos. Please use open source photos to convey what we want.

**Comment by salman-farooqi** [comment]
> @ishitakapoor26 Are you ready to submit a initial PR for this? The requirements have been set. Don't wait for contributor supplied photos. Please use open source photos to convey what we want.

Normally, one issue is assigned to one person but as this a big issue and can be split https://github.com/PalisadoesFoundation/talawa-docs/issues/390#issuecomment-1463106341. I would love to work on the design ideas, HTML and CSS. Thank you!

**Comment by palisadoes** [comment]
> > @ishitakapoor26 Are you ready to submit a initial PR for this? The requirements have been set. Don't wait for contributor supplied photos. Please use open source photos to convey what we want.
> 
> Normally, one issue is assigned to one person but as this a big issue and can be split [#390 (comment)](https://github.com/PalisadoesFoundation/talawa-docs/issues/390#issuecomment-1463106341). I would love to work on the design ideas, HTML and CSS. Thank you!

It's a one page redesign. It can be handled by a single issue.

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 Are you ready to submit a initial PR for this? The requirements have been set. Don't wait for contributor supplied photos. Please use open source photos to convey what we want.

Yes, I am on it. Will create a PR soon!

**Comment by ishitakapoor26** [comment]
I needed crisp content for the website. Because I have written code for sample content and have to replace it with the actual one. So, it would be great if you can suggest me some resources to collect the required data.
Moreover, I wanted to know if I can create a single PR and keep adding different sections to it to keep track.

**Comment by palisadoes** [comment]
Please source your own free, open source images. We can then challenge people to replace them with our own. One PR will be enough.

**Comment by palisadoes** [comment]
Try to find royalty free images of people working in communities. That will be a good start

**Comment by ishitakapoor26** [comment]
Okay sure. Thanks for clarifying me :)

**Comment by palisadoes** [comment]
@ishitakapoor26 We need a valid submitted PR in 12 hours. It's been two weeks and there are many others in the Talawa-Admin repository with typescript experience who could implement this in a couple days. I will close the issue if there isn't any progress after that deadline.

**Comment by palisadoes** [comment]
@ishitakapoor26 After giving this some more thought. I'm going to close this issue. It should have been completed long ago, and I want to be able to give another person at least one full working day on the weekend to give it a try.

**Comment by aviraldevv** [comment]
@palisadoes Please assign this issue to me.

**Comment by Yogita-T** [comment]
@palisadoes  Can you assign this issue to me?? I would love to work on this.

**Comment by nangahamandine** [comment]
I'd like to work on this

**Comment by nangahamandine** [comment]
I'd like to complete this issue alongside the FAQ section

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 After giving this some more thought. I'm going to close this issue. It should have been completed long ago, and I want to be able to give another person at least one full working day on the weekend to give it a try.

I already mentioned that I was not well and have college to attend as well, so I have to manage my time accordingly. 
About the issue, yes it was opened two weeks ago and there has been a discussion on the designs for one week. Given my schedule, I have taken small steps each day for this issue, since that first week of design discussion.
I contributed to the entire design of the page, initially, still, I'm unassigned.
Besides your decision, I should be mentioned to other assignees because of the contribution I made to the issue.

**Comment by Biki-das** [comment]
@aviraldevv could you update with the progress?

**Comment by aviraldevv** [comment]
@Biki-das I have been working on it lately it shouldn't take much time now.

**Comment by Orhmo** [comment]
@palisadoes @aviraldevv Can I assist. That's if you don't mind.
