### ISSUE TITLE
Footer not well arranged

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-docs#345]
**Describe the bug**
On the footer page on the desktop view, the margin does not align and it does not beautify the footer. Likewise, the footer on the mobile version is too spacious and needs to be worked on. Also, the text seems bigger on mobile and occupies spaces. Also, I can add some text format or style to the texts if that is allowed.

**To Reproduce**
1. To portray the footer more professionally
2. To reduce or remove the too much spacing on the mobile footer version 

**Expected behavior**
The footer is expected to be centered and spaced evenly 

**Actual behavior**
The footer is not centered which makes the margin not equal

**Comment by palisadoes** [comment]
Please upload a screenshot of what you mean

**Comment by iamyelex** [comment]
![desktop](https://user-images.githubusercontent.com/95015039/223458923-af7a8acb-7ace-4dbc-b778-8ec7fce2d29d.PNG)
That is the desktop view of the footer.  It is not centered.  and also could use a little text formatting.

![mobile](https://user-images.githubusercontent.com/95015039/223460111-fffbc357-1ac3-4f05-a451-9a878391e0ac.PNG)
This is the footer on the mobile version. The margin between each list is too spacious and also the copyright text should maintain one line and the font size is too big as well.

**Comment by palisadoes** [comment]
Thanks. This is not necessary.
