### ISSUE TITLE
Slack link under the footer's community section 

### ISSUE THREAD

**Issue by ayushi-8102** [PalisadoesFoundation/talawa-docs#346]
**Describe the bug**
The Slack link in the footer's community section is redirecting us to talawa readme page. 

**Expected behavior**
It should redirect to the slack community page.

**Actual behavior**
When clicked, It is redirecting us to talawa's readme page

**Screenshots**
![image](https://user-images.githubusercontent.com/91957156/223453257-02dcfbf6-e486-451b-b6a9-5ef90cf280b7.png)

**Behaviour**

![image](https://user-images.githubusercontent.com/91957156/223453439-f243fa01-3f2c-40db-a783-47a1c3112ab7.png)

**Expected Result** 
![image](https://user-images.githubusercontent.com/91957156/223453729-8d61bd8e-112a-4ddf-826f-82aab88449c8.png)

**Comment by ayushi-8102** [comment]
I want to work with this issue !

**Comment by palisadoes** [comment]
- The link on the README.md file has the join slack link which is updated every 30 days.
- Does the page you plan to redirect them to allow them to join? We've had difficulties in maintaining links to different pages in the past, so we decided to redirect everything related to slack to the repository homepage.
- The Graphene projects to the same.

**Comment by srishtig2412** [comment]
Hello, I am willing to work on this issue, please assign this to me. 
Thank you

**Comment by palisadoes** [comment]
Closing. The slack link changes every 30 days. That's why it's in the README.md file of https://github.com/PalisadoesFoundation/talawa

Closing
