### ISSUE TITLE
Misleading link

### ISSUE THREAD

**Issue by Wineshuga** [PalisadoesFoundation/talawa-docs#347]
**Describe the bug**
On the homepage, at the footer, the link 'tutorial' doesn't lead to a tutorial page but to the about page. There is no tutorial for this site.

**To Reproduce**

1. Link should be changed to a more descriptive text like 'Get started' or 'About'
2. Heading should be changed from Docs to a more descriptive text like 'introduction'

**Screenshots**
![Screenshot_20230307_153303_Chrome](https://user-images.githubusercontent.com/99335288/223454864-f1108018-4b1a-408c-a067-4deca218ddb9.jpg)

**Comment by Wineshuga** [comment]
I would love to work on this

**Comment by palisadoes** [comment]
Please remove the link and its heading completely. It is not necessary as we have a header with that information already.

**Comment by palisadoes** [comment]
Do you still want to work on this?

**Comment by Wineshuga** [comment]
I want to.

**Comment by Wineshuga** [comment]
Thank you

**Comment by vinayakjaas** [comment]
@Wineshuga do nice work but I also want to work on this issue can you assign to me ,I try to make footer section more attractive and responsive
