### ISSUE TITLE
Edit this page link  [about section]  is not working.

### ISSUE THREAD

**Issue by Sheetal-05** [PalisadoesFoundation/talawa-docs#348]
**Describe the bug**
when you go on about section and click on Edit this page link  it is not working and throws an error as page not found.

![Screenshot (53)](https://user-images.githubusercontent.com/97404550/223457692-6b57b44d-f7bd-4730-8420-bef1da9d9444.png)

![Screenshot (54)](https://user-images.githubusercontent.com/97404550/223457899-bf98e79f-e5c5-48c9-b3d4-0304d1115468.png)

**Comment by palisadoes** [comment]
Closing. Duplicate.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/332
