### ISSUE TITLE
Feature Request : Improving footer 

### ISSUE THREAD

**Issue by ayushi-8102** [PalisadoesFoundation/talawa-docs#349]
**Is your feature request related to a problem? Please describe.**
The footer can be arranged properly and new links can be added to it.
<br>
**Describe the solution you'd like**
Right now we only have slack link under **community section**. We can also add **twitter account** of Palisadoes Foundation, **Blog Link**, **Contact Us** under the community section.
Also instead of having a section named **"more"** we can use terms like **"Development"** and include GitHub link , reference to development team and opportunities under it.

**Screenshot** 
![Screenshot 2023-03-07 202907](https://user-images.githubusercontent.com/91957156/223460233-cd508c36-e719-4703-bb5b-22cef5437fee.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ayushi-8102** [comment]
Please assign this issue to me!

**Comment by palisadoes** [comment]
@ayushi-8102  Please ask @Cioppolo14 to review your pull request when ready.

**Comment by ayushi-8102** [comment]
sure!

**Comment by njorogedaniel** [comment]
@ayushi-8102 hello, are you still working on this?

**Comment by ayushi-8102** [comment]
@njorogedaniel yes I'm!
