### ISSUE TITLE
Feature Request: Customize the footer of all the pages linked to the talawa package page

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#351]
![IMG-20230307-WA0005](https://user-images.githubusercontent.com/78542333/223463370-7e2fd798-55cb-4ccb-b71c-fe5bc63939fb.jpg)

**Is your feature request related to a problem? Please describe.**
The current footer includes no information about the organization and links to about or blog.

**Describe the solution you'd like**
1. Add a customized footer to all the pages linked to the talawa package page.

**Comment by ishitakapoor26** [comment]
Please assign this issue to me.

**Comment by palisadoes** [comment]
Isn't this in conflict with the other HTML issue?

**Comment by ishitakapoor26** [comment]
I suppose not because the existing template includes the simple talawa version footer. Issue raised by me enhances the UI of all the footers attached to the talawa package pages.

**Comment by Cioppolo14** [comment]
@ishitakapoor26  This looks like its being addressed in issue #365.  What do you think?

**Comment by ishitakapoor26** [comment]
@Cioppolo14 no this issue is not being addressed in #365 as the footer mentioned in #365 is of about us and the documentation page while the footer I am referring to appears when you go to the talawa package. The Talawa package footer is displaying only the talawa package version (as you can notice in the above screenshot).

**Comment by ishitakapoor26** [comment]
![Inkedfooter](https://user-images.githubusercontent.com/78542333/223737160-dad2aeaa-b37f-4e69-82d9-db4af5c0eb17.jpg)

This is the footer I am referring to...
I will add palisadoes logo to the left and some links to github, blog, etc. Also modify the position of the version of the Talawa package.

**Comment by suhana832** [comment]
can you assign this task to me ?

**Comment by tasmeomeem** [comment]
can i fix it?

**Comment by steno1** [comment]
Can this issue be assigned to me?

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
