### ISSUE TITLE
Feature Request: Customize scrollbar for the entire Documentation

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#354]
**Is your feature request related to a problem? Please describe.**
The Scrollbar of the documentation is a default one.

**Describe the solution you'd like**
Add a customized scrollbar to the entire Talawa documentation, maintaining the design consistency.

**Comment by ishitakapoor26** [comment]
Please assign this issue to me.

**Comment by palisadoes** [comment]
The default scroll is sufficient. Will not fix.
