### ISSUE TITLE
Workflow Diagram Almost Invisible in Darkmode Bug Report

### ISSUE THREAD

**Issue by robinokwanma** [PalisadoesFoundation/talawa-docs#355]
**Describe the bug**
Under the GSOD 2022 and 2023 section, the workflow diagram is barely visible in darkmode

**To Reproduce**

1. Go to the Talawa documentation
2. Go to the Intership Section on the right side-bar
3. Click on GSOD drop down and select either the 2022 or 2023 option
4. make sure you have changed to darkmode

**Expected behavior**
A different image should be used with a different more visible color to ensure a good UX

**Actual behavior**
The same image is used for both light mode and darkmode and the colors are conflicting

**Screenshots**
![Screenshot (30)](https://user-images.githubusercontent.com/60473453/223475800-643521c5-618b-4ee4-8b4c-4f366b266e98.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by robinokwanma** [comment]
Please assign me to fix this issue.

**Comment by robinokwanma** [comment]
My suggestion is, since it is a static image, let me redesign a new flowchart with a color that'll match both light and dark mode. The link attached to wordpress.com there also doesn't seem necessary.
Can i proceed with this?

**Comment by palisadoes** [comment]
Go ahead. Fix the issue. Submit a PR and ask @Cioppolo14 to review. There is no need for requesting any approvals to do so.

**Comment by robinokwanma** [comment]
Alright. Noted
