### ISSUE TITLE
Adding Cards to the Website

### ISSUE THREAD

**Issue by MonalikaPatnaik** [PalisadoesFoundation/talawa-docs#356]
**Is your feature request related to a problem? Please describe.**

This section could be made look good by adding cards. Also, I have to ask does the cards needs to be made clickable so that they can redirect to the respective pages? If yes, then I love to do so.

![image](https://user-images.githubusercontent.com/99353300/223474101-434914b9-e784-422d-a68b-4325004d6a67.png)

**Describe the solution you'd like**
I would like to add cards to this section and make it clickable so that it gives a dynamic feeling to the user.

**Comment by palisadoes** [comment]
Thanks. A good observation, however the home page is being completely redesigned. Closing.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/344
