### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#357]
**Describe the bug**
On the introduction page, the option to edit the page is irrelevant. It should either be removed or should have a function defined. 

**To Reproduce**

 This option should be removed.

**Expected behavior**
![expected](https://user-images.githubusercontent.com/76475512/223486038-0ffec301-e7fb-450b-bbe5-d87f0293adb5.png)

**Actual behavior**
![BUG](https://user-images.githubusercontent.com/76475512/223486413-3c8138b3-3ff1-4848-bafb-e9119a90d31a.png)

**Screenshots**
![BUG1](https://user-images.githubusercontent.com/76475512/223486639-348fdce9-d1e6-4df5-a1bf-d0fd5eda7d28.png)

**Comment by Yogita-T** [comment]
Please review and assign me this issue.

**Comment by palisadoes** [comment]
1. Duplicate. Will not fix.
1. Please search the issues before creating new ones.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/332
