### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#358]
**Is your feature request related to a problem? Please describe.**
The next and previous buttons on  talawa-docs/docs can be arranged properly.

**Describe the solution you'd like**
Right now, the padding to these two buttons is way too much we can reduce that and make it look way better.

**Screenshot**
![button](https://user-images.githubusercontent.com/76475512/223491255-9697dd29-e4cd-43e8-a077-6c253164b815.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
Could you please review this and assign it to me?

**Comment by Cioppolo14** [comment]
@Yogita-T Thank you for your suggestions.  We're focusing on other aspects of Talawa Docs right now.  Please feel free to propose another issue!  I am going to close this for now.

**Comment by Yogita-T** [comment]
okay, Thankyou.
