### ISSUE TITLE
Feature Request: Improving Header

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-docs#359]
**Is your feature request related to a problem? Please describe.**
In the mobile version of the header, the hamburger and the logo of the site should be  at both edge of the page. 

**Describe the solution you'd like**
I will create a space between the hamburger and the site logo so they can both side at the left and right side of the page respectively. 

![98B65638-FDAB-4379-BD75-B1FD1077D859](https://user-images.githubusercontent.com/95015039/223499440-9e417b4f-201e-444b-9ae9-113964cf3843.png)

That’s a screenshot of the mobile view.

**Comment by Cioppolo14** [comment]
@iamyelex  Thank you for your suggestion! We're looking to focus changes on other aspects of Talawa docs right now. Feel free to propose another issue! I am going to close this for now.
