### ISSUE TITLE
Omitted step in installation procedure in the README file

### ISSUE THREAD

**Issue by faveee** [PalisadoesFoundation/talawa-docs#363]
**Describe the bug**
The README file doesn't indicate how to rain check if npm have been installed in the local device and the steps to take. This could cause delay in the workflow as this minute detail could be overlooked.

**To Reproduce**

1. Go to the repository
2. Paste the following command on your local terminal git clone https://github.com/PalisadoesFoundation/talawa-docs.git
3. run npm install -g npm

**Expected behavior**
npm -g installed successfully

**Actual behavior**
npm: command not found

**Screenshots**
![Screen Shot 2023-03-07 at 20 04 47](https://user-images.githubusercontent.com/104652670/223525828-50e566b4-7207-4381-8f11-fec7854a436d.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by faveee** [comment]
Kindly assign me to fix this issue

**Comment by Cioppolo14** [comment]
@faveee  Thank you! Please ensure you explain how to install npm for linux / mac / windows in each of the appropriate sections of the final documentation.  I will assign this to you.

**Comment by aanya963** [comment]
Hey @faveee! I would like to collaborate with you on this issue. Let me know if I can help anyhow on this issue or in general for collaboration. Thank you!

**Comment by faveee** [comment]
@Cioppolo14 I'll do just that. Thank you!

**Comment by faveee** [comment]
@Aanya9693 That would be great! I'll inform you if i encounter any issue in this regard.
