### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by Sheetal-05** [PalisadoesFoundation/talawa-docs#366]
**Is your feature request related to a problem? Please describe.**
Contact info section is still missing from the website.

**Describe the solution you'd like**
Users can contact you using your contact information. 
On your about page, provide a phone number and perhaps a support or informational email address. By doing this, anyone who needs more information or is having problems with your good or service can get in touch with you right away.
we can add a message us icon too.

I think it will be beneficial to improve user`s experience, open to suggestions.

![Screenshot (55)](https://user-images.githubusercontent.com/97404550/223656886-9bea8988-6052-4aa7-a03c-66821b70df47.png)

**Comment by ishitakapoor26** [comment]
Hi, @Sheetal-05, since I am redesigning the entire homepage, we should collaborate and get this feature to work. If @palisadoes approves this feature request, please raise a PR and I will merge your code with mine.
Hope this is okay with you!

**Comment by Sheetal-05** [comment]
If approved, please assign this issue to me.

**Comment by Cioppolo14** [comment]
@Sheetal-05 Thank you for spotting this! This issue will be resolved soon in a PR related to issue #365, so I am going to close this one.

**Comment by Sheetal-05** [comment]
Okay fine!
