### ISSUE TITLE
Link to view Past Interns not added

### ISSUE THREAD

**Issue by iamatifmoin** [PalisadoesFoundation/talawa-docs#367]
**Describe the bug**
In the "Internships > Palisadoes > Palisadoes Unpaid Internship" section, the link to view the past interns has not been added.

**To Reproduce**

1. Go to Internships
2. Go to Palisadoes
3. Go to Palisadoes Unpaid Internship

**Expected behavior**
The text "Take a look at our past interns" should be a link to [this page](https://www.palisadoes.org/internship-alumni/)

**Actual behavior**
No link has been added and "Take a look at our past interns" is a text.

**Screenshots**

![before](https://user-images.githubusercontent.com/97212195/223669498-0a5c5fae-489b-41ff-941b-b00036395832.png)

**Comment by palisadoes** [comment]
This information is specific to the Palisadoes Foundation and is already on its website. Will not fix.

**Comment by iamatifmoin** [comment]
@palisadoes 
So should I remove the "(Add Link)" text?

**Comment by palisadoes** [comment]
It's already been updated.
