### ISSUE TITLE
Unjustified Punctuation 

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#370]
**Describe the bug**
There are minor punctuation errors in [About Us](https://docs.talawa.io/docs/)  on Talawa docs.

**To Reproduce**

Add proper punctuation after `.` in certain sentences. 

**Expected behavior**
There should be a single space after a `.` which isn't there.

**Actual behavior**
Right now, there isn't a space added after `.`'s. 

**Screenshots**

![space](https://user-images.githubusercontent.com/76475512/223679325-29905158-8b37-4946-ba66-58c5aa693f43.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
Can I find all the punctuation and justify them?

**Comment by palisadoes** [comment]
Thanks for noticing this. Please focus on issues that have a meaningful impact.
