### ISSUE TITLE
Feature Request: Optimize Fonts, Fonts positioning and Icons on Homepage and Sidebar for Mobile View

### ISSUE THREAD

**Issue by Princeadxisrael** [PalisadoesFoundation/talawa-docs#371]
**Is your feature request related to a problem? Please describe.**
Enhance the Fonts and Icons on Mobile view homepage and Mobile view sidebar

**Describe the solution you'd like**
Propose optimized Fonts and Icons model for a more gamified experience on the homepage on the mobile view
Code the proposed design

I'd like this issue to be assigned to me.

**Comment by palisadoes** [comment]
Thanks. We are working on a refreshing in another issue. Please focus on issues with a more meaningful impact on the repository and the USSR experience. Closing.
