### ISSUE TITLE
Technology Used Section Missing in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#372]
**Describe the bug**
Technology Used Section Missing in readme.md.

**To Reproduce**

1. Add the Technology used section in the readme.
2. It will include a subsection listing down technology used for talawa app, talawa admin, and talawa docs website.

**Comment by ishitakapoor26** [comment]
Please assign me this issue.

**Comment by Cioppolo14** [comment]
@ishitakapoor26 We would like to keep the readme.md file focused on the technologies related to talawa docs.  Is there anything related to talawa docs you think are missing?

**Comment by ishitakapoor26** [comment]
Surely, then I will add a technology used section in readme, specifically dedicated to Talawa docs and if you suggest I can even add contributors section to the readme.

**Comment by palisadoes** [comment]
This isn't necessary. The technologies used are clearly stated in the current README.md file.

Closing. Thanks for the suggestion. Please think of more.
