### ISSUE TITLE
Missing specifications on exact Nodejs version required for a successful run of the development server

### ISSUE THREAD

**Issue by StrangeJay** [PalisadoesFoundation/talawa-docs#373]
**Describe the bug**

**To Reproduce**

1. npm install -g npm 
2. cd talawa-docs 
3. npm install docusaurus 
4. npm run start 

**Expected behavior**
 A message informing you that the develompent server is has been started and docusaurus is running on http://localhost:3000/

**Actual behavior**
An error message saying the Node.js version is not met, and stating the required minimum version for successfully starting up the development server. 

**Screenshots**
![Screenshot from 2023-03-08 02-43-18](https://user-images.githubusercontent.com/105195327/223688631-fa8414eb-81f5-4496-b5f9-8c0753f9f9b4.png)  

**Additional details**
This is a good first issue for beginners 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by StrangeJay** [comment]
Please I'd like to be assigned this issue, to update the  "Installation" and "Running the development" section of the readme.md 
I want to add exact commands to successfully start up Docusaurus on Linux and windows, with pictoral depiction of step by step processes for a successful run, and also links to informative pages for fixes to possible system based errors that might occur.

**Comment by Cioppolo14** [comment]
@palisadoes What do you think about this? It looks like #376 may be addressing this.

**Comment by palisadoes** [comment]
Yes. It's being addressed there. Closing
