### ISSUE TITLE
Feature Request: Include and Optimize Icons for Sidebar on Mobile view

### ISSUE THREAD

**Issue by Princeadxisrael** [PalisadoesFoundation/talawa-docs#374]
**Is your feature request related to a problem? Please describe.**
Enhance the Sidebar on Mobile view by including Icons 

**Describe the solution you'd like**
Propose Icons for Sidebar to optimize mobile view
code the proposed design

**Comment by palisadoes** [comment]
Please give an example by pasting a screen shot in a comment.

**Comment by Princeadxisrael** [comment]
Do you mean I should implement the design i have in mind and send a sample screenshot?

**Comment by palisadoes** [comment]
Not necessarily. Find an example on the internet, use a drawing package.
