### ISSUE TITLE
Footer copyright information

### ISSUE THREAD

**Issue by njorogedaniel** [PalisadoesFoundation/talawa-docs#375]
**Is your feature request related to a problem? Please describe.**
The current footer information does not relate in any way to Talawa

**Describe the solution you'd like**
Change the footer text to Talawa-related info.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by techfussion** [comment]
I would like to work on this

**Comment by palisadoes** [comment]
This is not required at the moment. The header showed the relationship with Talawa
