### ISSUE TITLE
Feature Request: Contact section missing in the Talawa documentation Homepage

### ISSUE THREAD

**Issue by ishitakapoor26** [PalisadoesFoundation/talawa-docs#377]
**Is your feature request related to a problem? Please describe.**
There is no contact section on the Talawa section homepage to provide user help and support.

**Describe the solution you'd like**
Add a contact section to the Talawa Documentation Homepage.

**Comment by ishitakapoor26** [comment]
Please assign this issue to me.

**Comment by Sheetal-05** [comment]
I have also raised the same issue but would like to inform you that This issue will be resolved soon in a PR related to issue https://github.com/PalisadoesFoundation/talawa-docs/pull/365,

**Comment by ishitakapoor26** [comment]
> I have also raised the same issue but would like to inform you that This issue will be resolved soon in a PR related to issue #365,

Oh, thanks for clearing it out!
I am closing the issue, in that case!
