### ISSUE TITLE
Google Translator 

### ISSUE THREAD

**Issue by Sheetal-05** [PalisadoesFoundation/talawa-docs#378]
**Is your feature request related to a problem? Please describe.**
We can make our website multilingual by including Google Translate.

**Describe the solution you'd like**
To the website's home page, we can add a Google translator button.

But I'm not positive if it's needed or not, to be sincere.
kindly share your thoughts.

![1493297085-google-translate-2png](https://user-images.githubusercontent.com/97404550/223757375-bfbed553-ddde-4fbc-bf10-2b19a13dad03.png)

**Comment by palisadoes** [comment]
This is a good idea, however nowadays you can translate most pages from your browser by going to translate.google.com and entering the URL of the website. I don't think this is necessary.

Please keep the ideas coming!
