### ISSUE TITLE
Bug:-Edit this Page option redirects to the wrong link

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#379]
Currently the `Edit this Page` option which would help to redirect to make some changes is broken!

https://user-images.githubusercontent.com/72331432/223758527-d813998f-bd48-4dc3-ab24-58a5bcb718ac.mp4

We need to make the edit url link dynamic to each page so that it takes to the redirect link corresponding to the page!

**Comment by palisadoes** [comment]
Duplicate issue. Closing

- https://github.com/PalisadoesFoundation/talawa-docs/issues/332
