### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Promisemagoga** [PalisadoesFoundation/talawa-docs#380]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I am working on improving the UX/UI on the talawa documentation website. When switched to dark mode the that green background color looks offish/ out of place

**Describe the solution you'd like**
How about where the green background colour is situated we substitude it with white background colour to complement the dark mode and change  heading 1 to that green colour and leave heading 2 to be black, then change the background colour of the "Get Started" button to that green with white text. This is to make the website looks more interesting and still keep the theme of the app

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![talawa](https://user-images.githubusercontent.com/104593732/223764049-5eed7218-7df9-4fad-86fa-7475ed2e57be.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Promisemagoga** [comment]
please assign this issue to me

**Comment by ishitakapoor26** [comment]
Hey @Promisemagoga! I'm already working on this one. You can check in the issue list.
Good luck!

**Comment by Promisemagoga** [comment]
@ishitakapoor26 sorry didn't see it, can you mention me on it, I want to see something?

**Comment by Promisemagoga** [comment]
@ishitakapoor26  oh just saw it, you are working on the whole home page? because I was looking at the dark mode side of it only. but if that's the case, no problem will look for another issue

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 oh just saw it, you are working on the whole home page? because I was looking at the dark mode side of it only. but if that's the case, no problem will look for another issue

yes, whole homepage.

**Comment by Promisemagoga** [comment]
@ishitakapoor26  ohk no problem and again sorry.
