### ISSUE TITLE
Feature Request:- i18n support for the current website

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#381]
Docusaurus Natively has support for i18n ( internationalization) , this would help us to achieve local translations for the documentation and the result could help a lot of people to read the docs in their preferred language from the supported ones!

More details on - https://docusaurus.io/docs/i18n/introduction

this would take me to write  a i18n.js config and add the supported languages 
![i18n js - jest - Visual Studio Code 3_8_2023 9_42_15 PM](https://user-images.githubusercontent.com/72331432/223767502-c8904439-8356-4e04-a7ba-3e6e0b590540.png)

**Comment by palisadoes** [comment]
@Biki-das We don't have the resources to translate the pages. So though the feature is interesting the long term support won't happen. Websites can now be easily translated by entering a URL into translate.google.com.

Closing
