### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Promisemagoga** [PalisadoesFoundation/talawa-docs#382]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
On the mobile friendly site the headings take up too many lines

**Describe the solution you'd like**
how about the font size be reduced just a little so that it can fit one or two lines
![talawa2](https://user-images.githubusercontent.com/104593732/223769631-b65d5e81-7604-47d7-83c3-70522983ea8b.PNG)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by srishtig2412** [comment]
Hi, I am an outreachy applicant. Is this issue open to work as I am willing to do the same .

**Comment by palisadoes** [comment]
Thanks for creating the issue. It's going to be difficult to get the right font size as every screen is going to be different.
I'm going to close this. However, if you feel that there is justification to keep it open, let me know.

We welcome your input. I'm sure there will be other areas for update.

**Comment by Promisemagoga** [comment]
@palisadoes I believe generally we have 3 screen size, a mobile screen size, a tablet screen size and a computer screen size, so for it to adjust with respect to the  device width we should use em/rem/percentage instead of px when reducing the font size

**Comment by Promisemagoga** [comment]
Oh I forgot to ask for permission intially for this to be assigned to me

**Comment by Promisemagoga** [comment]
@srishtig2412 Sorry, if it gets approved I'll be working on it, am also an outreachy applicant.Good luck on finding an issue

**Comment by palisadoes** [comment]
OK, I'll reopen. Thanks for the clarification.

**Comment by Promisemagoga** [comment]
Thank you

**Comment by aanya963** [comment]
hey @Promisemagoga, I would also like to work on this issue. Let me know if I can help you anyhow. For that, we talk on slack.

**Comment by Promisemagoga** [comment]
@Aanya9693  for now I don't need help,but if I do get stuck I'll definitely hit you up, thank you.

**Comment by Promisemagoga** [comment]
@palisadoes am done but it denies me access to push the changes back. I did test it on different screen size and it responds to the change in  screen size. Check the video below

https://user-images.githubusercontent.com/104593732/224888066-699b215b-b202-4d36-acbe-6b67379eaa7e.mp4

**Comment by palisadoes** [comment]
Is the sizing now too small for a regular web page?

**Comment by palisadoes** [comment]
You will need to open a pull request. Go to your repository and click on the pull request link. There are many tutorials on this process on YouTube

**Comment by Promisemagoga** [comment]
@palisadoes No it is the software I used to take the video,it makes it seem smaller.but if that's the case I can increase it a little more, that's not a problem as the main point here was to make the text responsive regardless the screen size.

**Comment by palisadoes** [comment]
OK, please submit a PR.
