### ISSUE TITLE
Feature Request :- Adding Back the edit URL option

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#385]
@palisadoes https://github.com/PalisadoesFoundation/talawa-docs/pull/360#issuecomment-1460514786, Sorry for the repeated bump.  as we discussed this PR does not solve the issue the `Edit this Page` option was built for the very purpose to easily get a direct link to the  page and as you pointed you dont want to edit the page directly and through the PR, it exactly does the same thing,  if someone finds something to change they can hit the edit and this would fork the repo and create a option to create a PR! see below for how it works!

https://user-images.githubusercontent.com/72331432/223790384-c9767fe8-632e-4806-96fa-72f80a88f468.mp4

**Comment by palisadoes** [comment]
1. This won't work on the Talawa repositories.
2. It works on your repository as you are the owner. 
3. Only GitHub accounts designated as contributors on Talawa repositories can do that.

Closing

**Comment by Biki-das** [comment]
> 

@palisadoes  if someone does not has the fork they will be promoted with this.
this will work on talawa repository, the problem was the edit url config was wrongly written, this is what it should be written for its appropriate behaviour
```
  editUrl: ({docPath}) => {
            return (`https://github.com/PalisadoesFoundation/talawa-docs/edit/develop/docs/${docPath}`)
          }
```
![About Us _ Talawa Project Documentation — Mozilla Firefox 3_8_2023 11_24_00 PM](https://user-images.githubusercontent.com/72331432/223791947-56b0bd89-e5f7-4f94-b666-8b89419a358c.png)
I am not getting your point, this edit this page is to enable easy and quick edit by any one ,if someone already has the fork this would redirect to making a new PR request and if they don't the above prompt would appear!

**Comment by palisadoes** [comment]
I see. Thanks for the explanation. Please submit a PR.

**Comment by Biki-das** [comment]
> I see. Thanks for the explanation. Please submit a PR.

thanks for the feeback! digging on it!

**Comment by palisadoes** [comment]
This is not a  feature we want to enable. It is not suitable for a multi-contributor organization. Please see the comments in the pull request.

**Comment by Biki-das** [comment]
> This is not a feature we want to enable. It is not suitable for a multi-contributor organization. Please see the comments in the pull request.

see comment https://github.com/PalisadoesFoundation/talawa-docs/pull/386#issuecomment-1461221857
