### ISSUE TITLE
Feature Request: Add Custom Scroll bar

### ISSUE THREAD

**Issue by kabugatti** [PalisadoesFoundation/talawa-docs#387]
**Is your feature request related to a problem? Please describe.**
The feature request for a scroll bar is related to a user experience problem. To add more consistency to the website, a custom scroll bar having the website's theme color would improve the user experience significantly.

**Describe the solution you'd like**
I'd like to implement a custom scroll bar for the website, using CSS. With a touch of cool and minimalistic CSS designs, the website will look much cleaner and involving. 

**Additional context**
![Scroll bar](https://res.cloudinary.com/dv765kdgq/image/upload/v1678304591/scrollbar_eyzadp.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kabugatti** [comment]
Kindly assign me to fix this issue

**Comment by palisadoes** [comment]
Thanks for submitting your issue idea. The default scroll is sufficient. We have not accepted this type of issue before.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/354

Don't be discouraged, please look for other issue ideas.
