### ISSUE TITLE
Feature Request: Improve 404 error handler page

### ISSUE THREAD

**Issue by kabugatti** [PalisadoesFoundation/talawa-docs#388]
**Is your feature request related to a problem? Please describe.**
As it stands, the 404 page is generic and doesn't provide many details for the user. It poses a problem with user experience and website maintenance. 

**Describe the solution you'd like**
I'd like to improve the 404-page design and add helpful information in case of a mistyped route. Additionally, a custom 404 error page improves professionalism and credibility.

**Additional context**
![404-Page](https://res.cloudinary.com/dv765kdgq/image/upload/v1678306174/404_lnzpew.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kabugatti** [comment]
Thanks, working on it! 💪

**Comment by vinayakjaas** [comment]
Please Assign This task to me I try My best to solve this problem

**Comment by kabugatti** [comment]
I'm already working on it @vinayakjaas. You can review my pull requests in the near future to possibly contribute to it.

**Comment by Yass32** [comment]
Hello @grand-rick001 can we collaborate on this

**Comment by kabugatti** [comment]
I'd like to know how you'd like to contribute to the issue first @Yass32

**Comment by Ladyperpetua** [comment]
can i get assigned to this please

**Comment by Cioppolo14** [comment]
We have a new website design coming, so I'm going to close this issue and let the new design address it.
