### ISSUE TITLE
Bug Report:- Subsection of the Documentation uses h3 heading instead of h2

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#391]
**Describe the bug**
The current home page of the Talawa docs have mainly four recognizable parts , the header, main section, and then a subsection and a footer.

The subsection heading are using a h3, this results in breaking of the hierarchy of the HTML markup and also violates the accessibility rules
![Talawa Project Documentation _ Talawa Project Documentation — Mozilla Firefox 3_9_2023 9_43_59 AM](https://user-images.githubusercontent.com/72331432/223915520-5ff89159-54f7-4ad9-83cf-eb266c838a31.png)

we have a `h1` on the main section and then we are directly using a `h3` here, replacing it with a h2 tag would be suitable both for accessibility reason and for making the HTML markup organized.

**To Reproduce**

1. Open the home page of the Talawa docs
2. Go the sub section explaining the main features of the project
3. Inspect on the subsection 
4. h3 tag would appear

**Expected behavior**
h3 tags should be replaced by h2 tags
**Actual behavior**
h3 tags are currently being used

**Screenshots**
![Talawa Project Documentation _ Talawa Project Documentation — Mozilla Firefox 3_9_2023 9_50_59 AM](https://user-images.githubusercontent.com/72331432/223916115-63bae9b0-90eb-45c4-96b1-6f93c2eddbd2.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vinayakjaas** [comment]
please Assign this task to me I am Happy to solve this bugs

**Comment by Biki-das** [comment]
> please Assign this task to me I am Happy to solve this bugs

this issue is not yet confirmed and i am looking forward to fix this :-), meanwhile you can look forward to other issue or find potential issues that can be solved!

**Comment by vinayakjaas** [comment]
I Solve This Issue I send  Pull Request Please Review
[https://github.com/PalisadoesFoundation/talawa-docs/pull/392](url)

**Comment by Biki-das** [comment]
> I Solve This Issue I send Pull Request Please Review [https://github.com/PalisadoesFoundation/talawa-docs/pull/392](url)

@vinayakjaas do not send PR request until and unless you are assigned a particular issue!

**Comment by vinayakjaas** [comment]
I closed PR So You start working on sorry for inconvenience

**Comment by ishitakapoor26** [comment]
Hey @Biki-das, the entire homepage is being redesigned, so I don't think it is quite necessary right now.
Good Luck!

**Comment by Biki-das** [comment]
> Hey @Biki-das, the entire homepage is being redesigned, so I don't think it is quite necessary right now. Good Luck!

that does not make any difference its not a huge breaking change and even if the design changes, the same structure will be followed!
Also we should not be barred of making changes, the whole page will be redesigned collectively by everyone so eventually these kind of PR is what would result in the redesign of the page!

**Comment by palisadoes** [comment]
@Biki-das The plan is for a radical redesign of the home page. This issue should be closed.

We have been accepting changes to it for newcomers so that they can gain confidence in the process.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/344

**Comment by Biki-das** [comment]
> @Biki-das The plan is for a radical redesign of the home page. This issue should be closed.
> 
> We have been accepting changes to it for newcomers so that they can gain confidence in the process.
> 
> - https://github.com/PalisadoesFoundation/talawa-docs/issues/344
Cool! Agree to your thoughts!
