### ISSUE TITLE
Misleading Link

### ISSUE THREAD

**Issue by njorogedaniel** [PalisadoesFoundation/talawa-docs#394]
**Is your feature request related to a problem? Please describe.**
This link in the footer section under Development>Team links to members on talawa-docs.
I think it should link to the team that develops/maintains the talawa-docs repository(https://github.com/orgs/PalisadoesFoundation/people)

**Describe the solution you'd like**
I would like to work on fixing this if approved

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by njorogedaniel** [comment]
@palisadoes I solved this issue in my latest commit. Kindly review the changes made

**Comment by Cioppolo14** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by njorogedaniel** [comment]
Hello, kindly reassign me.

**Comment by Ladyperpetua** [comment]
can i be assigned this issue @Cioppolo14 if its still up for assignment

**Comment by tasmeomeem** [comment]
can i fix it?

**Comment by njorogedaniel** [comment]
Hello, @Cioppolo14, I would like to be reassigned to this issue.

**Comment by palisadoes** [comment]
We link to the team that manages the code base. Closing
