### ISSUE TITLE
Updating the About Us Page 

### ISSUE THREAD

**Issue by Himanshiii-14** [PalisadoesFoundation/talawa-docs#395]
@palisadoes
1. Currently, when we browse the about us, the headings section, which appears on the left side, and which appears at the bottom, needs to be clarified.  
2. Also, the way of describing content on the right side can be improved
3. The content of each article can be more detailed to make it more informative
4. The page can be made more creative 
![img1](https://user-images.githubusercontent.com/84770085/223933991-aa03f29b-c84b-4c89-8e8e-884467b179df.png)
![img2](https://user-images.githubusercontent.com/84770085/223934001-d4b23a3f-106a-43a4-8cc0-71a20d0439ae.jpg)

**Comment by Himanshiii-14** [comment]
@palisadoes I want to work on this

**Comment by ishitakapoor26** [comment]
Hey @Himanshiii-14, I wanted to know your approach how will you make the right sidebar more informative? And in my opinion, right and left headings section are just fine.
Enlighten me on this!

**Comment by Himanshiii-14** [comment]
Hello @ishitakapoor26 
I suggest reducing the padding for the right sidebar and representing it in bullet points format by inserting symbols like arrows or using some table to describe it. Also, I mentioned making the content of articles more informative, not the sidebars. And at the bottom part, we can mention the main section and sub-section instead of just the sub-section.
I am thinking of adding some more features to this page. Do let me know if you have some ideas to make it visually more appealing :)

**Comment by palisadoes** [comment]
@Himanshiii-14 please make your issues focus on one item at a time.

1. The right side bar is OK. No need for an issue there.
2. Most people won't be navigating with the footer, and if they do the menu tree will be sufficient. Please don't open an issue for this.
3. This leaves the content. Yes, it could be updated. What information would you like to see?

**Comment by Yass32** [comment]
Hey @Himanshiii-14 can we collaborate on this

**Comment by Himanshiii-14** [comment]
@palisadoes 
Understood, the content of applications can be updated, it would be better to describe all the components in more detail. More content can be added in the developer resources/Talawa/ Overview.
