### ISSUE TITLE
adding outreachy internship under the internships section

### ISSUE THREAD

**Issue by mankaache** [PalisadoesFoundation/talawa-docs#396]
**Updating the internship section.**

![Screenshot (129)](https://user-images.githubusercontent.com/102906019/223935017-87486d9d-1d11-4667-a4bb-1fca83988d4c.png)

**Adding outreachy internship as one of the internships under this section**

**Comment by mankaache** [comment]
If confirmed I would like to work on this

**Comment by palisadoes** [comment]
That's a good point. What content would you put there?

**Comment by mankaache** [comment]
@palisadoes Firstly I would introduce what outreachy internship is all about and include a link to the outreachy website. 
secondly, I would point out the eligibility criteria for applying to outreachy.
Furthermore, I would introduce Palisadoes Foundation and talawa, also outlining the different tawala projects that will be on outreachy, writing little briefs about the projects.

**Comment by palisadoes** [comment]
Thanks.

1. Please use links to the outreachy site as much as possible to reduce the need for text that could go out of date quickly.
2. We won't need new information about Palisadoes and Talawa, however you can encourage people to look at other sections of the site. The links may change so be careful how you word this.
3. We find ourselves repeating the same information on slack about how to get started. It would be very valuable to add and expand on that information

**Comment by mankaache** [comment]
okay noted. Thank you

**Comment by Yass32** [comment]
Hey @babygirl2000  can we collaborate on this

**Comment by palisadoes** [comment]
Please change the title so that everyone has a better understanding of what the issue is. We currently have 5 issues titled `Feature Request`

**Comment by palisadoes** [comment]
An explanation of the purpose of files in order of importance would be very helpful too:
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DOCUMENTATION.md
- INSTALLATION.md
- ISSUE_GUIDELINES.md
- PR_GUIDELINES.md
- README.md 

Other things:

- This may require a second page, like "getting started with our repositories". You'll need to figure out how that could be integrated with a FAQ page issue that is currently open. A link would be better than putting all the content there.
- You'll need to propose a menu tree location for this new page

**Comment by mankaache** [comment]
> Please change the title so that everyone has a better understanding of what the issue is. We currently have 5 issues titled `Feature Request`

okay,

**Comment by mankaache** [comment]
> Please change the title so that everyone has a better understanding of what the issue is. We currently have 5 issues titled `Feature Request`

okay,

**Comment by mankaache** [comment]
> An explanation of the purpose of files in order of importance would be very helpful too:
> 
> * CODE_OF_CONDUCT.md
> * CONTRIBUTING.md
> * DOCUMENTATION.md
> * INSTALLATION.md
> * ISSUE_GUIDELINES.md
> * PR_GUIDELINES.md
> * README.md
> 
> Other things:
> 
> * This may require a second page, like "getting started with our repositories". You'll need to figure out how that could be integrated with a FAQ page issue that is currently open. A link would be better than putting all the content there.
> * You'll need to propose a menu tree location for this new page

okay so I could include a link that leads to the FAQ page right? 
Also, please could you please explain a little how to go about proposing a menu tree location?

**Comment by palisadoes** [comment]
Please use your initiative on both questions.

**Comment by mankaache** [comment]
> Please use your initiative on both questions.

okay got it. Thank you :)

**Comment by Yass32** [comment]
Hey @babygirl2000 can we collaborate on this

**Comment by mankaache** [comment]
> Hey @babygirl2000 can we collaborate on this

hello @Yass32 thank you for your suggestion but i feel like i can do this. But if i need help along the way i will surely get to you.

**Comment by palisadoes** [comment]
> Hey @babygirl2000 can we collaborate on this

Only one issue per person as outlined in our CONTRIBUTING.md file.  If the currently assigned person, or a mentor feels that it is a big enough issue to be split, then that could be done. This is very important if you are planning on applying for an internship. With shared issues, it is difficult to know the level of contribution of each person.
