### ISSUE TITLE
Bug Report Styling in footer section 

### ISSUE THREAD

**Issue by vinayakjaas** [PalisadoesFoundation/talawa-docs#398]
**style part of the footer section mismatched with other part of website. So not look very attractive I try do some styling on footer part . please assign this task to me.**
![2023-03-09 (7)](https://user-images.githubusercontent.com/96948435/223938250-e4063fcd-5db2-4114-bd3f-119b1ddf5fd8.png)

**Comment by ishitakapoor26** [comment]
Hey! please refer #344, this issue is being resolved there.
Good Luck!

**Comment by palisadoes** [comment]
@vinayakjaas Are you referring to the footer not having text centered in each column in the footer?

**Comment by vinayakjaas** [comment]
I referring both footer design as well as Text Which are present at centre

**Comment by palisadoes** [comment]
@vinayakjaas I'll assign this to you as a newcomer so that you can gain confidence. However we will be significantly changing the home page soon.

**Comment by Yass32** [comment]
Hello @vinayakjaas can we collaborate on this

**Comment by tasmeomeem** [comment]
please assign to me ..

**Comment by Cioppolo14** [comment]
I am going to close this issue as we have impending changes to the website that will alter the footer.
