### ISSUE TITLE
Improving the responsiveness of the navigation bar

### ISSUE THREAD

**Issue by mankaache** [PalisadoesFoundation/talawa-docs#399]
**The hamburger menu for the responsive design appears at a larger screen width 995px which is almost 1000px close to some desktop screen sizes plus it doesn't give it a great look and feel due to all the space at this screen size**

![Screenshot (130)](https://user-images.githubusercontent.com/102906019/223941397-577e8c20-81c5-4c1b-9e77-6a33de34c929.jpg)

**I suggest that a smaller screen size should be used, preferably  600px which will cover all possible devices with small screen sizes**

**Comment by SalilHarit** [comment]
I would like to be assigned this issue

**Comment by mankaache** [comment]
i would also like to work on this issue as i have already started working on it.

**Comment by mankaache** [comment]
@lonereaper the issue is still to be approved

**Comment by SalilHarit** [comment]
Apologies I am quite new to this so does this mean it has to be approved before being assigned to someone ? And if anyone can start working on an issue without being assigned?

**Comment by mankaache** [comment]
@lonereaper  the issue has to be assigned to you so you can open a pull request and solve the issue.

**Comment by SalilHarit** [comment]
Thanks

**Comment by mankaache** [comment]
@lonereaper  you're welcome :)

**Comment by Cioppolo14** [comment]
Thank you for your suggestion! However, this is not needed right now, so I am going to close it.
