### ISSUE TITLE
Integrate Algolia Search for the Docs

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa-docs#4]
**Description:** Algolia was used in the Docusaurus itself, and this can be implemented with the Talawa Docs as Algolia is free for Open Source Projects
https://www.algolia.com/for-open-source/

**Comment by jordanliu** [comment]
Hey, good idea but let's put this as a low priority for now.

**Comment by SiddheshKukade** [comment]
@jordanliu Sir, any updates? should we implement this now?
