### ISSUE TITLE
Bug Report: Link opens wrong page

### ISSUE THREAD

**Issue by Yass32** [PalisadoesFoundation/talawa-docs#401]
**Describe the bug**
The slack link in the footer takes you to the wrong page

**Expected behavior**
Open the link to the slack community

**Actual behavior**
Opens a link to talawa GitHub

**Screenshots**
![Screenshot (26)](https://user-images.githubusercontent.com/108995581/223975497-511e844b-4ea7-456c-b65b-7432bc08af28.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yass32** [comment]
Id like to fix the link

**Comment by palisadoes** [comment]
- It is the correct link. Slack links change every month, so we have chosen a single place to update it for consistency.
- Thanks for noticing this. Keep looking!
