### ISSUE TITLE
Bug Report:-  Nav option of about to be replaced with docs

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#402]
**Describe the bug**

The current Navbar of the Home page by default opens with a About option which is inappropriate in My Opinion rather we should call this as **Docs** which represent the whole documentation. We should change the label from "About" to "Docs"

**To Reproduce**

1. Navigate to the Talawa doc Homepage
2. Check the NavBar
3. There it says "About"

**Expected behavior**

https://user-images.githubusercontent.com/72331432/223986903-d570d258-256b-4f09-87df-aa718d748288.mp4

**Actual behavior**

https://user-images.githubusercontent.com/72331432/223987140-ec6d5a97-4020-4fdf-8982-c3027d199991.mp4

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Biki-das Thanks for the suggestion! Since it takes the use to the About Us page, we'd like to leave it as it is. I am going to close this issue.

**Comment by Biki-das** [comment]
> @Biki-das Thanks for the suggestion! Since it takes the use to the About Us page, we'd like to leave it as it is. I am going to close this issue. 

I don't think this is a good UX, almost every other doc site using Docusaurus use the same pattern and if this is the norm we should go the same direction too!
