### ISSUE TITLE
Feature Request:- Replacing plain github label with the Github icon in the navBar

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#403]
A clear and concise description of what the problem is.
Currently at the top Nav, the github link is just a plain label replacing it with the proper github icon seems an appropriate way.

**Describe the solution you'd like**
Adding a className to the item field in docusaurus config would solve this. we can use a background image externally and then use the icon.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

https://user-images.githubusercontent.com/72331432/224008882-01289675-5fed-4b08-ab94-2c3dc91a8e68.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Biki-das Would you like to be assigned this issue?

**Comment by Biki-das** [comment]
> @Biki-das Would you like to be assigned this issue? 

Yes

**Comment by Princeadxisrael** [comment]
Hi Biki-das, I am finding it difficult to locate the navbar section in the codebase? Can you point me in the right direction?

**Comment by Biki-das** [comment]
> Hi Biki-das, I am finding it difficult to locate the navbar section in the codebase? Can you point me in the right direction?

yeah sure @Princeadxisrael head to the `docusaurus.config.js` which is on the root directory, if you are on vscode or other editor press <kbd>ctrl+F</kbd> and search `navbar` .

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Biki-das** [comment]
@palisadoes yes i would like to be assigned!
