### ISSUE TITLE
Feature Request for slack link

### ISSUE THREAD

**Issue by Haywayaheadshot** [PalisadoesFoundation/talawa-docs#408]
**Is your feature request related to a problem? Please describe.**
If the user wants to join slack, it takes them to a GitHub page before asking them to click the slack link. It makes for a bad user experience.

**Describe the solution you'd like**
The link for slack should lead to an invite page for the Talawa slack group

**Describe alternatives you've considered**
I would like to enable the user redirected to the Talawa slack group invite page.

https://user-images.githubusercontent.com/105272189/224090260-9d2531f9-07ea-4407-a4b4-287c74304525.mp4

**Additional context**

**Comment by Haywayaheadshot** [comment]
@Cioppolo14 I would like to be assigned to this issue please

**Comment by palisadoes** [comment]
Thanks, but we will not fix this. Please take a look a this link for the reason.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/401

Please also search both closed and open issues to see whether anyone has tried your idea previously

**Comment by Haywayaheadshot** [comment]
@palisadoes Thank you for the clarification
