### ISSUE TITLE
Bug Report:- Main text breaking in mobile devices

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#409]
**Describe the bug**
The current main heading text is broken in mobile devices

**To Reproduce**

1. Go to Talawa Home page
2. Inspect the Page
3. Select mobile device
4. The heading text is Broken

**Expected behavior**
![Talawa Project Documentation _ Talawa Project Documentation — Mozilla Firefox 3_9_2023 10_26_39 PM](https://user-images.githubusercontent.com/72331432/224099601-f0785c6a-384c-4ffb-9214-4b3959514c9a.png)

**Actual behavior**
![Talawa Project Documentation _ Talawa Project Documentation — Mozilla Firefox 3_9_2023 10_23_57 PM](https://user-images.githubusercontent.com/72331432/224099743-b1d34344-e054-4923-8d47-cbc5ea97d42f.png)

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

Please assign this issue to me

**Comment by Haywayaheadshot** [comment]
@palisadoes Can I be assigned to this?

**Comment by Biki-das** [comment]
> @palisadoes Can I be assigned to this?

@Haywayaheadshot  The issue has not been approved yet, Meanwhile you can look forward to other issues! Once approved you can work on this issue!

**Comment by Cioppolo14** [comment]
@Biki-das @Haywayaheadshot It is good to ask if you can be assigned it, even if unapproved or if you made the issue itself.  That helps us keep track of who is will to do it. We try to review the issue, approve it and assign it all at the same time.  We also try to make sure no one has more than 2 issues at a time.

**Comment by Biki-das** [comment]
> @Biki-das @Haywayaheadshot It is good to ask if you can be assigned it, even if unapproved or if you made the issue itself. That helps us keep track of who is will to do it. We try to review the issue, approve it and assign it all at the same time. We also try to make sure no one has more than 2 issues at a time.

thanks for the clarification @Cioppolo14 yeah that way we can ensure every one gets enough opportunity to began contributing and get more understanding about the project.

**Comment by Haywayaheadshot** [comment]
@Cioppolo14 Thank you for the clarification. I figured since @Biki-das had completed a few issues, I could do this. But I'll find another
