### ISSUE TITLE
Inconsistency in the User Interface

### ISSUE THREAD

**Issue by faveee** [PalisadoesFoundation/talawa-docs#411]
**Describe the bug**
A substantial spacing can be identified between the title of each page and its contexts.

**To Reproduce**

1. Open up the Talawa Project Documentation website
2. Navigate to the developer resources section through the side bar
3. Click on the Talawa API section 
4. Open up the pages in this section 

**Expected behavior**
A consistent user interface that is easily understandable and aesthetically pleasing as seen [here](https://docs.talawa.io/docs/)

**Actual behavior**
Inconsistencies as the spacing between the header and title differs in each page
**Screenshots**
![Screen Shot 2023-03-09 at 18 37 02](https://user-images.githubusercontent.com/104652670/224125534-5c134975-a6f8-4ad9-9c17-3c2881b2f399.png)
![Screen Shot 2023-03-09 at 18 36 55](https://user-images.githubusercontent.com/104652670/224125540-598eb272-d1fa-4724-b54e-1f195a332f0d.png)
![Screen Shot 2023-03-09 at 18 39 02](https://user-images.githubusercontent.com/104652670/224125519-a3044f92-92c7-45bf-87c1-d10e4a30abc0.png)

**Additional details**
None

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by faveee** [comment]
@palisadoes I'd like to add introductory notes for these titles. Kindly assign to me.

**Comment by SalilHarit** [comment]
I'd like to be assigned to this
