### ISSUE TITLE
Move mode toggle button outside the dropdown menu for smaller screens

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#413]
**Describe the bug**
Currently, for smaller screens, the mode toggle button is inside the drop-down menu

**To Reproduce**

1. For smaller screens, open the drop-down nav menu
2. The mode toggle button can be found.
3.
4.

**Expected behavior**
Move the mode toggle button outside the dropdown menu for smaller screens. This will make it easily visible and accessible for smaller screens as not always visitors will open the drop-down menu.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![talwa - Copy](https://user-images.githubusercontent.com/62856848/224161728-6bd7a5fe-9d5f-4b0d-b1b7-3103438bd000.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on the issue

**Comment by tinniaru3005** [comment]
@Cioppolo14 this issue is regarding changes in the Homepage. As you mentioned it is undergoing a major change. Can you please confirm if this issue is still relevant and I can work on it?

**Comment by Keegan-20** [comment]
@tinniaru3005  if it is  not yet solved i would like to work on this issue.Please assign it to me

**Comment by Cioppolo14** [comment]
I am going to close this issue as it is no longer relevant with impending changes.
