### ISSUE TITLE
Reduce the height of the drop down menu and make it scrollable

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#414]
**Describe the bug**
The drop-down menu has only 4 elements and occupies the entire page.

**To Reproduce**

1. Switch to a smaller screen view
2. Open the drop-down menu

**Expected behavior**
Reduce the width of the drop-down menu and make it scrollable

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![talwa - Copy](https://user-images.githubusercontent.com/62856848/224165131-68a6c998-883f-4f81-8596-f2f5fdf22125.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on the issue

**Comment by Cioppolo14** [comment]
I'm going to close this since we are making website changes and are not ready to adjust items like this now.
