### ISSUE TITLE
Improve the look of the drop-down menu by adding hover effects to the elements

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#415]
**Describe the bug**
Currently, the elements of the drop-down menu doesn't have a very attractive look

**To Reproduce**

1. Switch to a smaller screen view
2. Open the drop-down menu

**Expected behavior**
improve the look and feel of the drop-down many by adding some hover effects to the elements

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

![talwa - Copy](https://user-images.githubusercontent.com/62856848/224166921-4ce6cd63-e2bd-4c66-a7b9-225877639873.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by palisadoes** [comment]
Thanks, but the links have hover effects already. They turn green.
Closing.
