### ISSUE TITLE
 Feature Request- Add Respective Icons to Footer Section

### ISSUE THREAD

**Issue by robinokwanma** [PalisadoesFoundation/talawa-docs#416]
**Is your feature request related to a problem? Please describe.**
Add respective icons to footer text 

**Describe the solution you'd like**
Add icons using react icons/bootstrap icons or font awesome icons to their respective texts in the footer section.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by robinokwanma** [comment]
Please take a look and assign me to this issue.

**Comment by robinokwanma** [comment]
![Screenshot (36)_LI](https://user-images.githubusercontent.com/60473453/224192871-c15f0f1f-364e-4b2b-b412-c92e14f5572a.jpg)

Here it is.

**Comment by Vic-Orlands** [comment]
Hello @robinokwanma,

I would suggest that you also add a share icon to the Contact Us link to show that the link will take the user to a different page and tab. See icons beside Talawa Api and Talawa at the Header.

![Screenshot from 2023-03-10 02-07-35](https://user-images.githubusercontent.com/53902215/224197143-101aa73b-f6a6-4db8-8f3d-48711d087302.png)

**Comment by robinokwanma** [comment]
> Hello @robinokwanma,
> 
> I would suggest that you also add a share icon to the Contact Us link to show that the link will take the user to a different page and tab. See icons beside Talawa Api and Talawa at the Header.
> 
> ![Screenshot from 2023-03-10 02-07-35](https://user-images.githubusercontent.com/53902215/224197143-101aa73b-f6a6-4db8-8f3d-48711d087302.png)

Thank you, noted
