### ISSUE TITLE
Create an INSTALLATION.md file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#419]
## Situation
1. The `talawa`, `talawa-admin` and `talawa-api` repositories all have a standardized `README.md` file that refers to their respective `INSTALLATION.md` and `CONTRIBUTING.md` files.
1. This is not the case with `talawa-docs` 

## Resolution
We need the following done:

1. Convert the `README.md` file to more closely match those of the other repositories
1. Extract the installation information from the README.md` file and place it in the `INSTALLATION.md` file
     1. Take guidance from existing talawa `INSTALLATION.md` files
     1. `INSTALLATION.md` must have a table of contents
     1. When transferred to the new `INSTALLATION.md`  section, the title `Installation` should be called `Install the Prerequisities` 
     1.  Installation steps are currently in the `Running the Development Server` section should be moved to the respective sections under the respective YARN or NPM pre-requisite installation sections
     1. The current section that says the following should be moved to the appropriate pre-requisite section. Stating the required versions of node will not be sustainable. The section that refers to v16.14 should just state that the person should ensure that they are running the versions currently required by Docusaurus with a link to the relevant docusaurus site.
 
                 Note: Install the latest stable version of Node.js on your system if you 
                 get a The engine "node" is incompatible with this module. Expected version 
                 message during the procedure below. You may need to use a custom repository for this.

                Please bear in mind that to install docusaurus your system, a Node.js version 
                16.14 or above (which can be checked by running node -v) is required. Other 
                requirements that pertains to the installation of docusaurus can be found here

**Comment by Vic-Orlands** [comment]
Hello @palisadoes Can you assign this task to me? I completely understand what is needed to be included in the INSTALLATION.md file and would love to work on it. Thank you.

**Comment by iamatifmoin** [comment]
@palisadoes I'd like to work on this please.

**Comment by Vic-Orlands** [comment]
> @palisadoes I'd like to work on this please.

It has been assigned to me, Mati and I’m working on it too

**Comment by palisadoes** [comment]
> @palisadoes I'd like to work on this please.

If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.
