### ISSUE TITLE
Improve the phrases on the landing page card

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#422]
**Describe the bug**
Currently, the phrases on the landing page are very basic and not very organized

**To Reproduce**

1. Open the landing page of Talawa-docs

**Expected behavior**
Improve the phrases on the landing page

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![224149860-7c786a05-adde-4b44-b1d9-b3506a9de955](https://user-images.githubusercontent.com/62856848/224240092-e44fec53-9ef3-46ad-9d30-9be7d83b8737.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by SalilHarit** [comment]
@palisadoes can I be assigned  to this

**Comment by tinniaru3005** [comment]
> @palisadoes can I be assigned to this

Hey thank you so much for your interest. But I have mentioned that I would like to take up the issue. You can have a look at the other issues. 😊

**Comment by SalilHarit** [comment]
sure !

**Comment by Cioppolo14** [comment]
@tinniaru3005 Thank you for your submission! We have issue #344 that will be changing these items, so I am going to close this issue since that change is coming.  Please, don't be discouraged.  Keep the ideas coming!

**Comment by tinniaru3005** [comment]
Ya sure. Will keep adding my ideas by raising issues. Thanks :)
