### ISSUE TITLE
Design inconsistency of the talawa package page 

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#424]
**Is your feature request related to a problem? Please describe.**
Talawa package page does not have best ui/ux practices and does not fit the rest of the talawa design and has a very basic html structure that looks out of place and it even lacks the Talawa logo 

**Describe the solution you'd like**
we can use modern html css practices to update the whole page's looks to make it look more modern and design consistent
![image_2023-03-10_123741251](https://user-images.githubusercontent.com/39475669/224247324-a68ab67a-b61c-484b-943c-b8851ae15103.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
@palisadoes can I be assigned to this ?

**Comment by palisadoes** [comment]
This page is auto-generated. Whenever there is a new pull request. Please research how this is done and make a suggestion. It's not just changing HTML, it is sourced from another location.

**Comment by palisadoes** [comment]
Closing. Duplicate.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199#issuecomment-1463363072
