### ISSUE TITLE
Talawa overview section update for developer resources 

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#425]
**Is your feature request related to a problem? Please describe.**
the overview of talawa project under developer resource section just provides the brief overview about the Talawa which is filler as this also written in introduction section and does not help the reader to access anything meaning such as the documentation website related contribution 

**Describe the solution you'd like**
updating content of overview section to include links of github repository and rewriting content to better understand the how the developer can contribute to the documentation website and scope of contribution as it has done with admin portal and api section 
![image_2023-03-10_144651462](https://user-images.githubusercontent.com/39475669/224275506-0cbc3a11-f9d1-4961-809a-441a6661ce28.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
@palisadoes I would like to be assigned to this

**Comment by Biki-das** [comment]
duplicate #390
