### ISSUE TITLE
Bug Report: Documentation Typo

### ISSUE THREAD

**Issue by Yass32** [PalisadoesFoundation/talawa-docs#426]
**Describe the bug**
I've noticed some documentation typos on the About Us and Core Functionalities Page

![Screenshot (33)](https://user-images.githubusercontent.com/108995581/224275536-6f009997-38ad-47c9-92e8-8ec040f0c379.png)

![Screenshot (32)](https://user-images.githubusercontent.com/108995581/224275526-5800377e-aac4-404b-a35d-6ced3899c434.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
Can I work on this?

**Comment by Yass32** [comment]
I'm already working on this @Yogita-T :)

**Comment by Yogita-T** [comment]
@Yass32 Okay!

**Comment by Cioppolo14** [comment]
@Yass32 Please contact me for any wording issues if it isn't totally clear from what is on the page. I can help with wording and clarity.  Also, in the future, just comment below your issue that you'd like to work on it, that helps us know if the issue creator just noticed the issue or wants to address it as well.  Thank you!

**Comment by Yass32** [comment]
Okay thank you very much Le 10 mars 2023 à 17:36, Crystian I ***@***.***> a écrit :﻿
@Yass32 Please contact me for any wording issues if it isn't totally clear from what is on the page. I can help with wording and clarity.  Also, in the future, just comment below your issue that you'd like to work on it, that helps us know if the issue creator just noticed the issue or wants to address it as well.  Thank you!

**Comment by Yass32** [comment]
> @Yass32 Please contact me for any wording issues if it isn't totally clear from what is on the page. I can help with wording and clarity. Also, in the future, just comment below your issue that you'd like to work on it, that helps us know if the issue creator just noticed the issue or wants to address it as well. Thank you!

Okay thank you very much

**Comment by Yass32** [comment]
Hi @Cioppolo14 sorry but I'm having trouble finding the HTML file of those pages, can you please help me out?

**Comment by Yass32** [comment]
Hello @Cioppolo14 , i was fixing the typos and I came across a sentence I don't fully understand.

## Switch Between Organizations
### Description
Users can belong to multiple organizations, however they cannot create their own. This is an admin feature. This is the ability for users to create their own organizations needs to be removed.

The users get the ability to create organizations that needs to be removed???

**Comment by Yass32** [comment]
Hello @Cioppolo14 ?

**Comment by Yass32** [comment]
Hello @palisadoes can you please help me out

**Comment by iamatifmoin** [comment]
@Yass32 
I think the sentence should be:
"Users can belong to multiple organizations, however, they cannot create their own. This is an admin feature. Thus the ability for users to create their own organizations needs to be removed."

**Comment by Yass32** [comment]
@iamatifmoin Thanks
