### ISSUE TITLE
Reduce the text size of drop down elements.

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#427]
**Is your feature request related to a problem? Please describe.**
In the https://docs.talawa.io/docs/  the font size of elements of a sub-topic in each topic should be smaller than the font size of topics.

**Describe the solution you'd like**
I would like to make each sub-topic size smaller than the size of the main topic.

![Size](https://user-images.githubusercontent.com/76475512/224284502-09e6f62b-6f6e-4c2e-894d-edc2518cbaa2.jpg)

I have marked the subtopics with blue and the topics with yellow.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
Please review and assign this task to me.

**Comment by Cioppolo14** [comment]
@Yogita-T  Thank you for your submission.  Right now, we'd like to focus on updating content and fixing significant bugs. I am going to close this for now.

**Comment by Yogita-T** [comment]
Okay,Thankyou
