### ISSUE TITLE
Completely Replace links with icons and very brief description of organizations profile

### ISSUE THREAD

**Issue by david-ibemma** [PalisadoesFoundation/talawa-docs#428]
**Is your feature request related to a problem? Please describe.
 websites have icons of social media platforms used as links to the organizations profile.  These icons are are placed below or directly under a  very brief description of the organizations profile in the footer section

**Describe the solution you'd like**
replace the social media links with icons of social media platform
write a brief description of organizations profile. Using CSS the description will be positioned towards the left end of the footer while the social media icons will be placed below the description.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by david-ibemma** [comment]
review and kindly assign issue to me

**Comment by Cioppolo14** [comment]
Hello, thank you for your submission. Issue #416 is addressing this change, so I am going to close this issue.
