### ISSUE TITLE
Improving Home Page Design

### ISSUE THREAD

**Issue by steno1** [PalisadoesFoundation/talawa-docs#430]
**I want to improve the Homepage design, to look for professional and attractive to the users

- I specifically want to work on the homepage Homefeatures to look like the image below

![palisadoesSnap](https://user-images.githubusercontent.com/46807940/224304255-1fa5a4f7-1f8d-4ee4-8698-c0142683c0a8.PNG)

- i will work on the HTML and CSS of the file

**Comment by steno1** [comment]
Good afternoon Mentor. please can this task be assigned to me. I am desperately in need of work to be assigned

**Comment by Cioppolo14** [comment]
@steno1 I am sorry, we have an active issue on this, #344.  Thank you for your submission!  I am closing this since it is already being worked on.
