### ISSUE TITLE
Feature Request: Add a Search bar

### ISSUE THREAD

**Issue by Vic-Orlands** [PalisadoesFoundation/talawa-docs#432]
**Describe the Feature**
If you look at the header of the Talawa documentation website, there is no Search Bar implemented. Good documentation should have a Search Bar at the header. This is so that users who are not patient enough can search for things on the docs using keywords. Users who can't locate areas on the docs can also search for what they are looking for using the Search bar
![Screenshot from 2023-03-10 14-08-22](https://user-images.githubusercontent.com/53902215/224328051-17ce3eae-fee8-43d3-9630-2b99dcb07215.png)

**My solution**
Implement a Search Bar with MelliSearch. The logic is to crawl the website pages and return well-detailed results with links to the pages and sections of the results.
MelliSearch is a fast, open-source, easy-to-use, and deploy search engine. The search and indexation are fully customizable and handle features like typo-tolerance, filters, and synonyms.
![Screenshot from 2023-03-10 14-40-16](https://user-images.githubusercontent.com/53902215/224330648-3c98e30e-b66f-4d70-ac09-2507a971fd26.png)

**Alternatives considered**
ElasticSearch is an alternative solution to the MelliSearch search engine and it is also free. I am choosing to go with MelliSearch because it is an open-source project and further encourages the vision and goals of this internship.

**Additional context**
![Screenshot from 2023-03-10 14-08-37](https://user-images.githubusercontent.com/53902215/224330178-a5404500-b998-4e84-afe5-32bb93f2f02d.png)

**Comment by Vic-Orlands** [comment]
@palisadoes Can you review and assign this task to me? Thank you.

**Comment by Cioppolo14** [comment]
@Vic-Orlands Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by Biki-das** [comment]
@Vic-Orlands #328 , This is not something that is really important to the project right now as stated by the project maintainer.

**Comment by Cioppolo14** [comment]
I am going to close this for now.  For now, we're going to rely on google advanced search. Try using it to search site:docs.talawa.io talawa data retention. Thank you!
