### ISSUE TITLE
Bug Report:- Css imports are not defined at the top of the document

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#433]
**Describe the bug**
The current font imports are defined after a certain point, `@imports` must be called on the top of the stylesheet 
https://developer.mozilla.org/en-US/docs/Web/CSS/@import
**To Reproduce**

1. Navigate to the `custom.css` file
2. Look for the Import URl

**Expected behavior**
The import statements must be defined at the very top of the document

**Actual behavior**
They are being defined below

**Screenshots**
![custom css - talawa-docs - Visual Studio Code 3_10_2023 7_22_54 PM](https://user-images.githubusercontent.com/72331432/224334566-4c463457-f66d-40a2-89b8-2f163c899799.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Biki-das Thank you for your submission.  Right now, we really want to focus on updating the content of Talawa docs. I am going to close this for now.

**Comment by Cioppolo14** [comment]
@Biki-das Thank you for your submission.  Right now, we really want to focus on updating the content of Talawa docs. I am going to close this for now.

**Comment by Biki-das** [comment]
@Cioppolo14 how can i help towards updating the content of docs any pointer you can suggest ?
