### ISSUE TITLE
Link to the instagram page is broken.

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#434]
**Describe the bug**
The link to Instagram in the footer's community section isn't working. 

**To Reproduce**

1. Will update the link to the right page.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Yogita-T  It appears to be working for me.  Can you identifying some reason it may not be working for you? Thank you!
