### ISSUE TITLE
Rearrange items on Footer

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#435]
**Describe the bug**
The left side of the footer looks quite blank on small screens.

**To Reproduce**

1. Go to the landing page
2. Switch to smaller screen view
3. Scroll down and go to the footer

**Expected behavior**
Rearrange the items on the footer so that there is not so much blank space left on the left side of the footer

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Footer](https://user-images.githubusercontent.com/62856848/224358313-bfeb58da-cd67-4f7f-98b8-42bc3770234d.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by SalilHarit** [comment]
we're told that footer changes are on hold for time being

**Comment by Cioppolo14** [comment]
@tinniaru3005 Thank you for the suggestion.  We are pausing footer changes for now, so I will be closing this issue.  Please don't be discouraged. Keep your ideas coming.
