### ISSUE TITLE
Create dropdown on talawa-api side bar

### ISSUE THREAD

**Issue by david-ibemma** [PalisadoesFoundation/talawa-docs#436]
**Is your feature request related to a problem? Please describe.**
side bar on the talawa-api appears confusing hence needs a dropdown created to facilitate easier usage and better understanding

**Describe the solution you'd like**
create a select html tag for each group of options. add option tags in theach select tag to accomodate the links in each group.
use css to style the dropdown and give a better outlook

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@david-ibemma Can you provide a screenshot?

**Comment by singhavs** [comment]
@Cioppolo14  @palisadoes I would like to fix this issue

**Comment by singhavs** [comment]
@Cioppolo14 he means this issue as shown in screenshot
<img width="245" alt="image" src="https://user-images.githubusercontent.com/67657066/225366261-752ef753-ae58-4a59-b9ff-a2fbfd3ad0db.png">
The colour coded words should appear in the drop down of colour coded tick marks.

**Comment by palisadoes** [comment]
Thanks for submitting your request to update the content of https://docs.talawa.io/talawa/index.html and https://docs.talawa.io/talawa-api/schema/index.html The files under these directories are 100% generated automatically by every merged PR in the Talawa, Talawa-API and Talawa-Admin repositories. The automated action parses the source Flutter and Typescript source code for comments on each method, class and function using the DartDoc and TSDoc packages and creates HTML suitable for online documentation from them. With each PR, the files in Talawa-Docs are completely overwritten by these PRs.

We have created special issues to update the look and feel of these automated updates in these issues below. We need to close this issue as it is a duplicate. Thanks, and continue searching for similarly inspiring ideas to make our documentation better.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199
- https://github.com/PalisadoesFoundation/talawa-docs/issues/200

I'll close this issue. Please ask to have it reopened if you think this was done in error.
