### ISSUE TITLE
Anchor next to the section title does not provide any meaningful navigation to the section 

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#437]
**Is your feature request related to a problem? Please describe.**
the '#' navigation feature is not useful from ux perspective as the user can just scroll down and it serves no purpose other than look odd when accidentally hovered over its not intuitive or has usability to ux flow of the page along with the section title on right side of the page which does the same thing 

**Describe the solution you'd like**
remove the '#' section navigation feature as it is not helpful and the user is better off scrolling for this amount of content
![Screenshot (2)](https://user-images.githubusercontent.com/39475669/224382839-f69dbba7-0cf5-42a1-a98e-81063229328a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/39475669/224383029-03aa4ba8-f352-4186-991c-817ff7df2dee.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
@palisadoes can this be assigned to me ?

**Comment by Cioppolo14** [comment]
@lonereaper Thank you for your submission.  We'd like to leave this in as it provides direct links for even the small titles.  I'm going to close this issue, but please keep submitting ideas!
