### ISSUE TITLE
the palisadoes logo on navbar is too small and external link icon does not look appealing on the navbar

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#438]
**Is your feature request related to a problem? Please describe.**
the external icons on navbar list items break the design uniformity along with the size of the organization logo 

**Describe the solution you'd like**
remove external link icon from the navbar completely and give it a cleaner look while increasing the size of logo to improve visibility 

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
@palisadoes can this be assigned to me ?

**Comment by Cioppolo14** [comment]
@lonereaper Thank you for your submission.  We really want to focus on content right now, so I am going to close this as unplanned for now.  Please keep submitting your ideas!
