### ISSUE TITLE
Feature Request:- Adding prettier to automate doc formatting

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#439]
**Is your feature request related to a problem? Please describe.**
Currently there is no doc formatting tool, so we need to manually format the documentation markdown which takes time and is not the best for future documentation updates, Adding the `prettier` tool and adding it to the devlopement tool can help us solve this as it supports markdown and it fast and ensures all of our code will be formatted.

**Describe the solution you'd like**
Adding the prettier package as a dev dependency and then writing a config, and further making it scan only for the documentation thus formatting it correctly if it some changes

**Describe alternatives you've considered**
There are no other alternatives to this problem, prettier is a popular tool used for a lot of project for code formatting so i feel we should also stick to the same .

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

https://user-images.githubusercontent.com/72331432/224388269-9ffe98aa-0db3-44f3-91e0-b593bdd5ee3d.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

Please assign this to me.

**Comment by Cioppolo14** [comment]
@Biki-das Thank you for your suggestion.  We do not want to implement this right now.  We'd like to leave this up to the individual at this time.  I'm going to close as unplanned for now. Please keep the ideas coming.
