### ISSUE TITLE
Feature Request: User Feedback Mechanism Missing from Documentation

### ISSUE THREAD

**Issue by tobidosumu** [PalisadoesFoundation/talawa-docs#443]
**Importance of a User Feedback Mechanism**
Providing a way for users to provide feedback or ask questions can help improve Talawa documentation and provide additional information for other users.

**Proposed Implementation Demo**
![proposedUserFeedbackMechanismForTalawDocs](https://user-images.githubusercontent.com/60399800/224417459-ecc5820c-0a20-4053-a719-414084a5af67.gif)

**Feature Suggestion: Implement User Feedback Mechanism in Footer Section for Improved UX**
May I suggest that the User Feedback Mechanism feature be implemented/situated in the footer section. 
The reason for this suggestion is based on the principle of UX. When a user scrolls down any page
on the Talawa-docs website, on arriving at the footer, they (i.e. the user) will be able to send their
feedback if they have any.

**Request for Task Approval**
Hello @palisadoes. I would like to request your approval for my proposal to include a User Feedback Mechanism in the footer section of the Talawa-docs website. The purpose of this proposal is to improve the user experience by making it easier for users to provide feedback as they navigate the website. Thank you for your consideration.

**Request for Task Assignment**
Hello @palisadoes. I am interested in working on the aforementioned task. I have experience with similar tasks and believe that I could make a valuable contribution to the project. Please let me know if you would be willing to assign this task to me. Thank you for your consideration.

**Comment by Cioppolo14** [comment]
@tobidosumu We really like this idea, but we don't have the volunteer resources to support it right now.  We'd love to consider it when Talawa is ready for users and there are less issues to manage on the Talawa respositories.  Once the project matures a bit more.  I'm going to close this as unplanned for now.  Thank you! Please keep submitting ideas.

**Comment by tobidosumu** [comment]
Thanks @Cioppolo14 for the feedback. I will submit another idea soon. 

But as an applicant who just joined the Talawa-docs community, do I stand a chance of having a task (or one of these ideas) assigned to me?
