### ISSUE TITLE
Feature Request : Style the sidebar on the dashboard.

### ISSUE THREAD

**Issue by Graycemuthui** [PalisadoesFoundation/talawa-docs#444]
**Is your feature request related to a problem? Please describe.**
The sidebar on the dashboard page seems to be quite flat . Therefore my thought is to style it make the content more concise. This will help improve the users experience with the page.

**Describe the solution you'd like**
Well for one all the different features on the container will be more clear and adding a bit of styling will help the dashboard look better of course taking note of the color palette.

**Describe alternatives you've considered**
Using different stylings to separate the content on the sidebar.
Making the description look more appealing.

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Graycemuthui Can you provide screenshots of what you mean?

**Comment by Graycemuthui** [comment]
This is the part I'm talking about. Thinking we could add the name of the organization as well in the about section.

![palisadoes](https://user-images.githubusercontent.com/95374858/224472165-14b05ae7-6247-428c-893d-408068a4efa6.jpg)

**Comment by Cioppolo14** [comment]
@Graycemuthui Can you reopen this in the Talawa-Admin repository?  I am going to close this for Talawa Docs.  Thank you!
