### ISSUE TITLE
Feature Request: Recreate/Update Image, and Replace Architecture Image 

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-docs#447]
**Is your feature request related to a problem? Please describe.**
The image representing the Architecture of Talawa on the Applications page needs to be recreated and modernized. 

**Describe the solution you'd like**
The above mentioned image needs to be recreated with a modern look, but effectively communicate the design. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
When asking to be assigned this issue, provide a sample of what you'd like to do with it. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Biki-das** [comment]
@Cioppolo14 i would like to work on this if possible!

**Comment by Cioppolo14** [comment]
@Biki-das Thank you! You actually have 3 issues right now.  Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Biki-das** [comment]
> @Biki-das Thank you! You actually have 3 issues right now.  Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Yeah sure, let me unassign myself!

**Comment by Yogita-T** [comment]
@Cioppolo14 I would like to work on this can you please assign this to me?

**Comment by Yogita-T** [comment]
Thank you! getting started with it.
