### ISSUE TITLE
Feature Request: Add a Section to About Us Describing Technologies Used

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-docs#448]
**Is your feature request related to a problem? Please describe.**
There is a lot of important, missing data in our About Us page. 

**Describe the solution you'd like**
Add a section in "about us" describing the technologies used in Talawa, and listing the important pages to read for a introduction the technical side of Talawa. This will require some research, our youtube channel will be a helpful resource: https://www.youtube.com/@PalisadoesOrganization/videos. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
See above.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
@Cioppolo14 Can you please assign this issue to me? I would like to work on this issue.

**Comment by Yogita-T** [comment]
Thank you! getting started with it.

**Comment by Yogita-T** [comment]
![Technology section](https://user-images.githubusercontent.com/76475512/224477786-9422735b-8eda-4c6e-af2f-5fef394d9a58.jpg)

Does this look good or should I add some other content?

**Comment by palisadoes** [comment]
Please submit a PR so that we can comment appropriately.

**Comment by Nitya-Pasrija** [comment]
@Yogita-T 
Can I work on this, if you aren't working on it?

**Comment by Yogita-T** [comment]
> @Yogita-T Can I work on this, if you aren't working on it?

I am working  on this. Thank you!

**Comment by Nitya-Pasrija** [comment]
Surely :)
