### ISSUE TITLE
Feature Request: Add to "Applications" section 

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-docs#450]
**Is your feature request related to a problem? Please describe.**
Our applications page is missing detail on why we chose typescript, flutter, and monogodb. 

**Describe the solution you'd like**
Add to the "Applications" page information on why we used typescript, flutter, and monogodb. Our youtube page has videos that could be a helpful resource: https://www.youtube.com/@PalisadoesOrganization/videos. 

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
I'd like to be assigned to this

**Comment by SalilHarit** [comment]
@Cioppolo14  is my pull request appropriate ?

**Comment by SalilHarit** [comment]
is my pull request appropriate ?

**Comment by mariomakter** [comment]
I'd like to be assigned to this

**Comment by SalilHarit** [comment]
already assigned to me
