### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mikoleNation** [PalisadoesFoundation/talawa-docs#451]
**Describe the bug**
The section of the site of the marked area as shown in the screenshot looks kinda dull and non appealing to the eye

**To Reproduce**

I plan to use the layout and css options which the system uses which I hope to get from @evasharma12 @tasneemkoushar @anwersayeed to help give the section a more authentic feel.

**Expected behavior**
Giving it that authenticity is key to giving the page that catchy feeling which will look appealing to users in the future

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![79C936B3-B11D-417F-876D-CC4A16B433E4](https://user-images.githubusercontent.com/112246930/224471312-a43982fc-e040-404b-9328-e84baf563ad8.jpeg)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KinetiCore-Labs** [comment]
Hi @mikoleNation , these pages are auto-generated. You can try and read more about this [here](https://dart.dev/tools/dart-doc). If you have any queries, feel free to connect with me on the Slack Channel.

**Comment by Cioppolo14** [comment]
Thank you for your submission!  Closing this due to the explanation above. Please keep the ideas coming!
