### ISSUE TITLE
Feature Request: Change background color of Dark Mode

### ISSUE THREAD

**Issue by salman-farooqi** [PalisadoesFoundation/talawa-docs#452]
**Is your feature request related to a problem? Please describe.**

The background color in 'Dark Mode' looks very odd, it is too much blue.

![blue](https://user-images.githubusercontent.com/127323880/224480417-0bc25343-7be6-459c-962e-fe8c1fb15140.JPG)

**Describe the solution you'd like**

Changed the color to dark, less blue, more decent and professional one.

**Additional context**
![black](https://user-images.githubusercontent.com/127323880/224480504-0b68d119-1943-4efa-9042-989005a29c55.JPG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by salman-farooqi** [comment]
I would like it to assing this to me.

**Comment by salman-farooqi** [comment]
I'm sorry, I've made so many changes, as this is my first in open source contribution.

**Comment by Cioppolo14** [comment]
@salman-farooqi No problem! We appreciate the effort in the accuracy  of the title.  Thank you for your submission.
