### ISSUE TITLE
Bug Report: Schedule update on the Palisadoes internship

### ISSUE THREAD

**Issue by Yass32** [PalisadoesFoundation/talawa-docs#454]
**Describe the bug**
The schedule part of the Palisadoes Unpaid Internship page is outdated.

**Screenshots**
![Screenshot (35)](https://user-images.githubusercontent.com/108995581/224486982-69cd3851-be44-4666-8e9a-981dba6bfd0c.png)

**Additional details**
Id like to update the dates

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noaholutunji** [comment]
What new dates would you like to update the current dates to?

**Comment by Cioppolo14** [comment]
May 31, 2023 would be a good date to update it too.  Please let me know if you want this assigned to you, and you have less than two issues already.

**Comment by Yass32** [comment]
@Cioppolo14 yes i want it assigned to me, thank you

**Comment by palisadoes** [comment]
@Yass32 please change the title of this issue. It is not descriptive enough for easy searches

**Comment by Yass32** [comment]
> @Yass32 please change the title of this issue. It is not descriptive enough for easy searches

Okay done
