### ISSUE TITLE
Excessive Spacing between Document Elements

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#456]
**Describe the bug**

The docs.talawa.io website documents  important community information. However the information listed on the site is too spread out due to the margins on:

1. headings
2. paragraphs
3. bullets

This means that:

1. Scrolling through the documentation takes excessive amounts of time.
1. Printing will consume unnecessary amounts of pages.

**Expected Actions**
The docusaurus margins for all elements must be restored to their defaults.

## Screenshots

**H2**
![image](https://user-images.githubusercontent.com/16875803/224492374-9f25b4e4-a652-43ab-8323-435d7c06415d.png)

**Paragraphs**
![image](https://user-images.githubusercontent.com/16875803/224492442-da82b1dc-ecb0-4b3f-bfe1-4df90f68cd56.png)

**Comment by salman-farooqi** [comment]
I would like it to be assigned to me. Thanks!

**Comment by salman-farooqi** [comment]
Thank you. How much time I get for submitting the PR? @palisadoes

**Comment by palisadoes** [comment]
- By default, the issue will be marked as inactive after 10 days.
- This is a really simple issue. If you cannot complete it this very early next week we'll assign it to someone else.

**Comment by salman-farooqi** [comment]
Thank you so much, it is more than enough time. I'll do my best. Thanks again!
