### ISSUE TITLE
Correct the spelling and grammar errors of the entire docs website.

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#459]
**Describe the bug**
Currently the docs website has a lot of spelling and grammar errors

**To Reproduce**

1. From the landing page go to talwa docs by clicking on the "Get Started" button

**Expected behavior**
Use tools like grammarly to check for spelling and grammatical errors and correct them.

**Actual behavior**

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on the issue

**Comment by palisadoes** [comment]
Please proceed. I'd like to see how that performs against the vscode spell checker. https://github.com/PalisadoesFoundation/talawa-docs/pull/335

**Comment by tinniaru3005** [comment]
> Please proceed. I'd like to see how that performs against the vscode spell checker. #335

Thanks a lot for assigning. I will start working on the changes today and draft a PR as soon as I can.

**Comment by Biki-das** [comment]
@palisadoes i have been working on integrating a automated and an unopinioniated way to check for the styles and grammer, this would result in running of a single command which would be able to scan both a single doc file or multiple of them and then give us suggestion on the basis of it
@tinniaru3005 you can continue to draft you work , and we can later analyse the outcomes  of both of our work.

**Comment by Biki-das** [comment]
> @palisadoes i have been working on integrating a automated and an unopinioniated way to check for the styles and grammer, this would result in running of a single command which would be able to scan both a single doc file or multiple of them and then give us suggestion on the basis of it @tinniaru3005 you can continue to draft you work , and we can later analyse the outcomes of both of our work.

see #467

**Comment by suhana832** [comment]
is it assigned to anyone ?

**Comment by MohitGupta14** [comment]
Hi, I am new to this organization, Can I work on this issue with the assignee?

**Comment by Cioppolo14** [comment]
We've had significant changes to the webpage, and we'd like to pause grammer and spelling issues right now, so I am going to close this issue.
