### ISSUE TITLE
Improve the About Us page of Talawa docs

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#463]
**Describe the bug**
The About Us page of Talawa docs can be further improved

**To Reproduce**

1. Go to the landing page of Talawa docs
2. Click on the Get Started button
3. Introduction
4. About Us

**Expected behavior**
- Add more details about Palisadoes Foundation and Talawa
- Add hyperlinks wherever possible for better navigation
- Restructure into paragraphs and points
- Add screenshots and images to better convey the information

**Actual behavior**

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by Cioppolo14** [comment]
Thank you for your submission! We have issue #344 which will be making significant changes to the home page and about us page, so I am going to close this for now.

**Comment by tinniaru3005** [comment]
![Screenshot_20230312-070124_Chrome](https://user-images.githubusercontent.com/62856848/224519310-4b1f1d6a-4ef1-4c09-b006-75060b1b4d92.jpg)
Hey @Cioppolo14  I am talinkg about making changes on this page and not the home page.

**Comment by tinniaru3005** [comment]
Also I am focusing on improving the content on this page.
