### ISSUE TITLE
Align the items in the footer on smaller screens

### ISSUE THREAD

**Issue by mankaache** [PalisadoesFoundation/talawa-docs#465]
**On smaller screens the contents of the footer all move to the left side of the footer , one on top of the other and it makes not have a good look**

![Screenshot (131)](https://user-images.githubusercontent.com/102906019/224550245-e189a1e1-34f7-4453-808e-28cf024d580e.png)

**Comment by mankaache** [comment]
i would like to be assigned this task

**Comment by Cioppolo14** [comment]
@babygirl2000 Thank you for your submission. We are pausing footer changes right now to allow our time to be focused on some other items.  I am going to close this, but please keep the ideas coming!
