### ISSUE TITLE
Add content to the Overview page of Talawa

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#470]
**Describe the bug**
The [Overview page of Talawa](https://docs.talawa.io/docs/developers/talawa/talawa-introduction) is almost Blank

**To Reproduce**

1. Go to [Overview page of Talawa](https://docs.talawa.io/docs/developers/talawa/talawa-introduction)

**Expected behavior**
Add content to this page

**Actual behavior**

**Screens
![talwa](https://user-images.githubusercontent.com/62856848/224542406-67788dfe-0f12-45ad-a34b-d9d14201e838.png)
hots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on it

**Comment by Biki-das** [comment]
duplicate #390

**Comment by Cioppolo14** [comment]
Thank you for your submission! This issue is already being worked in #390, but please keep your ideas coming!
