### ISSUE TITLE
overview text under Talawa API is too big

### ISSUE THREAD

**Issue by mankaache** [PalisadoesFoundation/talawa-docs#471]
**overview text under Talawa API is big, very pronounced and not uniform with the entire page**
A h3 heading was used for the text. 
This can be solved by using a heading with smaller font-size like h4 or we may not use a heading.
![Screenshot (133)](https://user-images.githubusercontent.com/102906019/224550908-cb5b2e99-f06d-45cf-b799-344a41491de0.jpg)

**Comment by palisadoes** [comment]
Make it normal text

**Comment by mankaache** [comment]
> Make it normal text

Okay I will
