### ISSUE TITLE
Change main components in the About Us page to better

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#472]
**Describe the bug**
Currently, the Main components of Talawa on the About Us page are in a paragraph.

**To Reproduce**

1. Go to [About Us](https://docs.talawa.io/docs/)

**Expected behavior**
Restructure it into points so that it can be clearly seen.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Talawa](https://user-images.githubusercontent.com/62856848/224560943-30ce537a-ea0d-46ca-9d25-267fb5ff2a66.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Complexlity** [comment]
I would like to work on this

**Comment by tinniaru3005** [comment]
@Complexlity thanks lot for your interest. Since I raised the issue I would like to work on it. But you can definitely find out other issues or raise your own. Thanks again. Let me know if I can help you in any way. 😊

**Comment by Cioppolo14** [comment]
@tinniaru3005 @Complexlity Thank you for your submission and willingness to work on items.  There are a few changes happening with the website and about us page in other issues, so for now, we'd like to pause issues until its all caught up.  Also, please comment on an issue if you'd like to be assigned it.  Sometimes people submit issues they've found, but don't necessarily want to work on them.  So a comment offering to be assigned the item is very helpful for us, even if you raised the issue.  Thank you. I am closing this for now.

**Comment by tinniaru3005** [comment]
Sure @Cioppolo14, I will keep that in mind. Thanks a lot for being patient and reviewing the issues and directing us. As mentioned in the Contributing Guidelines for Outreachy applicants, we are asked to raise PRs by making changes to 4 HTML, 5 CSS and 1 JavaScript element before moving ahead. It seems that it is not mentioned there that we must raise an issue before that. But in the PR I was directed to raise an issue. But now I cannot find out how can I proceed with this change if almost all the pages are undergoing changes. Can you please help me out by pointing out which areas where I can contribute? It will help me a lot to avoid confusion and help me focus on making contributions that will be impactful for the organization.
