### ISSUE TITLE
Feature Request:- Replace the sidebar.js config with the default docusaurus generated config.

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#473]
**Is your feature request related to a problem? Please describe.**
Currently the `sidebar config.js` file is being written manually, by default docusaurus comes with a autogenerated config which will automatically generate the sidebar for us, we can create as many side bar as we want . Manullay writing the sidebar is cumbersome and this would automate the whole process of sidebar generation

https://docusaurus.io/docs/sidebar/autogenerated

**Describe the solution you'd like**
Removing the current sidebar config and replace it with the auto generation config
**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Complexlity** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
@Biki-das You have been submitting a series of PRs with only one or two lines of code in modifications. This consumers a lot of our time to review. 

Please create a plan expressing all the changes you feel would be necessary in the next month so that we can review them in a more planned way.

The current approach reduces of ability to have a well made site due to the interruptions in our train of thought.

I hope you understand. We need better management of this process. The current approach is not optimal.

@Cioppolo14 please note

**Comment by Biki-das** [comment]
> @Biki-das You have been submitting a series of PRs with only one or two lines of code in modifications. This consumers a lot of our time to review. 
> 
> Please create a plan expressing all the changes you feel would be necessary in the next month so that we can review them in a more planned way.
> 
> The current approach reduces of ability to have a well made site due to the interruptions in our train of thought.
> 
> I hope you understand. We need better management of this process. The current approach is not optimal.
> 
> @Cioppolo14 please note 
Sorry for this activity @palisadoes , yeah sure i would draft one issue for specific areas and then work on them!  Where should i put my plan on? Should i upload it on slack or create a issue here itself?

**Comment by Biki-das** [comment]
@palisadoes should i close this one, though this wont be a one or two liner change, i would be deleting the whole config and replace this with a custom auto side generated config?, if not i shall close this one too.

**Comment by palisadoes** [comment]
We'll need to close this. It requires us to manage a separate configuration file in each folder and therefore will be more difficult to troubleshoot, especially for newcomers to the project. Though not optimal, what we have currently is adequate. We can revise this when we get a more complex file structure. Closing.

- https://docusaurus.io/docs/sidebar/autogenerated
