### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by mikoleNation** [PalisadoesFoundation/talawa-docs#476]
**Describe the bug**
the front page of the documentation site looks pretty dull especially the footer area containing the social media handles information. I particularly feel the aforementioned should be replaced with icons after all they are called social handles for a reasons so its supposed to totally represent that

**To Reproduce**

1.will be using gradients to give the website a new feel of life especially when in transition, it will even just look better. I for one feel the homepage is what really communicates or gets the attention of users. @palisadoes @evasharma12 @tasneemkoushar  please take a look at this
2 I dont know if boostraps are allowed, but if they are, I  will be implementing that  too.. As  boostraps are well known for making a website or a webpage responsive, interactive and user friendly.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Screenshot (290)](https://user-images.githubusercontent.com/112246930/224573573-66ce8c23-dd71-4f2a-810d-0dba96c8b693.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@mikoleNation Thank you for your submission.  Issue #344 is working on this, so I am going to close this. Please keep the ideas coming!
