### ISSUE TITLE
Hyperlink the component name instead of the description

### ISSUE THREAD

**Issue by tinniaru3005** [PalisadoesFoundation/talawa-docs#479]
**Describe the bug**
In the README.md Talawa Components part the description is hyperlinked instead of the component name

**To Reproduce**

1. Go to the README.md
2. Talawa Components

**Expected behavior**
Hyperlink the component name instead of hyperlinking the component description

**Actual behavior**

**Screenshots**
![Hyperlink](https://user-images.githubusercontent.com/62856848/224636995-c4fd4588-7470-4c91-8c9b-afabd8ce24f2.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by tinniaru3005** [comment]
I would like to work on the issue

**Comment by salman-farooqi** [comment]
But in my opinion, one would clink on the component description not the name because It's easy to click on the component's description compared to component's name.

**Comment by Cioppolo14** [comment]
@tinniaru3005 Thank you for your submission. I noticed you have 3 issues already.  Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Cioppolo14** [comment]
I am going to close this so we can focus on some other items right now.  Please keep the ideas coming!
