### ISSUE TITLE
Bug Report: Fix the minor bug issues across the website

### ISSUE THREAD

**Issue by salman-farooqi** [PalisadoesFoundation/talawa-docs#480]
**Describe the bug**

There are few minor bugs that should be fixed: **_(Images included for each step)_**

**To Reproduce:**
Steps to reproduce the behavior: (described by the images below in the 'Actual Behavior' section)

1. There should be a space between the paragraph and image.
2. There should be link provided to (point 5) as all other points have also links. (If @palisadoes can provide me the link in the comment section)
3. The (h1) in the website is taking too much space (height or margins of h1 should be decreased).
4. The text (h3) here is too big which should be converted into normal text (paragraph).
5. The Youtube video link section is not responsive for mobile devices. ([https://docs.talawa.io/docs/developers/talawa-admin/plugins/plugin-architecture](url))

**Actual behavior**
1. 
![image issue](https://user-images.githubusercontent.com/127323880/224657839-b1b4a86d-94df-4995-8913-7511f4d8bf50.JPG)

2. 
![link issue](https://user-images.githubusercontent.com/127323880/224657969-94f90c96-8b75-4952-ac47-d1e7142673bc.JPG)

3. 
![h1 issue](https://user-images.githubusercontent.com/127323880/224658868-7605dc8b-d6c2-42bf-8474-ec1dad2ac450.JPG)

4. 
![h3 headings](https://user-images.githubusercontent.com/127323880/224678889-bbcc5af3-437b-4ede-b145-ef393942d63b.JPG)

5. 
![image issue2](https://user-images.githubusercontent.com/127323880/224681400-f7cab572-c021-4552-9f06-af15df88e3bf.jpeg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by salman-farooqi** [comment]
I would like to work on these bugs.

**Comment by jadeharr** [comment]
@Cioppolo14 Would this need to be multiple issues?

**Comment by salman-farooqi** [comment]
Thank you so much for mentioning, I was also wondering about it.
What would you suggest me to? @Cioppolo14 
I have already solved these issues in my local system.
I will edit the current Issue, solve only one of the 5, and then
I can open separate Issue for each one of the remaining 4.

**Comment by salman-farooqi** [comment]
> Thank you so much for mentioning, I was also wondering about it. What would you suggest me to? @Cioppolo14 I have already solved these issues in my local system. I will edit the current Issue, solve only one of the 5, and then I can open separate Issue for each one of the remaining 4.

Would you please help me on this? @Cioppolo14

**Comment by Cioppolo14** [comment]
@salman-farooqi I believe some of these are being addressed in other issues, but #5, the youtube link, needs attention. Can you make a separate issue for that one? I'm going to close this one.  Thanks for your patience, I'm trying to catch up and make sure I'm tracking everything.
