### ISSUE TITLE
Make the "Talawa API" and "Talawa" components' display consistent with "About's" 

### ISSUE THREAD

**Issue by OndeyoMatoke** [PalisadoesFoundation/talawa-docs#482]
**Is your feature request related to a problem? Please describe.**
There is inconsistency in display when you click on different navbar components. For example, if you on Home page or "About" page, you are able to see "Talawa" and "Talawa API". This is not the same as when you click the latter two. If you are on "Talawa API" for instance, for you to go to "Talawa", you are forced to go back to "About" oh Home page first, which is time consuming. 

**Describe the solution you'd like**
I would have to adjust the CSS of both "Talawa" and "Talawa API" so that we have all the components display at the top once either of them is clicked.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![Screenshot (31)](https://user-images.githubusercontent.com/110782898/224748722-67c382bd-ec2d-4043-aa63-3d52769defaa.png)
![Screenshot (32)](https://user-images.githubusercontent.com/110782898/224750672-7577d517-67b2-4442-a7c7-51225da3fc9d.png)
![Screenshot (33)](https://user-images.githubusercontent.com/110782898/224750705-0a5dd191-a73a-493d-93f9-6700c134ba2d.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by OndeyoMatoke** [comment]
If approved, I would love to be assigned to work on this feature

**Comment by palisadoes** [comment]
Duplicate issue. Closing. Please search the issues before opening one.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199
- https://github.com/PalisadoesFoundation/talawa-docs/issues/200
