### ISSUE TITLE
Feature Request: Update Ideas List Page

### ISSUE THREAD

**Issue by Yass32** [PalisadoesFoundation/talawa-docs#484]
**Is your feature request related to a problem? Please describe.**
I want to update the Ideas List page by adding Outreachy and Palisadoes Unpaid Internship, to its internship program list

**Describe the solution you'd like**
Id like to add Outreachy & Palisadoes Unpaid Internship to the list as well as its links

![Screenshot (39)](https://user-images.githubusercontent.com/108995581/224760665-c02ad867-e0a0-45c5-abd4-81d306f4a7d3.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I like to work on this

**Comment by palisadoes** [comment]
Please remove the references to the GitHub Externship

**Comment by Yass32** [comment]
> Please remove the references to the GitHub Externship

Okay thanks

**Comment by singhavs** [comment]
@palisadoes Hey can I work on this?

**Comment by Yass32** [comment]
@singhavs I am already working on it :)

**Comment by singhavs** [comment]
@Yass32 okay

**Comment by tasmeomeem** [comment]
Can i fix it?

**Comment by salman-farooqi** [comment]
Have you made any progress on this? @Yass32

**Comment by palisadoes** [comment]
Closing. The ideas pages have been significantly revised.
