### ISSUE TITLE
Bug Report: Fix Page Break and Header Text Issues

### ISSUE THREAD

**Issue by Ugboaja-Uchechi** [PalisadoesFoundation/talawa-docs#485]
**Describe the bug**

- There are some minor styling issues concerning some `h2` text that takes up a lot of space and are as large as some `h1` text on mobile and desktop view.
- The "Plugin Architecture page breaks".

**To Reproduce**

1. From the landing page go to talwa docs by clicking on the "Get Started" button
2. While going through different pages in the sidebar this styling issue can be noticed

**Expected behavior**
A clear hierarchy of different headers to make it easier for users to differentiate different headings.

**Screenshots**

Font-Size  Bug | Page Break
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/224823505-2fef5bbb-ff29-4e10-9de2-e7d2fe5a764a.png)  |  ![image](https://user-images.githubusercontent.com/74814780/224829110-fbad148e-57e6-43f2-96b6-be0db8581ec2.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ugboaja-Uchechi** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
Please change the title of this issue so that it will be more easily searchable.

**Comment by Ugboaja-Uchechi** [comment]
I just did. Is this good enough?

**Comment by Cioppolo14** [comment]
Closing this issue for now.  Please make a new one that focuses on the text/header issues only. See PR #562
