### ISSUE TITLE
Feature Request:- Adding deployed Previews of the Documentation site

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#489]
**Is your feature request related to a problem? Please describe.**
Since documentation changes are mostly visual and design changes, having to see the changes on a deployed preview related to the PR would help us to review the PR fast as the changes can been seen directly by clicking on the preview link which will redirect to the preview of the website made after the changes

**Describe the solution you'd like**
1. Adding the `Deploy Preview PR` action to our yaml config.
2. Add the necessary workflows for the config to work.
3. we want to call the action only on certain type of changes , so we need to configure for the changes we want deployed preview for

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing as not planned.

1. You can pull the PR and view it on your system
2. You can provide screen shots
3. Having duplicate sources of Talawa docs for Google to access will create confusion.
    1. https://www.youtube.com/watch?v=Q4K6uJxrAOw

Please think through your issues before opening them. The frequent repetition of these types of issues is consuming too much time.
