### ISSUE TITLE
Bug Report - The image floating over the Paragraph

### ISSUE THREAD

**Issue by salman-farooqi** [PalisadoesFoundation/talawa-docs#490]
**Describe the bug**
The image is floating over the paragraph which should be fixed by creating a gap/space between them.

**To Reproduce**

1. Go to the Talawa docs site
2. In >developers>talawa-admin>plugins>plugin-architecture
3. Create a gap between image and paragraph

**Actual behavior**

![image issue](https://user-images.githubusercontent.com/127323880/224912916-56947a38-4382-4468-8886-6cc693288701.JPG)

**Expected behavior - after fixing the bug**

![image issue solved](https://user-images.githubusercontent.com/127323880/224912801-1ddd316d-6d1a-4ffb-b771-2ef5c325430e.JPG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Thank you for your submission.  We are focusing on updating content right now, but this might a good one to come back to with a list of items like this in the future, or as part of a project.  I'm going to close this for now.  Please keep the ideas coming!
