### ISSUE TITLE
Modification of "news" and "contact us" community links of Footer

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#495]
**Problem**
The icons of **News** and **Contact Us** are not appropriate.

**Describe the solution you'd like**
They can be made more precise by changing them to appropriate icons.

**Describe alternatives you've considered**
We can add the telephone icon for contact and newspaper icon.

**Approach to be followed (optional)**
We will be placing the exact link of the icons which matches the context of the given names.

**Screenshot**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/67657066/225123212-c8d902f2-4f8e-48a4-bcb1-20eb962209c7.png">

**Comment by singhavs** [comment]
@palisadoes can I work on this?

**Comment by Cioppolo14** [comment]
@singhavs Thank you for your submission.  For right now, we are pausing footer changes, but would consider this change in the future as part of a larger internship project.  I'm going to close this for now.  Please keep the ideas coming!
