### ISSUE TITLE
Repetition of "GSoC" in the navbar

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#496]
**Describe the bug**
**GSoC** has been listed as a seperate link in the navbar even though it is under the category of [**Internships**](https://www.palisadoes.org/about/) .

**Expected behavior**
GSoC should be used once  in internship category.

**Preview**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/67657066/225126689-d7f44c8a-4eae-4bd2-905f-3705dfdc6fde.png">

**Comment by singhavs** [comment]
@palisadoes can I work on this issue?

**Comment by palisadoes** [comment]
This site is not managed by Talawa repositories. Closing.

**Comment by singhavs** [comment]
Noted ! @palisadoes
