### ISSUE TITLE
Bug Report: Replace the images representing the emails with email-links

### ISSUE THREAD

**Issue by oyenuga17** [PalisadoesFoundation/talawa-docs#497]
**Describe the bug**
Using  images to represent emails creates a bad user experience such that  a user cannot highlight the text in the image. 
**To Reproduce**

 1. The Emails on the following links and others are represented using images:
 https://docs.talawa.io/docs/internships/palisadoes/palisadoes-introduction
https://docs.talawa.io/docs/internships/gsod/gsod-ideas-2022
https://docs.talawa.io/docs/internships/gsod/gsod-ideas

**Expected behavior**
Emails should be represented using email links in order for a reader to easily copy or click on the link to send a direct message.

**Screenshots**
<img width="566" alt="Screenshot 2023-03-14 at 23 02 31" src="https://user-images.githubusercontent.com/64274826/225151561-103282d0-f9c4-498d-b048-fc70fa3f2685.png">

**Comment by oyenuga17** [comment]
@palisadoes  @DMills27  please i would love to be assigned to this issue

**Comment by palisadoes** [comment]
Thanks. We will not do this for the reasons stated in these issues. Closing.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/497
- https://github.com/PalisadoesFoundation/talawa-docs/issues/235

It was a good observation.
