### ISSUE TITLE
Feature Request : Changing style of side menu(quick links) provided on each page

### ISSUE THREAD

**Issue by ayushi-8102** [PalisadoesFoundation/talawa-docs#498]
**Is your feature request related to a problem? Please describe.**
Change in styling of  side menu(quick links) that is provided on each page for better user experience.

**Describe the solution you'd like**
For better User Experience , we can change the styling and alignment of side menu of each page.
![Screenshot 2023-03-15 044648](https://user-images.githubusercontent.com/91957156/225163089-84d9c9b0-3dbd-4fd8-9983-ce5f393f4330.png)
(The following image is an example of a single page. Same is applied to all other pages of the website.)

**Describe alternatives you've considered**
We can change the font and font size of text . Also, Sections and sub-sections can be clearly defined by proper alignment.

**Comment by ayushi-8102** [comment]
Please assign me this issue.

**Comment by Cioppolo14** [comment]
@ayushi-8102 Do you have a screen shot of what you'd like to do?

**Comment by Cioppolo14** [comment]
We have upcoming website changes, so I am going to close this issue for now.
