### ISSUE TITLE
Modification in the search option in Talawa API

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#499]
**Is your feature request related to a problem? Please describe.**
Extra category options are present while searching for a specific one

**Describe the solution you'd like**
Removing the extra categories that are shown on search.

**Describe alternatives you've considered**
Instead of showing all the categories on search we can just render the data that is searched

**Preview**
<img width="239" alt="image" src="https://user-images.githubusercontent.com/67657066/225273842-59e0dc23-b561-4cfa-8ba2-c34697d8a857.png">

**Comment by singhavs** [comment]
@palisadoes can I get assigned with this?

**Comment by Cioppolo14** [comment]
@singhavs Thank you for your submission.  This page is automatically generated.  Please see these two issues if you are interested in supporting the updating of the automation process:  #199 #200.
