### ISSUE TITLE
Anchor Tags not getting redirected

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#500]
**Describe the bug**
The anchor tags in the about section do not have the functionality of redirecting to the previous pages.

**Expected behavior**
On click of the anchor tags it should get redirected to its respective pages.

**Actual behavior**
Not showing any functionality on clicking.

**Screenshots**
<img width="773" alt="image" src="https://user-images.githubusercontent.com/67657066/225284406-35017624-383c-414e-8520-0b7aeebabc44.png">

**Comment by singhavs** [comment]
@palisadoes can I work on this?

**Comment by Cioppolo14** [comment]
@singhavs Thank you for your submission. The anchor tags are working for me.  Can you identify what is giving you an issue?
