### ISSUE TITLE
Uncentred footer in talawa API in mobile view

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#501]
**Describe the bug**
The footer of the talawa API page is not centerd and alligned to right side of the page.

**Expected behavior**
The footer should be alligned at the centre of the page.

**Screenshots**
<img width="227" alt="image" src="https://user-images.githubusercontent.com/67657066/225287397-72597d60-f438-4542-995d-8e5e235d364f.png">

**Comment by singhavs** [comment]
@DMills27 @Cioppolo14 @palisadoes I would like to fix this issue

**Comment by Karnankita04** [comment]
@palisadoes Can I work on this issue? Thankyou!

**Comment by singhavs** [comment]
@Karnankita04 I am working on this issue, waiting for @palisadoes to assign it to me.

**Comment by Karnankita04** [comment]
@singhavs okay!

**Comment by Cioppolo14** [comment]
@singhavs Thanks for submitting your request to update the content of https://docs.talawa.io/talawa/index.html and https://docs.talawa.io/talawa-api/schema/index.html The files under these directories are 100% generated automatically by every merged PR in the Talawa, Talawa-API and Talawa-Admin repositories. The automated action parses the source Flutter and Typescript source code for comments on each method, class and function using the DartDoc and TSDoc packages and creates HTML suitable for online documentation from them. With each PR, the files in Talawa-Docs are completely overwritten by these PRs.

We have created special issues to update the look and feel of these automated updates in these issues below. We need to close this issue as it is a duplicate. Thanks, and continue searching for similarly inspiring ideas to make our documentation better. Please ask to have it reopened if you think this was done in error.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199
- https://github.com/PalisadoesFoundation/talawa-docs/issues/200
