### ISSUE TITLE
Styling modification of documentation of about page.

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#502]
**Problem**
The content present in the about section of the website is not justified throughout and needs some styling in the alignment as mentioned in the snapshots.

**Solution**
The paragraphs can be properly alligned.

**Before**
<img width="602" alt="image" src="https://user-images.githubusercontent.com/67657066/225303592-55157f1b-0388-4a1d-8671-4d327e8b6c0a.png">

**After**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/67657066/225304009-63541a04-f8ad-4565-9513-f182a7a0f8e1.png">

**Changes**
As seen the paragraphs are justified.

**Comment by singhavs** [comment]
@DMills27 @Cioppolo14 @palisadoes I would like to work on this issue.
Can you assign it to me?

**Comment by pushpanjali-10** [comment]
Can you assign it to me?

**Comment by singhavs** [comment]
@pushpanjali-10 I am already working on this, waiting for @palisadoes to assign it to me.

**Comment by Cioppolo14** [comment]
@singhavs Thank you for your submission.  We are focusing on content related updates right now. This one would be good to include in a larger group of changes.  I am going to close this for now. Please keep the ideas coming!
