### ISSUE TITLE
Footer's size is too big need to make the elements in horizontal way

### ISSUE THREAD

**Issue by Karnankita04** [PalisadoesFoundation/talawa-docs#504]
s your feature request related to a problem? Please describe.
The footer size is looking too big as it is taking so much space of the webpage and this feature makes it unattractive.

Describe the solution you'd like
It would look good if the community and Development part would be in horizontal way, if for example the Community part like Slack, Twitter, etc would be in horizontal way, this will work a lot and make it soo attractive.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
![doc footer](https://user-images.githubusercontent.com/91003709/225307356-f1573394-c6ca-45af-b143-b85471820bc1.jpg)

**Comment by Karnankita04** [comment]
@palisadoes can I work on this feature? Thankyou!

**Comment by pushpanjali-10** [comment]
Can i work on this?

**Comment by Cioppolo14** [comment]
@Karnankita04 Thank you for your submission.  Right now, we are pausing footer changes to focus our resources on content related updates.  Please keep your ideas coming!
