### ISSUE TITLE
Bug Report: A. Navbar links in new tabs B. footer update

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#506]
**Describe the bug**
The Talawa and Talawa Api headings in the Navbar open in the same page, however they should

**Expected behavior**
The Talawa and Talawa Api headings in the Navbar open in the same page, however

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pushpanjali-10** [comment]
Can you assign it to me?
