### ISSUE TITLE
Bug Report: A. Navbar links in new tabs and B. Footer update

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#507]
**Describe the bug**
A. The headings for "Talawa" and "Talawa API" in the Navbar currently open in the same page, but it would be better if they opened in a new tab. This is because their UIs are different, and it could potentially confuse users if they are taken away from the current page without warning.

B. The footer says "Copyright © 2023 My Project, Inc. Built with Docusaurus."

**Expected behavior**
The Talawa and Talawa Api headings in the Navbar should open in a new tab.
The footer needs to be updated and "My Project" needs to be changed to "Talawa"

**Screenshots**
![image](https://user-images.githubusercontent.com/97171261/225388717-dc1022bf-2350-4004-9a7d-6261bf2cc24a.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pushpanjali-10** [comment]
Can you assign it to me?

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 @These are small changes, hence merging them into one issue. Or should I create separate issues for them?
Also please assign it to me

**Comment by jmalicha** [comment]
Please review it for me. thanks

**Comment by tasmeomeem** [comment]
Can i fix it?
