### ISSUE TITLE
Bug Report: _Current UX reference Page doc seems out of flow and need a more stable structure

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#510]
**Describe the bug**
The current [Talawa UI/UX reference page](https://docs.talawa.io/docs/design/ux/ux-talawa) seems out of structure, the reader may find this hard to go through as the sections are intermingled the flow of the page is not quite consistent

**Expected behavior**

https://user-images.githubusercontent.com/72331432/225412487-a5d6d1e9-1573-41b7-8def-a81ce7f765e0.mp4

I have tried to structure the page by making the particular heading bold and divided each section properly

**Actual behavior**
![Overview _ Talawa Project Documentation — Mozilla Firefox 3_16_2023 12_17_31 AM](https://user-images.githubusercontent.com/72331432/225412715-143c23c0-cfb2-4af5-9e43-5fa9b2b2e7e9.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to solve this issue

**Comment by jmalicha** [comment]
Please assign it to me. Thanks

**Comment by Cioppolo14** [comment]
@jmalisha When completing this, please also address any typos or grammar issues you see in this page. Thank you!

**Comment by Cioppolo14** [comment]
@Biki-das Thank you for your submission. Our policy is to assign no more than two issues to each contributor, you currently have 2. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too, but only if you do not plan on working on them in the future.

**Comment by Biki-das** [comment]
> @Biki-das Thank you for your submission. Our policy is to assign no more than two issues to each contributor, you currently have 2. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too, but only if you do not plan on working on them in the future. 

Sure

**Comment by Biki-das** [comment]
hello @jmalisha you can checkout my screen recording above to get an idea on how to improve the page, rest you are free to include your observations and decide the changes you want to implement!

**Comment by jmalicha** [comment]
Hi, @Biki-das I will do that thanks a lot!
