### ISSUE TITLE
Modification in Navbar 

### ISSUE THREAD

**Issue by singhavs** [PalisadoesFoundation/talawa-docs#513]
**Problem**
As we see in the mobile view that **GitHub**  is listed under the navbar elements but in desktop view it is seperated from the rest of the navbar elements i.e it is moved to the right side of the page

**Describe the solution you'd like**
It would look more organised if it was moved to the left and set along with the rest of navbar elements.

**Screenshots**
In desktop view.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/67657066/225483363-c82f3434-30f2-4a85-b503-a26274559a14.png">

In smaller screen it is a part of the navbar elements
<img width="277" alt="image" src="https://user-images.githubusercontent.com/67657066/225483498-f8f35803-5177-4105-b471-b4f90d763097.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by singhavs** [comment]
@Cioppolo14  @palisadoes I would like to work on this issue, can you assign it to me?

**Comment by Cioppolo14** [comment]
@singhavs Thank you for your submission.  We would like to leave this as it is right now.  Please keep your ideas coming!
