### ISSUE TITLE
[Feature Request] A thorough flow-chart of the app

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa-docs#514]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but more of an enhancement. We can make a thorough document that mentions the flow of our app in detail, start from the `main.dart` itself.

**Describe the solution you'd like**
We can make a detailed flowchart of the app to ensure that new contributors understand the app correctly. Also, existing contributors will be helped a lot if they want to implement a new feature on top of another feature and want to understand how it works under the hood.
Something like this ?

![ex](https://online.visual-paradigm.com/repository/images/6c72bbc4-bd05-4e49-aa6f-e7f64d238cac/flowchart-design/riding-a-train.png)

In our case, we can make charts for flow of pages and the conditions that lead to them. This will help tremendously in bug fixing and especially help newcomers as one can guess the cause of error just by looking at the flow of the app, instead of manually running and checking through codebase.

**Approach to be followed (optional)**
There are a few options
1. [draw.io](draw.io)
2. Maybe a Google Doc
3. Figma Design (overkill ?)
4. [Excalidraw](https://excalidraw.com/)

**Comment by Biki-das** [comment]
@literalEval i would like to work on this one!

Since what you are referring to the flow of app, we can go with excali draw as you suggested and come up with a neat structure

**Comment by literalEval** [comment]
@Biki-das mentors will assign it to you. I'm a contributor just like you :)

BTW do you idea about our app ? And how do you plan to implement this ?

**Comment by Biki-das** [comment]
> @Biki-das mentors will assign it to you. I'm a contributor just like you :)
> 
> BTW do you idea about our app ? And how do you plan to implement this ?

yes i have a rough idea would need to dig , tha main.dart file exists at the lib folder right?, getting the primary widgets of the app would be the primary task  ,after that i would need to plan.

**Comment by literalEval** [comment]
Okay. But please be thorough and precise. Also, please give preference to detail over quantity. This is a large issue and will only be completed by many contributors' collaboration. Maybe we can create some smaller tasks from this, if @palisadoes agrees.

**Comment by palisadoes** [comment]
@Biki-das let's give a newcomer a chance to work on this. Everyone needs to get an opportunity.

**Comment by Biki-das** [comment]
> @Biki-das let's give a newcomer a chance to work on this. Everyone needs to get an opportunity.

@palisadoes sure, :-)

**Comment by literalEval** [comment]
@palisadoes I think we can covert this issue into many sub issues. That way everyone gets a chance and quality of the contribution will also be good, because we will need a flow chart of our whole app, and that is a huge task. What do you say ?

**Comment by Cioppolo14** [comment]
@literalEval Do you have a vision for how to break it down into several issues? It seems to make sense to me, and might make it more appealing for newer people to join the effort.

**Comment by literalEval** [comment]
Yeah @Cioppolo14 I think we can divide it as the flow goes. Like

1. Entrypoint
2. Pre-auth Screens
3. After-auth Screens
  1. Screens that are shown in that order

**Comment by Biki-das** [comment]
@Cioppolo14 can i start working on this one? or if you have anything in mind particularly where can i work on?

**Comment by palisadoes** [comment]
Does anyone want to work on this?

**Comment by Biki-das** [comment]
> Does anyone want to work on this?

I wanted to, but seeing the level of support from maintainers from work, this was probably my worst interaction with any open source project,  i really do not want to drag this.
