### ISSUE TITLE
Bug Report:- documentation website Theme does not correspond to the preferences of the user

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#516]
**Describe the bug**
Currently our documentation site does not adapt according to the user preferred theme, suppose some one's system or Operating system mode is default to dark mode , our documentation seem to present it on light theme, which is not a good user experience, we should make it adapt to the user preffered theme.

**To Reproduce**

1. Choose your system theme to dark.
2.  Navigate to the talawa doc repo.
3. The site will be presented in light theme.

**Expected behavior**

https://user-images.githubusercontent.com/72331432/225626831-645b61d8-7a41-4804-8d2f-223067ec7141.mp4

The above is after the changes i made to ensure it takes the system preferences in account to show the theme.

**Actual behavior**

https://user-images.githubusercontent.com/72331432/225628424-8c9ccb95-9315-4899-9f84-e38f6e6ae80c.mp4

Our current site, does not take into account the system preference, it should have changed the theme based on the system preference of the user.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to work on this one

**Comment by Cioppolo14** [comment]
Thank you for your submission. 
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of serious bugs. Think of any difficulty you have had in getting things working, or limitations in explanations. There could be a bug there waiting for you.

We will only be accepting feature issues for deficiencies that are obviously lacking for users. 

I am going to close this PR.
