### ISSUE TITLE
Feature Request: updating overview of the Member page

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#519]
**Is your feature request related to a problem? Please describe.**
The Members page overview is currently lacking in content despite the abundance of information available in its sub-pages. I am keen to address this issue and improve the page's overall usability.

**Describe the solution you'd like**
To enhance the user experience and facilitate better comprehension, I intend to document all the features included in the Members-overview. To achieve this, I will reference the various sub-pages within the Members category.

**Additional context**
![image](https://user-images.githubusercontent.com/97171261/225671164-87d3ced1-5951-4647-bb9b-b6b598609341.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@palisadoes @Cioppolo14 
Please assign this to me

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija Please fill out this page as best you can to better meet its purpose.  Let me know if you need help! Thank you!

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
Surely :)
Also quick question, should I remove the work in progress component too from here?
