### ISSUE TITLE
Feature Request: Adding documentation to the talawa-admin repo

### ISSUE THREAD

**Issue by AryanKoundal** [PalisadoesFoundation/talawa-docs#520]
**Is your feature request related to a problem? Please describe.**
The talawa-admin repository lacks documentation. Hence, as a reference for the contributors and to aid them in understanding the codebase this repository can be improved by documenting it. I found the organization wants to add documentation in this repository from https://docs.talawa.io/docs/internships/gsod/gsod-ideas/#add-base-documentation-to-talawa-and-talawa-admin-repositories section.

**Describe the solution you'd like**
I would like to document the React Components https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components . I am thinking about starting from the first three, which are

   - [AdminDashListCard](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/AdminDashListCard)
   - [AdminNavbar](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/AdminNavbar)
   - [ContriStats](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/ContriStats)

and then complete the rest as well.

**Approach to be followed (optional)**
I'll be using TSDocs for documenting the codebase.
Reason to use TSDocs : TSdocs has already been used by the organization and it provides a standard format to create efficient typescript documentation.

**Additional context**
I opened this issue in talawa-admin repo, then I was redirected to open this issue in talawa-docs. 

@palisadoes should I start working on it?

**Comment by Cioppolo14** [comment]
@AryanKoundal Thank you for your submission! This isssue is already being worked on, so I am going to close it.
