### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Taofeeqah** [PalisadoesFoundation/talawa-docs#523]
**Describe the bug**
The favicon is somewhat small and not prominent enough compared to other websites. The reader may find it challenging to locate the tab when there are several tabs open.

**To Reproduce**
Smart crop the favicon.ico image which is automatically effected across all tabs.

**Expected behavior**
![Screenshot 2023-03-17 155027](https://user-images.githubusercontent.com/45803442/225949640-23058049-eee4-40ab-80e6-f990f015e005.png)

**Actual behavior**
![Screenshot 2023-03-17 153205](https://user-images.githubusercontent.com/45803442/225949725-8603ae23-df48-4663-9b73-6155685a4d43.png)

**Result of the rectified issue**
![Screenshot 2023-03-17 155915](https://user-images.githubusercontent.com/45803442/225949942-c5119449-35b6-442d-9445-05d6233c5c7d.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I am available to work on this issue

**Comment by palisadoes** [comment]
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of serious bugs. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
