### ISSUE TITLE
Feature Request: - Adding a more detailed outline for the Talwa api overview page

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#527]
**Is your feature request related to a problem? Please describe.**
Reading through the Talawa API i feel we can add more bits of information , to make the page content more informative

**Describe the solution you'd like**
Added a description for the Talawa API about its structure and design

Below are the sections i created

![Overview _ Talawa Project Documentation — Mozilla Firefox 3_18_2023 1_44_50 PM](https://user-images.githubusercontent.com/72331432/226094005-6e6cb9e3-0233-41d4-bea4-007643360d4c.png)

![Overview _ Talawa Project Documentation — Mozilla Firefox 3_18_2023 1_45_00 PM](https://user-images.githubusercontent.com/72331432/226094043-9b713d15-85dc-4b39-9882-0d0b6710fed4.png)

![Overview _ Talawa Project Documentation — Mozilla Firefox 3_18_2023 1_45_10 PM](https://user-images.githubusercontent.com/72331432/226094052-93eebe94-a352-4379-b58e-df9b8cc052cc.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
I am closing this issue for now, the webpage has had significant reorganization.
