### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by akshat-jnn** [PalisadoesFoundation/talawa-docs#529]
![Screenshot (307)](https://user-images.githubusercontent.com/91486662/226098055-0d07a6c6-2c1e-4437-8e55-75e1da28a7c9.png)
**Is your feature request related to a problem? Please describe.**!
when we are on the about page and this was the first page so it's evident that it does not have any previous page so at the end of the page there is a next button and I think this button will be in the middle of the page instead of right 
**Describe the solution you'd like**
I think next button on about will be on middle not in right when it does not have any previous page

**Additional context**
![Screenshot (307)](https://user-images.githubusercontent.com/91486662/226098055-0d07a6c6-2c1e-4437-8e55-75e1da28a7c9.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@itsAkshat-jain Thank you for your submission. 
We are focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.


For Talawa-Docs, item 3 is our main focus right now.  I am going to close this.
