### ISSUE TITLE
Feature Request: Data Management Overview Docs update

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#531]
**Is your feature request related to a problem? Please describe.**
The documentation for the Data Management Overview page should be expanded to include detailed information about the different subcategories of features available, and ensure that all the information is linked together cohesively.

**Describe the solution you'd like**
I would like to enhance the documentation of the Talawa project's data management by including comprehensive information about its various aspects.

**Additional context**
![image](https://user-images.githubusercontent.com/97171261/226121601-ac17ffe4-c15d-4a84-ad59-83aa1daa493a.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
Please assign it to me

**Comment by Cioppolo14** [comment]
Thank you for your submission.  This is currently being worked on in #390. Closing as a duplicate.  Please keep your ideas coming!
