### ISSUE TITLE
Bug Report: Update Background of Image to White

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-docs#534]
**Describe the bug**
The green background in the diagram/image is not ideal. Shown here: https://docs.talawa.io/docs/internships/gsod/gsod-ideas needs to be switched to white so it can be seen in both light and dark modes. 

**To Reproduce**
See image here: https://docs.talawa.io/docs/internships/gsod/gsod-ideas

**Expected behavior**
A clean image and color with no negative effects from light and dark mode changes. 

**Actual behavior**
The background color is not ideal, but can be seen in both light and dark modes. 

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
@Cioppolo14  Can you assign this issue to me?

**Comment by mariomakter** [comment]
I'd like to be assigned to this

**Comment by Yogita-T** [comment]
Hi @palisadoes,
![whiteimg](https://user-images.githubusercontent.com/76475512/226159832-348e7f3f-6a1e-459a-92ae-703e841869b4.jpg)
![blackimg](https://user-images.githubusercontent.com/76475512/226159845-3d19dc09-f469-4ecf-ae95-44f8b8556b1c.jpg)
Could you please review these changes to the background color? Should I create a PR?

**Comment by mariomakter** [comment]
Hi @palisadoes, created this image from scratch.may be this image resolution is good. Should I create a PR?
![image](https://user-images.githubusercontent.com/102503970/226170073-786d9725-701a-4fd2-b3e3-ca2567b93fa1.png)

**Comment by Yogita-T** [comment]
@mariomakter  Thank you for your work! but the issue has been assigned to me and I am currently focused on working on it.

**Comment by Ujjwal990** [comment]
Hi, can you assign this issue to me, I understood the issue and can fix it quickly.

**Comment by Yogita-T** [comment]
@Ujjwal990  I am already working on it. Thank you!
