### ISSUE TITLE
Bug Report: A. page not found fixes B. Redundant link fixes  C. adding "Functionalities page" to Sidebar

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#540]
**Describe the bug**
Here, https://docs.talawa.io/docs/internships/internship-ideas/#api---primary-idea-areas

A. The Github Extenship links lead to "page not found" errors, and hence should be removed
![image](https://user-images.githubusercontent.com/97171261/226412932-60a5c680-d8e5-46b0-9860-f0d797fcd497.png)

B. The YouTube inspiration link 2 and 4 is the same
![image](https://user-images.githubusercontent.com/97171261/226413374-c1ed040d-764a-41ef-b071-2778179dab51.png)

C. The Plugin guide redirects to a functionalities page, which isn't added to the Sidebar and hence is unreachable otherwise.
![image](https://user-images.githubusercontent.com/97171261/226413941-71a59a92-3f3d-4cf2-a16b-ddc8cd233569.png)
![image](https://user-images.githubusercontent.com/97171261/226414004-452adfc9-fee1-49c2-97b9-92ce96efb39b.png)

D. Apart from this, I also plan to make all the links relative, wherever possible.

**Expected behavior**
I wish to resolve this, by making the necessary changes.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
Can you assign this to me?

**Comment by Ujjwal990** [comment]
@Cioppolo14 can you please assign some above-mentioned issues to me.

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
Just noticed that there are 2 folders with the same files- 'docs/developers/talawa-admin/plugins' and 'docs/functionalities' has 3 files in common. Should I delete the functionalities folder, after transferring the 'core-functionalities.md' file to the talawa-admin plugin folder and create a link in the side bar for it?

**Comment by Cioppolo14** [comment]
> @Cioppolo14 Just noticed that there are 2 folders with the same files- 'docs/developers/talawa-admin/plugins' and 'docs/functionalities' has 3 files in common. Should I delete the functionalities folder, after transferring the 'core-functionalities.md' file to the talawa-admin plugin folder and create a link in the side bar for it?

Let's ask @palisadoes.  I think this is a question for you.

**Comment by Nitya-Pasrija** [comment]
@palisadoes @Cioppolo14 
The 'core-functionalities.md' is being used in the existing features, I changed the reference links to the plug-ins so I have made the links work and the sidebar is visible now without any conflicts. Please review :) 
However, I would suggest deleting the 3 other files from the functionalities folder, as the same content is in the talawa-admin plugin folders and I have linked them to the 'Plugin Guide'

**Comment by Cioppolo14** [comment]
> @palisadoes @Cioppolo14 The 'core-functionalities.md' is being used in the existing features, I changed the reference links to the plug-ins so I have made the links work and the sidebar is visible now without any conflicts. Please review :) However, I would suggest deleting the 3 other files from the functionalities folder, as the same content is in the talawa-admin plugin folders and I have linked them to the 'Plugin Guide'

Can you make another issue for the duplication of information, and describe the issue there?

**Comment by Nitya-Pasrija** [comment]
Alright

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
I have created an issue for this task: #563
