### ISSUE TITLE
Adding functionality to the news section ( https://docs.talawa.io/docs/features/news%20feed/news-feed-overview )

### ISSUE THREAD

**Issue by Ujjwal990** [PalisadoesFoundation/talawa-docs#541]
**Is your feature request related to a problem? Please describe.**
The **news-feed** section is [](https://docs.talawa.io/docs/features/news%20feed/news-feed-overview/#overall-guidance) . It is empty and shows nothing. I have planned to add the functionality to add news articles that will contain images, and people will be able to like and comment on them.

**Describe the solution you'd like**
This entire task is very big and I would like it to be assigned to different people. That way everyone will get the opportunity to work and contribute and also this task will be done in exponentially less time.

![image](https://user-images.githubusercontent.com/83486007/226415972-8d24531b-0133-4398-9030-1c1bc9677fe0.png)

@palisadoes

**Comment by palisadoes** [comment]
The newsfeed is an existing feature of the mobile app. This page should be deleted.

**Comment by Cioppolo14** [comment]
@Ujjwal990 Thank you for your submission. This is no longer a desired feature, but an actual feature in Talawa. Our Docs need some updating.  I'm going to close this issue since it is not applicable and other changes need to be made.
