### ISSUE TITLE
Bug report: Correcting the alignment of the footer of the page

### ISSUE THREAD

**Issue by Ujjwal990** [PalisadoesFoundation/talawa-docs#542]
**Describe the bug**
The footer of every page is misaligned on a desktop screen and also on the mobile screen and needs to be fixed.

**To Reproduce**

1. go to [https://docs.talawa.io/](https://docs.talawa.io/)
2. scroll to bottom of the page and you will see misaligned footer.

**Expected behavior**
On desktop screen Both the sections i.e. **Community** and **Development** should be aligned in the center of the page like the content above the footer.
On Mobile screen both the sections should be be placed side by side.

**Actual behavior**
In desktop both the sections are aligned to left side and in mobile screen they are placed one above the other.

**Screenshots**
![p01](https://user-images.githubusercontent.com/83486007/226423360-a32cb6d7-8943-40d2-a4a5-052b10fb9a30.png)

![p02](https://user-images.githubusercontent.com/83486007/226423553-b7517c43-a168-433b-8bb4-14b7beb2a2a0.jpg)

@palisadoes I would like to solve this issue.
**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ujjwal990** [comment]
@palisadoes Please assign it to me.

**Comment by Cioppolo14** [comment]
@Ujjwal990 Thank you for your submission.  We have a few impending footer changes right now, so we are pausing further changes.  Please keep your ideas coming!
