### ISSUE TITLE
[Feature Request] navbar border and search bar function added

### ISSUE THREAD

**Issue by mariomakter** [PalisadoesFoundation/talawa-docs#545]
### navbar and searchbar function added
**Is your feature request related to a problem? Please describe.**
Here which navbar and which main content section is not well understood.I think here added a border-bottom. I already added it.I think a search bar should be provided in navbar section and I already added it 

**Describe the solution you'd like**
 I would like it to be assigned and PR it .

**screenshot**
Actual behavior
![image](https://user-images.githubusercontent.com/102503970/226555947-b6edcef4-d68f-41c8-a213-866204ec5a64.png)

I added this 
![image](https://user-images.githubusercontent.com/102503970/226556090-4595b596-7c38-4410-9de1-94db98602576.png)
![image](https://user-images.githubusercontent.com/102503970/226556130-b3024a13-0c10-4657-9b0c-e1a210559455.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by mariomakter** [comment]
@palisadoes please assign me for PR request

**Comment by Biki-das** [comment]
@mariomakter 
https://github.com/PalisadoesFoundation/talawa-docs/issues/328

We don't want any search feature as of now!
I think you can close this, Issue like this create noise and eventually makes it harder for the maintainer to work with !

**Comment by mariomakter** [comment]
> @mariomakter #328
> 
> We don't want any search feature as of now! I think you can close this, Issue like this create noise and eventually makes it harder for the maintainer to work with !

but navbar we should navbar border distinguish by other section

**Comment by palisadoes** [comment]
We are focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
