### ISSUE TITLE
Bug Report: Desired Feature Pages Need to be Consolidated & Updated

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa-docs#547]
**Describe the bug**
Our desired feature pages are out-of-date, and for simplicity of future tracking, need to be consolidated. 

We need the following:
1) Desired Features to be consolidated to be all on one page
2) Other desired feature pages deleted
3)The content on the single desired features page to be completely up-to-date with Talawa's current state

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by salman-farooqi** [comment]
I would like to work on this, but if you please can give a little explanation. Thank you!

**Comment by Ujjwal990** [comment]
@Cioppolo14  I would like to complete this task if you can please assign it to me. I understood the issue and will start working on it as soon as you assign it to me.
I think the **caution:** message needs to be removed and all the desired features pages should be on one single page for convenience and less cluttering.

**Comment by salman-farooqi** [comment]
I would like to work on this, but if you please can give a little explanation. Thank you!
![Capture](https://user-images.githubusercontent.com/127323880/226616030-39775558-5481-40af-94d3-1d0fcd64855a.JPG)

**Comment by salman-farooqi** [comment]
I would like to work on this, but if you please can give a little explanation. Thank you!

![Capture](https://user-images.githubusercontent.com/127323880/226616183-2b4e5b77-85e8-4b6f-9b17-81f5bfa3911b.JPG)
What I understood is that:
1. The 'Desired Features' main menu should just have sub-menus i.e Admin Portal, Admin Capabilities, Chat and Messaging etc.
2. These sub-menus should not have more sub-menus inside them, and the content should be just on one page.
3. The links to the Sub-menus in the 'Introduction Menu' is already there which are useful, so this 'Introduction' page should not be removed.

I can do the further changes if required.

**Comment by salman-farooqi** [comment]
> I would like to work on this, but if you please can give a little explanation. Thank you!

![Capture](https://user-images.githubusercontent.com/127323880/226618780-b1f4a7d4-9010-45b2-adb3-6c4394b67d55.JPG)


What I understood is that:

   1. The 'Desired Features' main menu should just have sub-menus i.e Admin Portal, Admin Capabilities, Chat and Messaging etc.
   2. These sub-menus should not have more sub-menus inside them, and the content should be just on one page.
   3. The links to the Sub-menus in the 'Introduction Menu' is already there which are useful, so this 'Introduction' page should not be removed, but when we click on the "Click here to know more" link, it opens in new tab, I think it'll be good if takes the user to the details of the desired feature but remain in the same page.

I can do the further changes if required.

**Comment by salman-farooqi** [comment]
Please need a little assistance @palisadoes @Cioppolo14 
 
 1. What should I do about features like these where the authors' names and dates are mentioned, there is no content in them, should I remove them, if you say I don't have to remove it, where should I find the content for it to write in these sub-menus? (OR) I search and write content by myself?

 2. And also what about, warning 'caution' section?

 3. How can I be completely up-to-date with Talawa's current state? How can I know which parts/features are not operational any more?

![caution](https://user-images.githubusercontent.com/127323880/227213156-619e8b19-f82a-40e4-8916-110319b485c9.JPG)

**Comment by salman-farooqi** [comment]
![desired features](https://user-images.githubusercontent.com/127323880/227361736-9944b42d-b39e-478a-a29e-fdf1c8aa18ee.JPG)

I've simplified the 'Desired Features' by removing the sub-menus and gathered its content on single pages. But, the content inside them is not up-to-date, if you guide me on that please!

**Comment by salman-farooqi** [comment]
@palisadoes @Cioppolo14 @DMills27 @noman2002 @xoldyckk I need your guidance on this.

**Comment by salman-farooqi** [comment]
> 



> **Describe the bug** Our desired feature pages are out-of-date, and for simplicity of future tracking, need to be consolidated.
> 
> We need the following:
> 
> 1. Desired Features to be consolidated to be all on one page
> 2. Other desired feature pages deleted
>    3)The content on the single desired features page to be completely up-to-date with Talawa's current state
> 
> **Potential internship candidates** Please read this if you are planning to apply for a Palisadoes Foundation internship [PalisadoesFoundation/talawa#359](https://github.com/PalisadoesFoundation/talawa/issues/359)

1. There are 11 Desired Features (with sub-menus inside them) and in my opinion it cannot be collected/merged into one single page, as it will be time consuming for users to scroll down all the way to the end of the page to see all the features.
2. I have consolidated each Desired Feature's sub-menus to one single page as can be seen in picture above https://github.com/PalisadoesFoundation/talawa-docs/issues/547#issuecomment-1481917871.
3. But I need help/guidance to decide which of the Desired Feature is currently up-to-date with Talawa, and which one need to be removed?

**Comment by palisadoes** [comment]
Thanks, but we cannot guide you unless you do a PR where we can see what you have done. Please submit a PR for review.
