### ISSUE TITLE
Pricing page is missing

### ISSUE THREAD

**Issue by yeahChibyke** [PalisadoesFoundation/talawa-docs#554]
Description:
A pricing page helps customers understand the different tiers of pricing the product has. The fact that it is missing would create confusion for potential customers.

Solution:
I would like to work on creating a pricing page (or work with anyone -designer and/or dev- who is already working on this). 

Approach:
Seeing as the talawa-docs is built using docusaurus, I can also use it to build a pricing page as far as I am provided with necessary media and guidance. I would love to be assigned to this.

**Comment by palisadoes** [comment]
The product is not for sale. It is open source. Closing
