### ISSUE TITLE
Powerful Story-telling for the Talawa Project

### ISSUE THREAD

**Issue by yeahChibyke** [PalisadoesFoundation/talawa-docs#556]
Description:
The description of Talawa on the website is quite generic. I propose using powerful storytelling to describe Talawa.
That would mean having a standalone page as it is currently being described in relation to The Palisadoes Foundation (which already has its own website).
![chrome_Dsv0KxyICK](https://user-images.githubusercontent.com/56419077/227009128-60f2bad5-7bad-4402-9bfc-45bdd05559f5.png)

Solution:
I have researched existing similar products and I have noticed their use of powerful storytelling to describe their product concisely.
I will study Talawa intensively and come up with a write-up which is both interesting and attention-catching, whilst being technical enough, to tell the Talawa story. 
Similar to [SportMember](https://www.sportmember.com/) did on their site as can be seen in the following screenshots.
![chrome_dXmfUTmjLO](https://user-images.githubusercontent.com/56419077/227011411-40f66989-a2ee-4583-8519-978df6685b6f.png)
![chrome_he2ZCpAtCA](https://user-images.githubusercontent.com/56419077/227011418-6c159918-3f48-4d6a-a84c-32f353949ffb.png)
![chrome_rjOBLakR4X](https://user-images.githubusercontent.com/56419077/227011434-e6db5392-d311-4ccf-be82-3e2294357693.png)

Perhaps, a tag (with its link preferably in the footer) can be created that tells the story of Talawa from the perspective of its mission, vision, history, etc. This tag could be named 'About Us'

Alternative Approach:
Since pictures are worth a thousand words, then the right video is worth a million.
A video could be created that explains what Talawa does concisely and posted in a section on the homepage.
[SportMember](https://www.sportmember.com/) did something similar on their homepage.
![chrome_hRr7R3ByBO](https://user-images.githubusercontent.com/56419077/227012999-96e2fc47-065a-4761-a198-971e0d723107.png)

If I am assigned to this task, I would begin work immediately acting on the directives and guidance of the mentors.

**Comment by Cioppolo14** [comment]
@gODcodes97 This has potential. Please follow this thread about our new page design, while developing this: https://github.com/PalisadoesFoundation/talawa-admin/issues/759

**Comment by yeahChibyke** [comment]
Ok. I will get on it immediately

**Comment by palisadoes** [comment]
This is a duplicate issue. 

- https://github.com/PalisadoesFoundation/talawa-docs/issues/344

We hope to have an updated site soon. Please add your comments there. The major design elements are being worked on. 

Closing.
