### ISSUE TITLE
Bug Report : Font size is blur and very small if used on tablets

### ISSUE THREAD

**Issue by Keegan-20** [PalisadoesFoundation/talawa-docs#558]
**Describe the bug**
i was checking responsivness of the document and found that the font-size is very small on tablet mode thus making it unreadable.

**Expected behavior**
the text should will be visible clearly so that users can read it over all devices.

**Actual behavior**
text is too small and blury on tablet devices

**Screenshots**
![talwa1](https://user-images.githubusercontent.com/97297724/227128582-70cb9ace-e1e5-46ea-a603-f6ee3f05ed6a.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Keegan-20** [comment]
i would like to work on this issue

**Comment by Cioppolo14** [comment]
@Keegan-20 Thank you for your submission. We are in the process of switching website designs, and I believe this will be affected, so I don't want to put resources into right now.  We are focusing content as much as possible.  Please keep the ideas coming!

**Comment by Keegan-20** [comment]
Yh that's okay. Would love to work on other issues in future
