### ISSUE TITLE
Feature Request : Creating a custom scrollbar for talwa docs

### ISSUE THREAD

**Issue by Keegan-20** [PalisadoesFoundation/talawa-docs#559]
**Is your feature request related to a problem? Please describe.**
How about creating a custom scrollbar  rather than default windows scrollbar ?

**Describe the solution you'd like**
we can create a custom scrollbar for both dark and light mode  like  for   - light mode we can keep the t**humb color** of scroll bar to **lite green** (the background color which is set for h1 header of talwa documentation) and  **TRACK COLOR:#ffff.**

**Dark mode -**
thum color: Teal
track color:black

**Additional context**
I think if we create the custom scrollbar it will enhance the overall Ui of the website thus improving user Experience rather than baic default windows scrollbar.

**Comment by Keegan-20** [comment]
I would like to work on this issue, Please assign it to me

**Comment by tasmeomeem** [comment]
can i fix it?

**Comment by palisadoes** [comment]
This is not a required feature. We have declined adding it multiple times in the past. Closing.

Thanks for considering it.
