### ISSUE TITLE
Same code files in the 'Functionalities' and Talawa-Admin's plugin folder

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#563]
**Is your feature request related to a problem? Please describe.**
There are 3 files namely:
1. implementing-plugins-example.md
2. implementing-plugins.md
3. plugin-architecture.md

in both 'docs/developers/talawa-admin/plugins' and 'docs/functionalities' folder.
These files in the functionalities are not referenced in the 'sidebars.js' file either, and aren't being used anywhere

**Describe the solution you'd like**
I would like to delete these redundant files as the content is the same, and go through all the files to link the files of 'plugin' folder, rather than the functionalities folder, for ease of editing and maintenance.

**Additional context**
![image](https://user-images.githubusercontent.com/97171261/227225217-14105023-1b62-446c-a08a-4babf48907a7.png)
![image](https://user-images.githubusercontent.com/97171261/227225334-b94b7a49-fbf7-4824-aa67-6a303f688b39.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
With ref to our conversation in #540

**Comment by faveee** [comment]
Can this be assigned to me?

**Comment by Nitya-Pasrija** [comment]
Hey @faveee 
I have already did the work beforehand for this issue, before creating the issue.. sorry, but can I planned to create the PR, after it gets assigned

**Comment by faveee** [comment]
@Nitya-Pasrija Yeah I noticed. Since the initial issue contained a list of bugs, I thought it would be assigned to a new person. It’s fine. Well done.

**Comment by Cioppolo14** [comment]
@palisadoes Can you weigh in on this issue?

**Comment by Nitya-Pasrija** [comment]
@palisadoes @Cioppolo14 
Should I close this issue?
