### ISSUE TITLE
Moving Dark/light mode button and github icon in main navbar  in responsive mode. 

### ISSUE THREAD

**Issue by Keegan-20** [PalisadoesFoundation/talawa-docs#565]
**Describe the bug**
Moving the dark/light mode button and GitHub icon from sidebar (hamburger)menu to main navigation bar.

Initially,Users usally don't interact much  with sidebar menu  when they first land on a website moving the icon and button  besides the logo would improve user experience as they get ,Call To Action option instantly in responsive mode. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
![Screenshot_2023-03-24-10-08-29-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/97297724/227427301-e064d7c0-bf06-4152-b89a-40fc9526febc.jpg)

**Comment by Keegan-20** [comment]
Please assign me this issue

**Comment by steno1** [comment]
Can this issue be assigned to me?

**Comment by Cioppolo14** [comment]
Thank you for your submission. 
 
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

I am going to close this, as it does not fall under our focuses right now.
