### ISSUE TITLE
Bug Report: Fix Header Text Styling To Give A Clear Hierarchy

### ISSUE THREAD

**Issue by Ugboaja-Uchechi** [PalisadoesFoundation/talawa-docs#566]
**Describe the bug**
- There are some minor styling issues concerning some `h2` text that takes up a lot of space and are as large as some `h1` text on mobile and desktop view.

**To Reproduce**

1. From the landing page go to talwa docs by clicking on the "Get Started" button
2. While going through different pages in the sidebar this styling issue can be noticed

**Expected behavior**
A clear hierarchy of different headers to make it easier for users to differentiate different headings.

**Screenshots**
![image](https://user-images.githubusercontent.com/74814780/224823505-2fef5bbb-ff29-4e10-9de2-e7d2fe5a764a.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ugboaja-Uchechi** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
Please change the title of this issue so that it will be more easily searchable.

**Comment by Ugboaja-Uchechi** [comment]
I just updated it.

**Comment by steno1** [comment]
Please can I work on this issue?

**Comment by Cioppolo14** [comment]
@Ugboaja-Uchechi Please remove the second bullet regarding the page break issue, lets focus on fixing the header style relationships.

**Comment by Cioppolo14** [comment]
We've reorganized the webpage and expect significant changes to formatting soon, so I am going to close this issue as not currently planned. I apologize for the change.
