### ISSUE TITLE
Add policy page on Talawa-API GraphQL resolver design

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#568]
**Is your feature request related to a problem? Please describe.**
We need to add a page under the Talawa-API developers section on how we design our GraphQL resolvers. The conversation here needs to be converted into a Talawa-API policy.

- https://github.com/PalisadoesFoundation/talawa-api/discussions/1209

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**

None

**Approach to be followed (optional)**
See above

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@EshaanAgg @xoldyckk Please take a look

**Comment by EshaanAgg** [comment]
@palisadoes
The linked discussion is quiet specific to only cursor based pagination resolvers.

As I see it, we can create a general page highlighting some common design principles, and in it we can add a specific section about the cursor pagination. 

I can start working on it as soon as [#1187](https://github.com/PalisadoesFoundation/talawa-api/pull/1187) is merged in Talawa API, taking it as a basis for good practices.

**Comment by palisadoes** [comment]
I created a design guide page that we can use as a starting point. 

- https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/developers/talawa-api/design-guide.md

**Comment by kb-0311** [comment]
@palisadoes @EshaanAgg is correct that the discussion is specific to how we model the API for connections, not the complete industry-standard graphql design practices.

I had mentioned in my GSoC proposal how we would be going about making sure that graphql API in talawa-api is up to production standards by making sure the API design follows all practices here ->

https://graphql.org/learn/best-practices/

@EshaanAgg would you like to pass this issue to me? I will create a general standard API design doc then you can take care of documenting the connections resolvers part. That would be a lot better as I already have code snippets ready about this the how we can get rid of the antipattern nature of graphql in talawa-api

**Comment by EshaanAgg** [comment]
Sure @kb-0311. You can tag me once the general document is ready, and I'll then complete the pagination part. 

Unassigning myself. @palisadoes please assign @kb-0311 for now.

**Comment by palisadoes** [comment]
Any updates on this?

**Comment by kb-0311** [comment]
@palisadoes yeah working on the error policy currently as soon as it has been done and merged will complete this one too.
