### ISSUE TITLE
presence of word wrap and copy container for plain text in talawa api > base constraint >admin

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#570]
**Describe the bug**
there is a word wrap and copy container to handle plain text which is not relevant to the residing content

**Expected behavior**
it should be treated as normal content.

**Actual behavior**
plain text is present inside 

**Screenshots**
![admin role](https://user-images.githubusercontent.com/39475669/227595203-25bd5f3d-2f94-40e4-8de4-afc868f6d538.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
can i be assigned to this ?

**Comment by Cioppolo14** [comment]
@lonereaper Can you brainstorm what we could add here? We also have SuperAdmin role, maybe that should be discussed here as well.

**Comment by SalilHarit** [comment]
> @lonereaper Can you brainstorm what we could add here? We also have SuperAdmin role, maybe that should be discussed here as well.

sure ! we can add the admin capabilities a little more descriptively and distinctly such as 

1.Add/ remove members from organisation
2.Elevate/remove users to/from coordinator
3.Create/Delete group chats
4.Create/Delete events
5.admin can manage/exit multiple organisations
6.admin can message everyone at once in an organization/s
7.admin can moderate newsfeed
 i.admin can delete post/s (at one time)
ii.admin can enable/disable comments
iii.admin can archive posts 
iv.admin can hide likes from a post
v.admin can manage sharing limits of a post/event
8.admin can ban/unban user from organisation (with a documented reason)

SuperAdmin Roles

1.they can do what admin can do but with higher access rights than admin
2.they can add/remove admin's access to certain feature/s organization/s
3.they can remove/ban admins
4.they can report admins
5.they can remove and moderate organizations
6.they can ban/unban admin from organisation or in general (with a documented reason)

**Comment by SalilHarit** [comment]
And we can add admin and super admin model as well if it is not sensitive information
