### ISSUE TITLE
Bug Report: Custom css style border related problem(talawa docs)

### ISSUE THREAD

**Issue by mariomakter** [PalisadoesFoundation/talawa-docs#571]
**Describe the bug**
CSS Borders refers to the line outside the padding and inside the margin of the CSS Box Model. This line wraps around the padding and content in every HTML Element. That is both semantic and non-semantic elements.
Borderlines don’t have to be a solid straight line. We can apply different styles to it to change its looks and feel, as you will see as we learn more about it in this blog on CSS Borders.
here border style is blur .Its not visible .It's not user friendly

Understanding how to use CSS Borders can improve our work with web elements.

**To Reproduce**

1.navbar border style add
2.Docs sidebar border add
3.colllapse sidebar button border add
4.docMainContainer_gTbr ->table-of-contents table-of-contents__left-border ->border add

**Excepted behavior**
This diagram describes each section separately. I think this interface is user friendly
**Screenshots**
![image](https://user-images.githubusercontent.com/102503970/227609903-55283a11-88af-41c6-905e-e185e42bc3fc.png)
![image](https://user-images.githubusercontent.com/102503970/227609984-cb1d5ff0-97ca-4951-8fa4-fc3c8c9c9978.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/102503970/227612228-11d1e766-b38b-4cd7-a970-8510daccac8d.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by mariomakter** [comment]
@Cioppolo14  please assign me this work?

**Comment by Hajihbola** [comment]
@Cioppolo14 can I have this issue assigned to me please?

**Comment by steno1** [comment]
Please can I have this issue assigned to me?

**Comment by palisadoes** [comment]
We really need to get contributions that improve the content on the page to make them useable for the developers and end users.

Closing
