### ISSUE TITLE
Feature Request: 1. Adding code line-numbers to code-blocks  2. Keyword colour change

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#573]
**Is your feature request related to a problem? Please describe.**
My plan is to enhance the code block in the dark mode by adding code lines and modifying the color of the keywords. This adjustment will reduce distractions and improve the code block's readability.

**Additional context**
1. Adding code line-numbers to code-blocks 
It would look something like this:
![image](https://user-images.githubusercontent.com/97171261/227725253-9191c988-88cc-4d23-934d-067e3fa3dfe5.png)
![image](https://user-images.githubusercontent.com/97171261/227725265-c8c3f812-e369-4c67-8a4e-d64048c9ac23.png)

And wouldn't cause a problem while selecting the code:
![image](https://user-images.githubusercontent.com/97171261/227725283-ae276ed5-db5b-43dd-8c67-6280b45087c0.png)
-------------------------------------

2. The keywords would like this:
![image](https://user-images.githubusercontent.com/97171261/227725556-25fb68a5-b57c-4b35-8828-709f707eb929.png)
Instead of:
![image](https://user-images.githubusercontent.com/97171261/227725467-388afd2e-0e8a-4bb3-925d-b50dbedcefc7.png)
This would also retain the color in the light mode:
![image](https://user-images.githubusercontent.com/97171261/227725496-5531aa8f-202e-42f5-a4b3-3b9ff70db960.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 @palisadoes

**Comment by mariomakter** [comment]
@Nitya-Pasrija I would like to work on this issue. please chance me one PR create

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by Nitya-Pasrija** [comment]
Thank you for letting me know. I will keep the pointers in mind.
