### ISSUE TITLE
Re-designing, Making changes on Home Page & About Page

### ISSUE THREAD

**Issue by sumyat-aung** [PalisadoesFoundation/talawa-docs#576]
**I would like to request a re-design of the home page with the following suggestions:**

- **Decrease the number of Background Colors: There are currently three different background colors on the same page, which can be confusing for the user. I suggest decreasing the number of background colors to create a more cohesive and user-friendly design. (The current primary background color for the hero section is green, I suggest changing it to be the same as the Homepage feature section)** 

- **Add Modern Hover Animation to 'Get Started' Button: The 'Get started' button can be improved by adding a modern hover light animation to make it more interactive and engaging. This animation can be a subtle movement effect that appears when the user hovers over the button.**

- **Gradient for Homepage Feature Section: The 3 features box in the Homepage feature section should have some gradient to make them more visually appealing and modern. The gradient should be adjusted to fit the overall design of the page.**

![image](https://user-images.githubusercontent.com/108873224/227748575-818fe996-5e49-4231-a55f-2c67eaa03eaa.png)

<br />

- **Add Mini Border to Light Mode Sidebar: The sidebar and main page are currently divided by a mini border in dark mode, but this is not present in light mode. I suggest adding this mini border to the light mode as well to create consistency and improve the visual appeal.**

![image](https://user-images.githubusercontent.com/108873224/227748527-147b8ca9-72bd-45dc-9260-705c8e5c5b23.png)

![image](https://user-images.githubusercontent.com/108873224/227748681-5288cea5-4ba6-4427-8ff3-2b60992fc78b.png)

**Comment by sumyat-aung** [comment]
@DMills27 

I would like to work on the issue.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
