### ISSUE TITLE
Bug Report:- Broken Link on the Talawa admin plugin architecture Page

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#579]
**Describe the bug**
Two link to the talawa mobile app  page  and talawa admin app are broken, this needs to be fixed

**To Reproduce**

1. Go to the Talawa plugin architecture Page
2. Click on the Talawa mobile app link and Talawa admin app
3. This will direct to broken Page

**Expected behavior**
This should redirect to the corresponding Page

**Actual behavior**
This redirects to Broken Page
**Screenshots**

https://user-images.githubusercontent.com/72331432/227757515-68a1c757-e7db-4c88-bacc-607a180a6c73.mp4

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
The correct URL has been provided. Closing.

**Comment by palisadoes** [comment]
The URL was made private. We uploaded a public version.

**Comment by Biki-das** [comment]
> The correct URL has been provided. Closing.

@palisadoes  where it is provided?, currently it is broken!
