### ISSUE TITLE
Improving the Clarity and Organization of the Schema Page in the Documentation

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#580]
**Describe the bug**
The Schema page in the documentation is cluttered with excessive code, which makes it difficult to comprehend. Furthermore, the page lacks clear differentiation between different code topics, and the titles and descriptions are repetitive and indistinguishable from each other.

**Expected behavior**
The readability of the Schema page is problematic, as some examples and argument explanations are inconsistent, which makes it hard to understand. For instance, the 'skip' and 'first' arguments could have used the same integer value, as that of the example snippet. 
![image](https://user-images.githubusercontent.com/97171261/227763597-d714b0ee-73f8-4595-9c46-b79608178d10.png)

Moreover, the page is quite complex, with three different categories of queries, subscriptions, and mutations, which can be overwhelming.

**Actual behavior**
The website page lacks clear separation between different code topics, making it feel endless and confusing. My aim is to introduce a differentiated structure pattern to present the code. To achieve this, I plan to use inline comments and incorporate a dummy code structure followed by relevant example code. Additionally, I will include a suitable description with return types and arguments, to offer clear differentiation between different query commands.

**Additional details**
For instance, the following section could be redesigned as follows:
BEFORE
![image](https://user-images.githubusercontent.com/97171261/227763782-8d819697-f1c3-4909-9cce-6a9083ac8c4a.png)

AFTER
![image](https://user-images.githubusercontent.com/97171261/227764479-021a13e1-734c-4321-a91b-3cd702504156.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
Can I be assigned to this?

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija Thank you for your submission! We have created special issues to update the look and feel of these automated updates in these issues below. We need to close this issue as it is a duplicate.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/199
- https://github.com/PalisadoesFoundation/talawa-docs/issues/200

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 

These are documentation changes though. I plan to edit the description, and examples to put them in sync as well.
