### ISSUE TITLE
1. Using Text Instead of Email JPEGs for Better Usability 2. Scroll Navbar for Enhanced Space Management in Smaller Devices

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#586]
**Describe the bug**
I suggest converting the mails imgs to text format to make it easier for viewers to copy the emails. Currently, they have to switch back to see the email, which can be inconvenient. Additionally, I propose hiding the navbar on down scroll and making it reappear on scrolling up, to improve the user experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/97171261/227788334-4a3f48c2-bd61-4106-89fa-52ef47713dbe.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Duplicate. 

- https://github.com/PalisadoesFoundation/talawa-docs/issues/497
- https://github.com/PalisadoesFoundation/talawa-docs/issues/366
- https://github.com/PalisadoesFoundation/talawa-docs/issues/235

Please search the closed issues to see whether your issue has already been addressed. 

Closing

**Comment by Nitya-Pasrija** [comment]
I apologize for any inconvenience caused by not checking the closed issues before submitting my query. Going forward, I will make sure to check the existing issues before posting to avoid such oversights.

**Comment by Nitya-Pasrija** [comment]
@palisadoes
Should we proceed with the implementation of a scrollable navbar to provide mobile application users with more screen space though?

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by palisadoes** [comment]
Also we need to one issue per problem discovered. It makes tracking easier.

**Comment by Nitya-Pasrija** [comment]
Alright, I will keep this in mind. Should I create a separate issue for the navbar issue thou?
