### ISSUE TITLE
Bug repport: Footer items not centered and need redesign

### ISSUE THREAD

**Issue by sarazaToussaint** [PalisadoesFoundation/talawa-docs#587]
#### Describe the bug

The footer items on the Talawa-docs website are currently not centered on the mobile version, and the design needs to be updated. Currently, the footer items are aligned to the left side of the page, which looks unprofessional and affects the overall user experience. I would like the footer items to be centered on the page, with a more modern and visually appealing design. I have attached a screenshot of the current footer design for reference.
![talawa](https://user-images.githubusercontent.com/34794815/227810060-4b247461-b440-4a6b-8568-e502bfb94805.png)

**Comment by sarazaToussaint** [comment]
@Cioppolo14 I would like to complete this task if you can please assign it to me. I can start working on it as soon as you assign it to me.

**Comment by Cioppolo14** [comment]
Thank you for your submission.  

We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting issues focused on significantly improving the content of the pages right now.  We are working on  a significant webpage layout change, so we are not making any more changes in that area. 

I am going to close this issue.
