### ISSUE TITLE
Creating a separate Sidebar for the Talawa API docs

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#596]
**Describe the bug**
With the use of a separate sidebar reserved only for the Talawa API documents folder, the Talawa API would be quickly available when opened.

**Expected behavior**
There is currently no way to go to different topics other than returning to the pages you were on; adding a sidebar independent of the Talawa documentation would be beneficial.
![image](https://user-images.githubusercontent.com/97171261/229045129-22864174-bd23-432d-8e01-d22d363dc620.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14

**Comment by Nitya-Pasrija** [comment]
@palisadoes @Cioppolo14 @noman2002

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija I apologize for the delay, we are thinking on this.  I will get back to you soon.

**Comment by Cioppolo14** [comment]
@tasneemkoushar @anwersayeed @evasharma12   Could you look at this issue?

**Comment by Biki-das** [comment]
@Nitya-Pasrija the talawa API is not a part of the docusuaurus page, the docs are just generated and served at real time .

**Comment by saiteja13427** [comment]
@Nitya-Pasrija @Cioppolo14 Can I take up this issue?

**Comment by palisadoes** [comment]
Assigning to @Nitya-Pasrija as she'll be doing the redesign of the site during the summer.
