### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#600]
**Is your feature request related to a problem? Please describe.**
Currently the slack in the footer is linked to https://github.com/PalisadoesFoundation/talawa#readme

**Describe the solution you'd like**
It should be directly linked with the slack invitation page.

**Approach to be followed (optional)**
Linking it with https://thepalisadoes-dyb6419.slack.com/join/shared_invite/zt-1s3fehykg-n2wfvgapdRxMakOQs~U7PA#/shared-invite/email

Please assign me this. @noman2002 @DMills27 @tasneemkoushar @JamaicanFriedChicken

**Comment by palisadoes** [comment]
The slack link changes every 30 days. We have to update it manually, therefore we put it in one place where any contributor can edit it when it expires. Closing
