### ISSUE TITLE
UI Improvement#1

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#601]
**Is your feature request related to a problem? Please describe.**
In https://docs.talawa.io/talawa/index.html   the picture logo near [N|Solid](https://github.com/PalisadoesFoundation/talawa) and [Build Status](http://www.palisadoes.org/) needs improvement.

![Screenshot 2023-03-29 223023](https://user-images.githubusercontent.com/97789856/228613618-9375f49b-ce5e-4e5e-b8e7-b41804c2e464.jpg)

**Describe the solution you'd like**
Making it visible. 

Please assign me this @DMills27 @noman2002

**Comment by salman-farooqi** [comment]
Duplicate https://github.com/PalisadoesFoundation/talawa-docs/issues/404
