### ISSUE TITLE
UI Improvement#2

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#602]
**Is your feature request related to a problem? Please describe.**
The talawa mobile site does not follow the branding colours of talawa.

**Describe the solution you'd like**
Transforming the UI of talawa mobile site according to colour code of talawa and palisadoes foundation.

Please assign me this.

**Comment by palisadoes** [comment]
The Talawa-mobile UX is not handled in this repo. Closing
