### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#603]
**Describe the bug**
[501(c)(3) organization](http://www.irs.gov/charities/charitable/article/0,,id=96099,00.html) link broken in Contact us page.

**Screenshots**
![Screenshot 2023-03-29 223808](https://user-images.githubusercontent.com/97789856/228615668-7904dc5d-faea-4ec9-bff3-2d101244d945.jpg)

Will solve this issue if you assign me this.

**Comment by palisadoes** [comment]
This is not a link on the Talawa docs site. Closing.
