### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#604]
**Is your feature request related to a problem? Please describe.**
The header of Contact us page contains GSOC Section but not Outreachy section.
![Screenshot 2023-03-29 224118](https://user-images.githubusercontent.com/97789856/228616373-bf287f0e-3afc-4209-bc8b-9843ae9a48ae.jpg)

**Describe the solution you'd like**
Adding Outreachy Section in the header section of Contact us page.

Please assign me this.

**Comment by palisadoes** [comment]
This is not a site handled by the talawa-docs repository or website. closing
