### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by neelimagoogly** [PalisadoesFoundation/talawa-docs#605]
**Describe the bug**
The 'click here to know more' link at introduction page of desired features page is broken.

**Expected behavior**
Should work properly.

**Screenshots**
![Screenshot 2023-03-29 224731](https://user-images.githubusercontent.com/97789856/228617397-69be1d08-10af-4011-8854-3574674f61bd.jpg)

Please assign me to fix this.

**Comment by palisadoes** [comment]
Closing. There is no link as to what you are talking about. 

No paliadoes.org website pages are handled in Talawa-docs.
