### ISSUE TITLE
Requirements Docs/Desired features does not havethe correct title indentation.

### ISSUE THREAD

**Issue by VictoriaAde** [PalisadoesFoundation/talawa-docs#611]
**Describe the bug**
Talawa-Docs: the pages under Requirements Docs/Desired features were recently consolidated and 
this has resulted in the pages not having the correct title indentations.
As the menu on the left does not change nor show the user that they are scrolling.

**To Reproduce**
Go to this URL and scroll, notice that it is hard to identify which feature you are on from the table of contents on the left-hand menu

**Screenshots**
![image](https://user-images.githubusercontent.com/60205816/228956106-da40e88e-347d-46a6-a1c8-652e6a9b8be2.png)

**Comment by palisadoes** [comment]
The left hand side menus are sufficient and must not be modified. The right hand side menus need to make the content clearer.

In this example https://docs.talawa.io/docs/features/admin-role there are four different features mentioned and it is hard to individually identify them as many of the titles are at the same level.

![image](https://user-images.githubusercontent.com/16875803/228974466-d8c1bf57-bad5-4975-9f0f-67f8683c8d43.png)

**Comment by salman-farooqi** [comment]
> The left hand side menus are sufficient and must not be modified. The right hand side menus need to make the content clearer.
> 
> In this example https://docs.talawa.io/docs/features/admin-role there are four different features mentioned and it is hard to individually identify them as many of the titles are at the same level.
> 
> ![image](https://user-images.githubusercontent.com/16875803/228974466-d8c1bf57-bad5-4975-9f0f-67f8683c8d43.png)

@palisadoes Yes, I would have done that as well in my PR for 'Consolidation of Desired Features', but I needed permission to make changes and how to change the content. If I'm given hints, I can still do it. But for that I have to know which feature need to be removed, and to decide which feature is up-to-date with Talawa?
Or should I go through and study the whole website to do that?

**Comment by salman-farooqi** [comment]
I can do that as well if allowed. I will go though all the documentation and find relative information. And also, I'll check any typos, errors etc. And if found any ideas and suggestions for improvement, will discuss that too.
And I would love to continue with Palisadoes after the contribution period ended, because it'll keep me motivated for learning.
I've learned so much since March 6 that I can't imagine, so it's a source of learning and experiencing the outside world for me.
I didn't imagine that learning can be so fast, easy, and excited at the same time at the competitive levels. Thank you for the opportunity @palisadoes 🙌

**Comment by palisadoes** [comment]
1. Let's give @VictoriaAde an opportunity to respond to see whether she wants to be assigned this issue. 
2. She created the issue and as a newcomer should be given an opportunity to participate.

**Comment by VictoriaAde** [comment]
Thank you @palisadoes 
I would love to be assigned the issue.

**Comment by Cioppolo14** [comment]
@VictoriaAde Thank you! Please make sure to focus on the request in palisadoes comment above, regarding the indentation for the right menus. The left menus we'd like to leave alone.

**Comment by VictoriaAde** [comment]
> @VictoriaAde Thank you! Please make sure to focus on the request in palisadoes comment above, regarding the indentation for the right menus. The left menus we'd like to leave alone.

Okay @Cioppolo14, I will focus on fixing the indentation for the right menus.
Thank you.

**Comment by palisadoes** [comment]
@VictoriaAde The expectation was that the markdown files would be adjusted so that the H1, H2, H3, H4 titles would be appropriately assigned to the headings to make the table of contents usable.

We are not accepting any more changes to CSS.

**Comment by VictoriaAde** [comment]
@palisadoes, I have been on the code all day looking for a way to adjust the heading on the right menu without CSS. Still, unfortunately, any change I made affects the main content in the middle as that is how [Docusaurus.io](https://docusaurus.io/) has been developed and the only way to make a change to the right menu is through custom CSS.

**Comment by salman-farooqi** [comment]
> @palisadoes, I have been on the code all day looking for a way to adjust the heading on the right menu without CSS. Still, unfortunately, any change I made affects the main content in the middle as that is how [Docusaurus.io](https://docusaurus.io/) has been developed and the only way to make a change to the right menu is through custom CSS.

You'll have to make changes to headings, open the markdown files and change the h2 into h3 you'll see the difference on right side menu

**Comment by VictoriaAde** [comment]
> > @palisadoes, I have been on the code all day looking for a way to adjust the heading on the right menu without CSS. Still, unfortunately, any change I made affects the main content in the middle as that is how [Docusaurus.io](https://docusaurus.io/) has been developed and the only way to make a change to the right menu is through custom CSS.
> 
> You'll have to make changes to headings, open the markdown files and change the h2 into h3 you'll see the difference on right side menu

@salman-farooqi I have done that, it was my first approach but there was no change to the right-side menu.
I went on the [Docusaurus.io](https://docusaurus.io/) official Docs and they recommended the custom CSS approach.

**Comment by salman-farooqi** [comment]
Well as far as I understood the issue, it has to be markdown changes only

**Comment by salman-farooqi** [comment]
I've checked your PR, you just increased the h1 sizes using CSS. On the contrary, you should decrease the size of other headings in markdowns except h1 and see how it works.

**Comment by palisadoes** [comment]
There must be no changes to the CSS. The problem can be solved without doing so by editing the original markdown file

**Comment by VictoriaAde** [comment]
So @palisadoes  I think the reason why editing the original markdown file won't work is that the side menu is originally in` <ul> <li> <a>` tags, so it's not markdown.
You can try inspecting to get what I mean, the class names for the markdown are different from that of the side menu to tell you that it's not markdown.

**Comment by palisadoes** [comment]
It will work because docusaurus converts markdown to HTML. Please research docusaurus and how it does this. All the documentation on the docs.talawa.io site is sourced from markdown file in the `docs/` directory.

**Comment by VictoriaAde** [comment]
Okay @palisadoes, I will do more research on it and get back to you soon.

**Comment by VictoriaAde** [comment]
@palisadoes I have seen how the markdown can be used to improve the right sidebar, however, for the [Admin Capabilities](https://docs.talawa.io/docs/features/admin-role) page I need to know which features need to be removed, and to decide which feature is up-to-date based on the comment made here [Comment](https://github.com/PalisadoesFoundation/talawa-docs/issues/611#issuecomment-1491028233)

**Comment by palisadoes** [comment]
Please fix the headings. We'll work on updating the content later. We'll need the updates to be done to all the pages under features too.

**Comment by VictoriaAde** [comment]
Okay, I am on it.
