### ISSUE TITLE
Adding NavBar hideonscroll Feature

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#614]
**Is your feature request related to a problem? Please describe.**
We should hide the Navbar when the user scrolls down the Page as it helps the user to get a more reading content area, the navbar would again appear up when the user would scroll up thus they can access it as they want

**Describe the solution you'd like**
This would be simple to just add a simple config to the docusaurus, Below are the results

https://user-images.githubusercontent.com/72331432/229360815-b1e901ec-c071-4c06-918a-447ed5142d9d.mp4

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
