### ISSUE TITLE
semi colons at end of sentences 

### ISSUE THREAD

**Issue by SalilHarit** [PalisadoesFoundation/talawa-docs#615]
**Describe the bug**
grammar error

**Screenshots**
![image_2023-04-02_210111222](https://user-images.githubusercontent.com/39475669/229362915-6eec87b0-d3f0-45fb-9ed0-0cdf8a9d2eb6.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SalilHarit** [comment]
can i be assigned to this ?

**Comment by SalilHarit** [comment]
i know this is a low quality issue but its in plain sight on the first page.

**Comment by palisadoes** [comment]
We need to start focusing on upgrading our content. Checks like this can be a part of substantial work on the pages. Closing.

**Comment by SalilHarit** [comment]
> We need to start focusing on upgrading our content. Checks like this can be a part of substantial work on the pages. Closing.

Understood.
