### ISSUE TITLE
Feature Request: Add a project timeline template for the outreachy program on talawa-docs.

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#621]
**Is your feature request related to a problem? Please describe.**
 During the preparation of the final application, participants find it difficult to understand what to add to the project timeline section and a template could help give them a better understanding of what to mention in that section.

**Describe the solution you'd like**
Add a project timeline template for the outreachy program on talawa-docs.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yogita-T** [comment]
Please review and assign this issue to me. Thank you!

**Comment by Cioppolo14** [comment]
Thank you for your submission. We aren't ready to add such a template right now, so I am going to close this.
