### ISSUE TITLE
Feature Request: - Adding A Git guide for contributors

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#624]
**Is your feature request related to a problem? Please describe.**
I Have seen many new contributors facing merge conflict issues, pushing old code etc because they have not added upstream to their local repository which is common for beginners as they are just starting, Mentioning the same forehand can be really helpful to beginner contributors to prevent such issues and thus they can concentrate on contributing.

This evolved from a simple issue to a comprehensive git guide for talawa as suggested by the maintainers!

**Describe the solution you'd like**
Adding an entirely new section for git guide

**Describe alternatives you've considered**
N/A
**Approach to be followed (optional)**
Writing the Guidelines  in the appropriate segment  
Below is the screenshot of what i would like to write
![Our Repositories _ Talawa Project Documentation — Mozilla Firefox 4_5_2023 8_04_25 PM](https://user-images.githubusercontent.com/72331432/230115309-c7c401d8-355a-4192-9a0b-9e2afe6755ad.png)

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to work on this issue!

**Comment by palisadoes** [comment]
This is insufficient. We need a generic guide like this.  
- https://zulip.readthedocs.io/en/latest/git/index.html

It must:
1. Have its own section on the site. 
2. Clearly explain that it's using talawa-docs as a reference but that it would apply to any of our repositories.
3. Show people that we are only accepting PRs to the develop branch of each repository.

**Comment by Biki-das** [comment]
@palisadoes ok let me research on the above and i shall create a new section for the same. thanks for the feedback

**Comment by palisadoes** [comment]
Please work with @Cioppolo14 on this.

**Comment by Biki-das** [comment]
@Cioppolo14 let start with what important things we can include here?

**Comment by palisadoes** [comment]
Source files.
- https://github.com/zulip/zulip/tree/main/docs/git

**Comment by Biki-das** [comment]
@palisadoes  could you assign the issue to me? i have started drafting the initial structure for how the workflow guidelines should be in respect to talawa!

**Comment by palisadoes** [comment]
Please work with @Cioppolo14 on this. Please don't ping me. I've been getting too many interrupts in my day.

**Comment by Biki-das** [comment]
> Please work with @Cioppolo14 on this. Please don't ping me. I've been getting too many interrupts in my day.

sure! sorry for the ping!

**Comment by Cioppolo14** [comment]
@Biki-das I am going to look at this more. Keep me updated with what you have.

**Comment by Biki-das** [comment]
@Cioppolo14 since i am writing this guide we currently do not have a linter for our docs, which does not seem to proivde a good experience for contributors adding the same can be a good step to go forward, looking forward to your thoughts? 

cc @tasneemkoushar

**Comment by Cioppolo14** [comment]
@Biki-das That may be a possibility in the future, and Tasneem would have better input, but first lets get this guide going based on Palisadoes previously mentioned guidelines.

**Comment by Biki-das** [comment]
@Cioppolo14 should i make the git guide inside the developer resources section or it should have a section of its own?

**Comment by Cioppolo14** [comment]
@Biki-das Its own section so it easiest to find.

**Comment by Biki-das** [comment]
> @Biki-das Its own section so it easiest to find.

thanks for the feedback!

**Comment by Biki-das** [comment]
@Cioppolo14 wrote the first quickstart for Talawa 
![Quick start_ how Talawa uses Git and Github _ Talawa Project Documentation — Mozilla Firefox 4_14_2023 9_56_16 AM (1)](https://user-images.githubusercontent.com/72331432/231941675-4243350f-2a14-4197-8284-33f5cac9c689.png)

could you give some feedback?

**Comment by Cioppolo14** [comment]
@Biki-das It looks like a good format for the quickstart page. I think the first two sentences can be combined (the word detailed can be removed, this is a quickstart, not the detailed version), and there are several typos throughout that need to be fixed.  Please change good luck to "Thank you!".  Also, I think we should add a final bullet containing some details about how we handles PRs based on our available volunteers.  Something that says, "We are a small non-profit with limited volunteer resources.  We have the following rules in place for PRs to ensure we can manage Talawa's GITHUB repos as efficently as possible: 
- Please ensure your PR passes all tests and there are no merge conflicts.
- Please do not submit draft PRs.
- Read our CONTRIBUTING.md file. Most importantly:

PRs with issues not assigned to you will be closed by the reviewer
Fix the first comment in the PR so that each issue listed automatically closes.

**Comment by Biki-das** [comment]
> @Biki-das It looks like a good format for the quickstart page. I think the first two sentences can be combined (the word detailed can be removed, this is a quickstart, not the detailed version), and there are several typos throughout that need to be fixed. Please change good luck to "Thank you!". Also, I think we should add a final bullet containing some details about how we handles PRs based on our available volunteers. Something that says, "We are a small non-profit with limited volunteer resources. We have the following rules in place for PRs to ensure we can manage Talawa's GITHUB repos as efficently as possible:
> 
>     * Please ensure your PR passes all tests and there are no merge conflicts.
> 
>     * Please do not submit draft PRs.
> 
>     * Read our CONTRIBUTING.md file. Most importantly:
> 
> 
> PRs with issues not assigned to you will be closed by the reviewer Fix the first comment in the PR so that each issue listed automatically closes.

thanks for this detailed review! yes i was thinking of adding these rules.

**Comment by Biki-das** [comment]
@Cioppolo14 i have updated the quick start and made changes as you said, here are the changes, i think this is enough for the quick start part, i am currently now writing the guide for setting up git in local machine-
![Quick start_ how Talawa uses Git and Github _ Talawa Project Documentation — Mozilla Firefox 4_15_2023 11_22_24 AM](https://user-images.githubusercontent.com/72331432/232187222-3f45a6f7-2d7c-4f6d-9e8a-2f6c24dd78cc.png)
![Quick start_ how Talawa uses Git and Github _ Talawa Project Documentation — Mozilla Firefox 4_15_2023 11_22_34 AM](https://user-images.githubusercontent.com/72331432/232187223-4ac99bd5-2452-449a-8a30-18cc024199e6.png)

**Comment by Biki-das** [comment]
@Cioppolo14 i have written the guide for getting the code could you give some feebdack?
![Get Talawa code _ Talawa Project Documentation — Mozilla Firefox 4_16_2023 11_54_40 PM](https://user-images.githubusercontent.com/72331432/232333783-42ab36e2-82f7-4710-8d7c-b2f311117ce7.png)
![Get Talawa code _ Talawa Project Documentation — Mozilla Firefox 4_16_2023 11_54_50 PM](https://user-images.githubusercontent.com/72331432/232333786-918ea758-7af9-417d-adf5-bc9cded325c4.png)

**Comment by Cioppolo14** [comment]
@Biki-das Thank you.  I have the following comments:
1) Please read through it for grammar and capitalization issues
2) At the beginning, clearly state that this example is for talawa-docs, but can be tweaked by repository name to be used for any Talawa repo.
3) Please redo the examples to be the exact commands for Talawa-Docs.  It might be helpful to finish it with a brief table or blurb about what would be changed for the other talawa repos.

**Comment by Biki-das** [comment]
@Cioppolo14 shouldn't we refer to talawa mobile app setup as the default one and as you said to redo the commands, its exactly similar so i think just stating the same will be followed would be sufficient?

**Comment by Cioppolo14** [comment]
@Biki-das Palisadoes requested it use talawa-docs as the example in the above discussion. I don't think we need to ping them to ask, I think we should just follow their vision.

**Comment by Biki-das** [comment]
> @Biki-das Palisadoes requested it use talawa-docs as the example in the above discussion. I don't think we need to ping them to ask, I think we should just follow their vision.

yeah, lets go with the approach suggested by palisadoes.

**Comment by Biki-das** [comment]
@Cioppolo14  work update! added a working copies and a detailed workflow guide section please review, quite a lot of work done 😅

**Working copies section**
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_07_02 PM](https://user-images.githubusercontent.com/72331432/232692242-9833fec7-c9f5-4210-a0b9-483a3da1c75e.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_07_13 PM](https://user-images.githubusercontent.com/72331432/232692274-c3bbc340-5aca-4ca9-aa80-9004d0564cac.png)


**Workflow section**
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_11_51 PM](https://user-images.githubusercontent.com/72331432/232693839-395b0460-d0d0-4f8d-8c37-62411bc6ae89.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_02 PM](https://user-images.githubusercontent.com/72331432/232693886-2d4cf6d8-2a5e-40a6-a781-b16f7b11c1cc.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_11 PM](https://user-images.githubusercontent.com/72331432/232693956-3ca5bf0d-7f32-4a9b-8c83-4f69ab4e607a.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_19 PM](https://user-images.githubusercontent.com/72331432/232694010-0ff6f8c5-f69f-421e-af61-a90097a3649c.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_35 PM](https://user-images.githubusercontent.com/72331432/232694055-5805edf8-b1d9-46ef-945a-7808158dd286.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_42 PM](https://user-images.githubusercontent.com/72331432/232694109-f699a560-0e9c-4c1b-a6df-fedc7f3d6409.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_42 PM](https://user-images.githubusercontent.com/72331432/232694222-789ae191-2e93-4005-8960-4da8718ced17.png)
![Working copies _ Talawa Project Documentation — Mozilla Firefox 4_18_2023 12_12_48 PM](https://user-images.githubusercontent.com/72331432/232694253-72d530ae-49af-40fa-a99c-2cd50acecf9b.png)

**Comment by Cioppolo14** [comment]
@Biki-das I am having some internet challenges, but I think you have the idea down. Just make sure to proofread everything. I'll give comments once my internet is more reliable.

**Comment by Biki-das** [comment]
> @Biki-das I am having some internet challenges, but I think you have the idea down. Just make sure to proofread everything. I'll give comments once my internet is more reliable.

sure i have completed the guide now just checking if links are ok and grammer etc is fine. currently what i have written would be enough for now later in future we can add more changes as needed!
