### ISSUE TITLE
Bug Report: Broken link for news.

### ISSUE THREAD

**Issue by Yogita-T** [PalisadoesFoundation/talawa-docs#626]
**Describe the bug**
The link should take the user to the Palisadoes news page, rather it throws **Page not found**

**Expected behavior**

![newsactual behaviour](https://user-images.githubusercontent.com/76475512/230422530-f7081d52-0417-43c8-a66c-6d1dadb02364.jpg)

**Actual behavior**
![pagenotfoundnews](https://user-images.githubusercontent.com/76475512/230422405-ac7b5925-b428-4502-be9a-6a78932bac72.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
The source document no longer exists. Please merge with the latest upstream. If the problem persists, then reopen the issue. The newsfeed will not be using the palisadoes.org news link. 

Closing
