### ISSUE TITLE
Feature Request:- Add the navbar, sidebar and table of content seperator .

### ISSUE THREAD

**Issue by Biki-das** [PalisadoesFoundation/talawa-docs#628]
**Is your feature request related to a problem? Please describe.**
Currently the documentation does not have a neat structure between the sidebar Navbar and the table of content, Adding the seperator makes the documentation neat and easy to differentiate.

**Describe the solution you'd like**
Overwriting the css to bring back the default borders which gave the page a divider among the sidebar navbar and Table of content, the results are below what it would like after doing the changes.

![Getting Started _ Talawa Project Documentation — Mozilla Firefox 4_8_2023 6_45_29 PM](https://user-images.githubusercontent.com/72331432/230723587-fbda3506-c3af-4dd8-b44d-4c752a3bcba3.png)
![Core Concepts _ Talawa Project Documentation — Mozilla Firefox 4_8_2023 6_48_34 PM](https://user-images.githubusercontent.com/72331432/230723613-09b043df-025a-47e9-9346-d45678db8aaf.png)

**This is what it looks like currently without the changes**

![Getting Started _ Talawa Project Documentation — Mozilla Firefox 4_8_2023 6_46_01 PM](https://user-images.githubusercontent.com/72331432/230723667-5640d23c-2323-450f-9cc1-3122e0a99aec.png)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Overwriting the css files to get the divider

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

For Talawa Docs, we will only be accepting issues related to item 3. Thank you for your submission.  I will close this issue.
