### ISSUE TITLE
Bug Report: Image Overlaps on mobile screens

### ISSUE THREAD

**Issue by Vic-Orlands** [PalisadoesFoundation/talawa-docs#633]
**Describe the bug**
On mobile screens, the images are overlapping and stretches outside the viewport.

**Expected behavior**
The images should be properly aligned so that it is centered in the mobile viewport.

**Screenshots**
First image:
![5F9B2BB0-061B-41C9-86C7-F724E2D65526](https://user-images.githubusercontent.com/53902215/231463374-a19d4a44-931d-40dc-9cab-bcb1f481a442.png)

Second image:
![151D3033-06E0-408B-9727-290B4D4DF38C](https://user-images.githubusercontent.com/53902215/231463710-1e9d8e53-5716-40a3-82b2-7b497454f799.png)

Third image:
![F9D0778A-08A1-4EC3-9E82-1AB3F8B87234](https://user-images.githubusercontent.com/53902215/231463775-42bf540b-bc5d-4458-bf76-243e7b4a010f.png)

**Comment by palisadoes** [comment]
The only ones that need fixing are:

## Rocket Ship Image
![image](https://user-images.githubusercontent.com/16875803/231511344-f2a00b51-c220-469b-be4b-1d1f163b3a05.png)
## Phone Animation
![image](https://user-images.githubusercontent.com/16875803/231511775-fddd4f96-9152-4638-bc69-3212b4f3ec6b.png)

Do not modify anything else.

**Comment by Biki-das** [comment]
@Vic-Orlands could you update me if you are working on this one? i am happy to work on this if you are not currently available to work on this!

**Comment by Biki-das** [comment]
@Cioppolo14  this can be closed, i have fixed this issue in #646 .
