### ISSUE TITLE
Bug Report: Desired features link doesn't work on ideas page

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-docs#636]
**Describe the bug**

Currently, the desired features link in the ideas page is redirecting an old URL:  https://docs.talawa.io/docs/internships/features/features-introduction

**To Reproduce**
Steps to reproduce the behaviour:

1.  Go to https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas
2. Click on desired features 
3. Link leads to 404 error
4.

**Expected behaviour**
Corrected link is 

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.
Should redirect here: https://docs.talawa.io/docs/features/features-introduction/
**Screenshots**
![image](https://user-images.githubusercontent.com/65951872/232000956-edc13d66-0885-4ee3-b49f-73e6649bb312.png)
![image](https://user-images.githubusercontent.com/65951872/232001093-34f7ff67-3218-4df3-afda-4f9517fc3f53.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
@palisadoes Sir, I'd like to work on this issue by fixing the link. please assign.

**Comment by Cioppolo14** [comment]
@SiddheshKukade Please change the link to go here: https://docs.talawa.io/docs/category/desired-features
