### ISSUE TITLE
The schema sub levels don't have descriptions

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#644]
**Describe the bug**
The sub levels of the schema are not accompanied by any explanations or descriptions.

**Expected behavior**
We should add a short description of what the command does

**Screenshots**
It would be beneficial to include brief descriptions on some pages, similar to this one, to assist users in better understanding the commands being presented.
![image](https://user-images.githubusercontent.com/97171261/233618867-3e3eaa28-153b-4463-a8d1-a52e37f666d1.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
The comments are automatically generated from the code base in Talawa-API. This issue is addressing this deficiency:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1309

Closing
