### ISSUE TITLE
Feature Request: Adding customized issue labels for talawa suite

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-docs#648]
**Is your feature request related to a problem? Please describe.**
As the contributors to the talawa projects are increasing drastically year after year there are a lot of changes that are being added, changes or fixed everyday. Having some customized issues labels for our talawa apps and APIs would be great to links issues together and track them as parent of children of each other

**Describe the solution you'd like**
I'd like to extend the issue labels with the following:

### For Talawa-docs
`technical`: adding docs related to the technicalities of the talawa apps.
`user-guides`:  for adding docs related to onboarding new users, explaining new concepts in a non technical way,etc.
`design`: realted to the design of the docs website
`misc`: for other miscellaneous issues

### For Talawa-admin, API and Mobile

**COLORED IN LIGHTGRAY**
`parent`: The issue is generating more sub-issues
`children`: The issue which is generated due to other parent issue.

**COLORED IN YELLOW**
`figma`: issue related and being worked with the figma file of the Admin UI

 **ALL COLRED IN PURPLE**
`area/performance`: related to improving performance of website
`area/ci-cd`:  relted to CI/CD workflow
`area/tests`:  related to adding tests
`area/ux`: relted to UX improvements
**`component/api`: Issues related to the talawa API**

**ALL COLORED IN WHITE**

`issue/blocked`: blocked due to another pending problem.
`issue/design-required`: Design template is require before proceeding
`issue/blocked`: remind tag to check issue in the future time (basically means issue is not relevant right now)
`issue/stale`: problem desribed is stale or outdated.

#### PR labels:

**ALL COLORED IN LIGHT BLUE**
`pr/do-not-merge`: Can't merge due to merge-conflicts of files or a important review is required.
`pr/on-hold`: if the linked issues is on hold 
`pr/dependancies`: related to adding dependancies in the project

**Describe alternatives you've considered**
Please suggest alternatives in comments

**Approach to be followed (optional)**
**IMPORTANT**: Someone with a member access to the Palisadoes Foundation is required to add the issue lables in each repo with the description

**Comment by SiddheshKukade** [comment]
Discussion link : #649

**Comment by SiddheshKukade** [comment]
This issue is created to add a page in the docs explaining how issues and labeling works in talawa,
Something like: https://handbook.rocket.chat/departments-operations/support/github-issues
but in a more detailed manner.

**Comment by Cioppolo14** [comment]
@SiddheshKukade I appreciate this idea and its use, I just want to caution you that it may not be sustainable from the volunteers side of things to keep up with this accurately and effectively.

**Comment by SiddheshKukade** [comment]
This is completed and the labels can now be used and are available at the following links
- https://github.com/PalisadoesFoundation/talawa-admin/labels
- https://github.com/PalisadoesFoundation/talawa-api/labels
- https://github.com/PalisadoesFoundation/talawa/labels
I'll close this issue now.

**Comment by SiddheshKukade** [comment]
- https://github.com/PalisadoesFoundation/talawa-docs/labels?q=pr%2Fdo-not-merge

**Comment by SiddheshKukade** [comment]
- https://github.com/PalisadoesFoundation/talawa-docs/labels
