### ISSUE TITLE
Migrate Talawa-API documentation to the Talawa-Docs Repo

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#65]
**NOTE:** [This issue is linked to one in the Talawa-API repo](https://github.com/PalisadoesFoundation/talawa-api/issues/221)

The [Legacy Talawa-API documentation website](https://talawa-api.readthedocs.io/en/latest/) needs to be migrated to the new [Talawa Docs website](https://palisadoesfoundation.github.io/talawa-docs/)

The steps to do this would be:

1. Create a major heading for Talawa-API in the Talawa-Docs repo
2. Migrate the existing [Talawa-API documents in the talawa-api repo](https://github.com/PalisadoesFoundation/talawa-api/tree/master/docs) to the Talawa-Docs repo. Note: The source documents are in RST format and will need to be converted to .MD format.
3. Inform @palisadoes when the pull request for this documentation is completed so that the legacy ReadTheDocs site can be removed.

Copy / pasting the documentation will not be enough. The documentation has changed. You will need to update the documentation so that it matches the current master branch functionality.

**Comment by adithyaakrishna** [comment]
@palisadoes Can I work on this?

**Comment by palisadoes** [comment]
It's already been assigned to @XshubhamX  in the talawa-api repo.

**Comment by XshubhamX** [comment]
Sir starting work on this with Sir @xsh2047
