### ISSUE TITLE
Remove the extra Table of Contents

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#655]
**Is your feature request related to a problem? Please describe.**
In the Talawa-API docs, there are 2 Table of Contents, one at the right and one in the beginning of the doc

**Describe the solution you'd like**
Planning to remove one to reduce redundancy 

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-docs/assets/97171261/88000b34-993f-4928-b0d9-62ee015c5c8e)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@Nitya-Pasrija Just for clarification, are you just removing the "table of contents" phrase in one of the locations, or the entire section?

**Comment by Nitya-Pasrija** [comment]
@Cioppolo14 
It was aimed for one of the locations, 2 table of contents seemed a lil redundant

**Comment by palisadoes** [comment]
@Nitya-Pasrija Are you still working on this?

**Comment by Nitya-Pasrija** [comment]
We can close this, as it will be automatically resolved through turndown files

**Comment by Cioppolo14** [comment]
Closed per @Nitya-Pasrija's comment.
