### ISSUE TITLE
Re-introducing the dark theme

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#658]
**Describe the solution you'd like**
- Re introducing the dark theme is a crucial element of a documentation website
- Slack connect link needs to be fixed as well

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@Nitya-Pasrija We have to close this.

1. The slack link changes every 30 days. That is why we have it in a single location on the README.md file.
2. We decided against a dark theme earlier this year as it required us to re-design images to be compatible. It also meant that every PR would have to be tested against the dark theme. For documentation, we also felt that it was not a priority.
