### ISSUE TITLE
Generating a "Getting Started Document Guide"

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-docs#661]
**Describe the solution you'd like**
This functionality guide will assist users in smoothly familiarizing themselves with the application and provide guidance on accessing its features.

**Comment by palisadoes** [comment]
@Nitya-Pasrija Please add more detail.

**Comment by Nitya-Pasrija** [comment]
@palisadoes 

The guide would help offer an in-depth overview of the application's user interface (UI), highlighting key elements and explaining their functions. It should cover aspects such as menus, buttons, and navigation options, ensuring users understand how to interact with the UI effectively, for both Talawa as well as Talawa Admin.

Furthermore, the guide should provide detailed instructions on accessing and utilizing specific features of the application. This may include step-by-step guides for tasks such as creating new events, post creations, customizing language settings, etc.
It will also be organized in a logical manner, with clear headings, subheadings.

Overall, the aim of the functionality guide is to empower users to quickly and efficiently familiarize themselves with the application and confidently utilize its features, ensuring a seamless and productive user experience.
