### ISSUE TITLE
Bug Report: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [PalisadoesFoundation/talawa-docs#676]
**Describe the bug**
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

**To Reproduce**
Scroll to bottom and see old twitter logo

**Expected behavior**
The Twitter logo should be changed to X.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
<img width="960" alt="266578703-10e81d39-e9db-41da-921b-ba4ebcfcb2d2" src="https://github.com/PalisadoesFoundation/talawa-docs/assets/91591901/402b0639-7fe3-44a3-a175-9d4c95973565">

**Additional details**
@palisadoes
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by 0xV0YD** [comment]
@palisadoes   i have made a pr for this issue please look at it

**Comment by vinfinity7** [comment]
@palisadoes May i work on this issue?  Its a 2 minute job

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by DhairyaMajmudar** [comment]
@palisadoes I would love to work on this issue. PLs. assign it to me

**Comment by umangutkarsh** [comment]
@palisadoes, if no one is working on this, please assign it to me. Will finish this asap.

**Comment by DhairyaMajmudar** [comment]
> @palisadoes, if no one is working on this, please assign it to me. Will finish this asap.

I am working on this issue
