### ISSUE TITLE
Upgrade Talawa-Docs to Docusaurus v3.0

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#685]
**Is your feature request related to a problem? Please describe.**
We need to upgrade to the latest version of docusaurus to take advantage of the latest features.

**Describe the solution you'd like**
You can do this by following the process outlined on the docusaurus site:

- https://docusaurus.io/docs/migration/v3

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- Follow the steps above

**Additional context**
- The functionality of the existing v2.x site must be maintained.
- Run the upgraded website on your local system to verify functionality

**Comment by disha1202** [comment]
Hi,
I would like to work on this.

**Comment by disha1202** [comment]
Hi @palisadoes, 

For migrating to V3 there will be a lot of changes, it will be difficult to test and review. Can we first prepare the site for migration [https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3](https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3) and also have multiple PRs. Each PR can consist of 3-4 md files. 

What do you think?

**Comment by palisadoes** [comment]
This should be done in a single PR.

1. The site is small. 
1. The content is mostly simple text. 
1. The upgrade process has a script you can run to find compilation errors
1. Our volunteer reviewers have limited time to review the dozens of PRs you are proposing
1. You can easily test the changes on your local system by running docusaurus there.
