### ISSUE TITLE
Improve Layout + Groundwork for Setting Up Multiple User Guides

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#686]
Our docs.talawa.io website has a major deficiency in that it focuses only on our developer community. It does not provide any documentation for either administrators or end users. It would also be useful to have a blog.

We want to make the following changes.

Maintain the current home page with updated links, namely:

1. User Guide – Directing to docs.talawa.io/users
    1. This must direct to a “User guide coming soon” page. We will add the rest of the pages later.
    1. This section must have its own completely separate left hand side menuing system.
    1. The documentation for this section must be located under the talawa-docs/users directory or some other unique name that minimizes confusion with other document trees.
1. Admin Guide - Directing to docs.talawa.io/admins
    1. This must direct to a “Admin guide coming soon” page. We will add the rest of the pages later.
    1. This section must have its own completely separate left hand side menuing system.
    1. The documentation for this section must be located under the talawa-docs/admins directory or some other unique name that minimizes confusion with other document trees.
1. Developer Guide - Directing to our existing docs.talawa.io/docs URI
    1. The current left hand side menuing system must be maintained
    1. The documentation for this section must be located under the existing talawa-docs/docs directory
    1. All CI/CD integrations with other repos must not break. These integrations must operate and update the correct document trees when updated. For ease of implementation you may consider using the existing directory structure for these integrations.
1. Blog - Directing to docs.talawa.io/blog
    1. Consider using the default blog plugin: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog 

We have done some research and discovered that it is possible to have multiple document URIs in a single docusaurus instance:

- https://stackoverflow.com/questions/60783595/is-there-a-way-to-have-two-docs-in-docusaurus-2 

Please work with @tasneemkoushar and @anwersayeed who have worked extensively with our CI/CD integrations. Ask to be assigned this task by them.

**Comment by palisadoes** [comment]
@disha1202 would you be interested in tackling this issue?

**Comment by disha1202** [comment]
> @disha1202 would you be interested in tackling this issue?

Yes, I'm interested in working on this issue.
