### ISSUE TITLE
Adding Docker Support Details for Talawa-Admin

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-docs#689]
**Title:**
Adding Docker Support Details for Talawa-Admin

**Description:**

**Changes Needed:**
The documentation for Talawa-Admin currently lacks information about Docker support. We need to update the documentation to include details on setting up and running Talawa-Admin using Docker.

**Context:**
Adding Docker support is a significant enhancement, and users would benefit from clear instructions on how to leverage Docker for deploying Talawa-Admin. The documentation should cover:
1. Instructions for creating and running Docker containers.
2. Configuration options related to Docker deployment.
3. Any considerations or best practices for using Talawa-Admin with Docker.

**Additional Notes:**
Consider including code snippets, commands, or screenshots to make the documentation user-friendly and easy to follow.

**Potential internship candidates:**
This documentation update provides an opportunity for internship candidates to contribute to the Talawa project by enhancing user guidance related to Docker. It involves documentation writing and collaboration with the development team.

**Comment by palisadoes** [comment]
Talawa docs does not require docker to run. It is a docusaurus project.

Closing
