### ISSUE TITLE
Bug: Not responsive icons

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [PalisadoesFoundation/talawa-docs#691]
**Describe the bug**
Both icons are not in their proper position on mobile devices.
<img width="136" alt="image" src="https://github.com/PalisadoesFoundation/talawa-docs/assets/69814563/a4df02e6-e8f1-4f6f-a0a4-d03d89cbdb4c">

**Comment by palisadoes** [comment]
Thanks. We are focusing on the content of the repository at this time. Closing
