### ISSUE TITLE
Icons and their corresponding names are not properly aligned in the footer.

### ISSUE THREAD

**Issue by KshitijTodkar48** [PalisadoesFoundation/talawa-docs#692]
The icons of Community, Social-Media handles and Development in the footer are not properly aligned with their corresponding names.

**Steps to reproduce the behavior:**

1. Go to https://docs.talawa.io/
2. Scroll down to footer.

**Expected behavior**
The icons and names should be aligned properly.
![Screenshot 2023-11-23 184535](https://github.com/PalisadoesFoundation/talawa-docs/assets/120639775/12715325-b774-4f64-bfec-03ea447a3d4a)

**Actual behavior**
![Screenshot 2023-11-23 183546](https://github.com/PalisadoesFoundation/talawa-docs/assets/120639775/17862ffb-eb12-44b0-a5a7-12c2231c3957)

**Comment by KshitijTodkar48** [comment]
I would like to fix this.

**Comment by palisadoes** [comment]
We are not doing any styling changes to the site at this time. Closing.
