### ISSUE TITLE
Updating Talawa Docs with official UI figma file 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-docs#695]
**Is your feature request related to a problem? Please describe.**
Attaching  official UI figma file in the  Talawa Docs.

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
How's this going?
