### ISSUE TITLE
Talawa logos with text required

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#71]
Our current logos do not have `Talawa` text. This creates some issues:

1. It is difficult to define our typography when the `Talawa` text is used beside the logo.
2. It makes it difficult to have a consistent user experience when using our various web and mobile apps.

We need additional logo files with proportionately sized text:

1. Beside and to the right of the logo
2. Centered and below the logo

Other guidance

1. The new files must use the existing ones as the starting template
2. The new files with text must have the same names as the existing files, but with the suffix text `with-text-vertical` and `with-text-horizontal` added before the filename extension.

Some other factors to consider:

1. The text must not dominate the logo.
2. These logos must be added to the logo repository directory.
3. Use our [Typography Guidelines](https://palisadoesfoundation.github.io/talawa-docs/docs/) found in the branding section of our documentation

**Note:** Please use the GitHub issue auto closing feature when working on this issue.

**Comment by adithyaakrishna** [comment]
@palisadoes Can I take this up and Work on it?

**Comment by adithyaakrishna** [comment]
Thank You @palisadoes 
Just a doubt, is color logos also needed? 
if not, I would give the logos in 2 versions **black and white** with transparent and non-transparent options
