### ISSUE TITLE
typo: In idea page of GSoC

### ISSUE THREAD

**Issue by OmAximani0** [PalisadoesFoundation/talawa-docs#722]
**Describe the bug**
The section **[Fail Safe](https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas/#fail-safe)** is having a typo where the word should be `fixing` but it is typed as `ixing`.

**To Reproduce**

1. Open this [link](https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas/#fail-safe:~:text=.%20ixing%20this%20would%20greatly%20help%20the%20project%20and%20will%20increase%20the%20developer%20base%20we%20can%20attract.)

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-docs/assets/75031769/bb6ebec2-6093-413c-b73e-65c5b88de1af)

**Additional details**
If it's okay, I'd be happy to take this on. Please feel free to assign it to me.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Thanks, this is a draft document and will be proof read by the team later.

Or current priorities can be found here:
- https://youtu.be/iYdyBfXdV2w?si=t6vR0aRgTwhORzFY

Closing
