### ISSUE TITLE
Feature Request : Shifting to nextjs and making over to effiecient documenation 

### ISSUE THREAD

**Issue by kunjgit** [PalisadoesFoundation/talawa-docs#725]
**Is your feature request related to a problem? Please describe.**
I want to have whole documentation makeover to the nextjs with markdown documentation by having static site generation 

**Describe the solution you'd like**
I will be working on this issue for longer amount of time in observation and will be updating the things weekly
my strategy is to make the documenation better with better UI !

**Approach to be followed (optional)**
I will be approaching to this whole transformation by following the existing ui and also making some creative changes by approving them with team 
in first 2 weeks I will target to make the home page and documentation setup !
in later 2-3 weeks  period I will be completing the stuff to migrating from the existing documentation 

**Additional context**
I have really good experience in working with NextJs and static site generation with markdown 
here are few of my work that I am pinging you [CertiCraft](https://certicraft.co)
and another one which is having documentation itself [GitGinie](https://gitginie.co)

**Comment by kunjgit** [comment]
Please assign me this issue !
I would love to contribute and have some good make over for the documentation .

**Comment by palisadoes** [comment]
1. We will not change our documentation system from Docusaurus. It is supported by Meta / Facebook
1. Closing
