### ISSUE TITLE
UI Improvements in Navbar-Sidebar

### ISSUE THREAD

**Issue by antriksh-9** [PalisadoesFoundation/talawa-docs#734]
In mobile view: 
Improving the margin-left property of the menu list items that opens up after clicking on navbar toggler.
The items are very close to the left-end of the screen which lowers the UI of the website when viewing in small screen.

The problem: 

![Screenshot 2024-01-14 005304](https://github.com/PalisadoesFoundation/talawa-docs/assets/132576984/9440ca95-393d-4f2f-a32c-d45aedc6012a)

The Solution: 

![Screenshot 2024-01-14 005314](https://github.com/PalisadoesFoundation/talawa-docs/assets/132576984/78ff6afb-f951-4362-87e1-218dee42ed31)

**Comment by antriksh-9** [comment]
Hey @noman2002 @Ayush0Chaudhary 
I want to work on this issue.
Please assign it to me.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by antriksh-9** [comment]
Hey @palisadoes What about adding a feature a "Scroll to Top Button" that helps user to smoothly navigate through the website. 
Can I open issue for that?

**Comment by palisadoes** [comment]
Yes. But we will immediately close it for the reasons above.
