### ISSUE TITLE
Issue: Links Not Found in The Palisadoes Foundation's GSoC Ideas List

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [PalisadoesFoundation/talawa-docs#765]
**Describe the bug**
Several important links referenced in The Palisadoes Foundation's GSoC (Google Summer of Code) Ideas List are not found. These links are crucial for potential applicants to access relevant information, guidelines, and resources to participate effectively in the GSoC program under The Palisadoes Foundation.

**To Reproduce**

1. Click https://docs.talawa.io/docs/internships/gsoc/gsoc-introduction/
2. Go to the 8 point and you can see the :
**Affected Links:**
-GSoC Application Guide
-Selection Criteria
-Application Template
-Conflict of Interest Policy
-GitHub Quick-Start Guide

**Expected behavior**
The expected behavior is that all links provided in The Palisadoes Foundation's GSoC Ideas List should lead to the respective resources mentioned. Each link should direct users to the relevant documentation, guidelines, or policies without encountering any errors or broken links.

**Actual behavior**
Upon reviewing The Palisadoes Foundation's GSoC Ideas List, it was observed that several links were missing or led to non-existent pages. This deviation from the expected behavior hinders potential applicants' ability to access essential information, resulting in a lack of clarity and potential confusion regarding the application process, selection criteria, and relevant policies. It is imperative to rectify this discrepancy promptly to ensure a smooth and accessible application experience for all prospective participants.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-docs/assets/94298791/332766c1-ad06-4151-8f11-7a5594c8cb49)

https://github.com/PalisadoesFoundation/talawa-docs/assets/94298791/26864ef9-995b-4d9d-844d-9dbf0fd892d8

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by i-am-SnehaChauhan** [comment]
@Cioppolo14 I am interested in contributing to this project. Could you please assign this to me? Pages are already exist but not linked so i will link them.

**Comment by palisadoes** [comment]
Closing. This is not a priority
