### ISSUE TITLE
Remove references to the deprecated Docusaurus v1.14.7 package

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#791]
**Describe the bug**

1. The www.talawa.io website is generated by the Docusaurus build process.
2. The build process references packages in the `package.json` file
3. There is a reference to deprecated `Docusaurus v1.14.7`
4. When this reference is removed, the generated site breaks

**Expected behavior**

1. A way must be found to remove the Docusaurus v1.14.7 reference without breaking the site
2. References to deprecated `Docusaurus v1.14.7` libraries must be replaced with references to the latest Docusaurus `v3.x` package currently being used.
3. The site functionality must not be affected in any way after the change

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-docs/assets/16875803/1d434af9-39e3-48aa-bba3-c31e367eb000)

**Additional details**

- N/A

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi 
I know I already have 2 issues assigned but can I work on this as I have already worked on migrating docusaurus from v1 to v3.

**Comment by palisadoes** [comment]
@disha1202 How is this going? We just had to upgrade Docusaurus again. The deprecated code reference needs to be removed.

**Comment by disha1202** [comment]
Hi @palisadoes 
I have removed the references of Docusaurus v1.14.7

Please take a look.
