### ISSUE TITLE
Migrate docs from talawa to talwa-docs

### ISSUE THREAD

**Issue by jordanliu** [PalisadoesFoundation/talawa-docs#8]
We're now using a centralized repository containing documentation for both repos. As a result, we'll be needing to migrate the docs that are in talawa which is rst to markdown

https://github.com/PalisadoesFoundation/talawa/tree/master/docs

**Comment by KhyatiSaini** [comment]
Hello sir, I would like to work on this issue, please assign me this issue.

**Comment by jordanliu** [comment]
Hey @KhyatiSaini, assigned.

**Comment by MayankVir** [comment]
Hey @jordanliu Is this issue open for work?
