### ISSUE TITLE
Fix Talawa-API broken links visible when starting the Talawa-Docs app

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-docs#821]
**Describe the bug**
When starting Talawa-Docs there are numerous references to broken links in the console. Most, **but not all,** are related to  `README.md` files

**To Reproduce**

1. Start Talawa-Docs
2. The console shows broken links

**Expected behavior**

1. Start Talawa-Docs
2. No broken links are discovered in startup.
    1. The end user must get no 404 errors when clicking any link in talawa-docs generated websites
4. All other web page content is maintained.

**Actual behavior**

- See above

**Screenshots**

**Additional details**

![image](https://github.com/PalisadoesFoundation/talawa-docs/assets/16875803/fe4129bb-0f6e-4150-bb9a-2fa3cd1e3989)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ghost** [comment]
Hey @palisadoes, Can I work on this issue ?

**Comment by ghost** [comment]
Hey @palisadoes , @Cioppolo14 Can you help me a little bit , can't I just change onBrokenLinks & onBrokenMarkdownLinks to "ignore" from "warn" in docusaurus.config.js file or do you want me to remove all those warning links ?

**Comment by palisadoes** [comment]
The user will click on the links and get 404 errors. We can't have that. That's poor UI/UX design.
You need to fix the root cause, not hide the issue.

**Comment by Aloksh42** [comment]
Okay @palisadoes

**Comment by ghost** [comment]
Hey @palisadoes , I have created a PR , can you please look at it
