### ISSUE TITLE
Image Blurring During Scrolling in Talawa Documentation

### ISSUE THREAD

**Issue by Annu881** [PalisadoesFoundation/talawa-docs#920]
**Describe **
I noticed that images in the Talawa documentation appear clear when the page is static, but they become blurry while scrolling or during page transitions. This affects the user experience, especially when viewing important visual content in the documentation.

**To Reproduce**

1.Open the Talawa documentation page [https://docs.talawa.io/]
2.Scroll up or down the page containing images.
3.Observe that the images become blurry during the scrolling motion but sharpen when scrolling stops.

**Expected behavior**
The images should remain sharp and clear during scrolling, ensuring a professional and seamless documentation experience.

**Actual behavior**
The images become blurry or pixelated during scrolling, temporarily degrading their quality.

**Screenshots**
![WhatsApp Image 2024-12-30 at 04 35 37_d1a67560](https://github.com/user-attachments/assets/1677c5f1-e66b-49dd-92f8-89e71ea609f3)
![WhatsApp Image 2024-12-30 at 04 36 29_674f2302](https://github.com/user-attachments/assets/cfba278d-ff1c-4031-b6ce-739e94789f40)

**Additional details**
Impact: This issue affects the readability and professionalism of the Talawa documentation, especially for users relying on visual elements to understand functionality.
Priority: While this may not be critical to functionality, addressing it would significantly improve the user experience.
Frequency: The issue occurs consistently during scrolling or page transitions on the documentation site.
Platform-Specific Observation: This behavior was observed on [specify platform/browser, e.g., Chrome on Windows 11]. Similar behavior may occur on other platforms.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Thanks

1. We are currently redesigning the website. This won't be an issue. 
2. Closing
